Allow adding UI textures from mod folders
FAForever/fa pull request #3109
Opened 2020-05-16 16:08 UTC by wodzu93

Second try at allowing mods to add/modify UI textures. Note, for some reason init_XXX.lua files are not being deployed through the client, despite github changes being merged correctly. This change was already done and approved to init.lua in patch 3710, but hasn't been deployed so far. #2935

2020-05-16 19:47 UTC, KionX commented
Deploying init_*.lua is broken.

2020-05-30 15:38 UTC, shalkya commented
As kion said this is a deployment issue. We will wait till it get fixed, and see if this PR is required (i don't think so) then i will close or merge it.

2020-05-30 15:38 UTC, axel1200 commented
not broken the faf-java-api was never intended to deploy init.lua :D But yes would be good if it did

2020-09-07 16:40 UTC, ThrashAbaddon commented on init_faf.lua
> +                          mount_dir(MODFOLDER..'\\'..mod..'\\textures\\ui', '/textures/ui')
Something  like clang-format

2020-11-14 23:42 UTC, HUSSAR-mtrela requested changes

2020-11-14 23:42 UTC, HUSSAR-mtrela commented on init_faf.lua
> +                          mount_dir(MODFOLDER..'\\'..mod..'\\textures\\ui', '/textures/ui')
@wodzu93 can you add "meshes" folder like you did with "textures" folder. So mods can also add/change dds files in meshes folder.

2020-11-15 10:08 UTC, speed2CZ commented on init_faf.lua
> +                          mount_dir(MODFOLDER..'\\'..mod..'\\textures\\ui', '/textures/ui')
Mods cant do that right now?
There are new mods with units and props and what not, and they all add new meshes.

I thought this is about adding support mainly for strategic icons, as their path is hardcoded.
Any other texture that you use via Lua can be pretty much anywhere and you just specify path for that (sure having it in the texture folder wont hurt)

2020-11-16 19:59 UTC, HUSSAR-mtrela commented on init_faf.lua
> +                          mount_dir(MODFOLDER..'\\'..mod..'\\textures\\ui', '/textures/ui')
@speed2CZ sorry, I meant to say that UI mods cannot change existing meshes because paths to those files are hardcoded in (original FA) SIM files, e.g. 
```
/lua/SimPing.lua(48):  ping:SetMesh('/meshes/game/ping_'..data.Mesh)
/lua/SimPing.lua(84):  ping:SetMesh('/meshes/game/ping_'..data.Mesh)
```
Also, meshes are hardcoded in some FAF files, e.g.
[/lua/ui/game/commandmode.lua](https://github.com/FAForever/fa/blob/develop/lua/ui/game/commandmode.lua#L164)
[/lua/skins/skins.lua](https://github.com/FAForever/fa/blob/develop/lua/skins/skins.lua#L20)

So adding `/meshes/` folder to `init_faf.lua` should resolve this limitation.

2020-11-16 20:13 UTC, speed2CZ commented on init_faf.lua
> +                          mount_dir(MODFOLDER..'\\'..mod..'\\textures\\ui', '/textures/ui')
you can hook those functions and tables and set your own path, or am I missing something?

2020-11-16 21:24 UTC, HUSSAR-mtrela commented on init_faf.lua
> +                          mount_dir(MODFOLDER..'\\'..mod..'\\textures\\ui', '/textures/ui')
the SimPing.lua as its name suggest it is run on SIM side so UI mods cannot change it. I even created UI mod where I tried to hook /meshes/ folder with my own version of those ping's .dds files but they were not loaded by the game because the path is hard coded in the SimPing.lua file. Therefore, I kindly ask to add /meshes/ folder to init_faf.lua

2020-11-16 21:28 UTC, speed2CZ commented on init_faf.lua
> +                          mount_dir(MODFOLDER..'\\'..mod..'\\textures\\ui', '/textures/ui')
Fair enough

2021-07-18 21:05 UTC, shalkya commented
I think that PR can be closed now, since the init got fixed. Comment here if it's still needed and need to be reopened.

2021-07-18 21:05 UTC, closed without merging