Lobby mod options
FAForever/fa pull request #3144
Opened 2020-08-03 19:15 UTC by Garanas

This allows simulation mods to have game options in a similar manner to map options. All selected simulation mods will add their options to the options list dynamically. Adding an additional mod or removing a mod will add or remove their options. The options are defined in a mod_options.lua file which resides next to the mod_info.lua file in the mod directory.

<a href="https://ibb.co/5TYghhB"><img src="https://i.ibb.co/G7s4QQc/mod-options.png" alt="mod-options" border="0" /></a>

Additionals:
 - Changes 'Advanced' into 'Map Options'. The English and Russian languages are part of the pull request. Other languages will follow suit.
 - Map options that are not chosen will have their defaults set, as described in #3138 
 - Mod options that are not chosen will have their default values set

The order of the options are now:
 - Team options
 - Game options
 - Mod options
 - Map options
 - AI options

The AI options are at the bottom but perhaps making them 3rd is better because they do not change in size.

This does introduce a long list of options when a map with options and loads of mods with options are selected, will be adding for a way to 'show/hide' a set of options.

What I haven't tested yet:
 - Whether or not the options are propagated through the network. I think they are because I add them like any other changed option. I'll test this next week with someone that also has the development environment setup.

2020-08-04 13:31 UTC, Garanas commented
Latest version:

Options when selecting a map:
<a href="https://ibb.co/6128tR3"><img src="https://i.ibb.co/KLYDsjM/map-select-dialog-1.png" alt="map-select-dialog-1" border="0"></a>

Options when in lobby:
<a href="https://ibb.co/YWT9xvf"><img src="https://i.ibb.co/z5HczKP/lobby-1.png" alt="lobby-1" border="0"></a>

Both pieces of UI support:
 - Sections (title in code)
 - Subsections (subtitle in code)
 - Option (typical option)
 - Space (blank space)
 - Text (some text)

All map and mod options have tool tips that are defined in the files themselves and these function properly. All the titles no longer have tool tips (this happens when you scroll down / back up: the last tool tip that was at the position of a section / title would then be applied to the section / title).

A more generic approach to data formatting is chosen: a very flat data structure that is then piece by piece converted to their corresponding UI structure. You can view this structure in OptionUtil.lua.

A new file: OptionUtil.lua that helps you process all those options from various sources. Helps processing and structuring the options from the Team Options, Game Options, AI Options and Map / Mod Options sources.

Map and Mod options that are not set will have their defaults set on launch.

Would love to hear what people think.

2020-08-09 15:51 UTC, Garanas commented
``` lua
-- lobby.lua
-- Add lobby options from AI mods
function ImportModAIOptions()
    local simMods = import('/lua/mods.lua').AllMods()
    local OptionData
    local alreadyStored
    for Index, ModData in simMods do
        if exists(ModData.location..'/lua/AI/LobbyOptions/lobbyoptions.lua') then
            OptionData = import(ModData.location..'/lua/AI/LobbyOptions/lobbyoptions.lua').AIOpts
            for s, t in OptionData do
                -- check, if we have this option already stored
                alreadyStored = false
                for k, v in AIOpts do
                    if v.key == t.key then
                        alreadyStored = true
                        break
                    end
                end
                if not alreadyStored then
                    table.insert(AIOpts, t)
                end
            end
        end
    end
end
ImportModAIOptions()
```

This is how other mods load in options as of writing. Would be be terrible if I remove this piece of code and load in options from both _<mod>/mod_options.lua_ and _<mod>/hook/lua/ai/lobbyoptions.lua_, such that mods taking this approach are nicely added in the new UI from this PR?

@Uveso , would that mess with your AI in some way? I recall it being a mod (at the very least Swarm is). The options would still be added in regardless of whether they were set, just like any other option.

2020-08-11 12:33 UTC, Garanas commented
According to people from the AI development channel it wouldn't interfere:
<a href="https://ibb.co/Kw59wcP"><img src="https://i.ibb.co/6By4BcM/ai-options.png" alt="ai-options" border="0"></a>

I've removed the old approach to loading in additional options and added them to the current approach.

2020-08-13 16:52 UTC, Garanas commented
The latest version now also supports detailed information on mods:

<a href="https://ibb.co/cxZd36W"><img src="https://i.ibb.co/R7sWb3X/mod-support-section.png" alt="mod-support-section" border="0" /></a>

The little icon (this is a temp icon) is a button that allows you to click for additional information.
<a href="https://ibb.co/XDfZsRn"><img src="https://i.ibb.co/C6p57Gj/mod-support-section-default.png" alt="mod-support-section-default" border="0"></a>

On default the description of the mod is shown. Some descriptions are too long for the mod manager view.
<a href="https://ibb.co/PQ6JRMw"><img src="https://i.ibb.co/fvxZb94/mod-support-section-defined.png" alt="mod-support-section-defined" border="0"></a>

If there is a mod_details.lua file defined and it contains a specific function (which I will document clearly), then a mod owner can define custom pages. This is to mimic the 'information box' of Phantom, but then on a more generic way. The intension is to have a button on the main lobby for featured mods, such as Phantoms.

<a href="https://ibb.co/Y8bcCdW"><img src="https://i.ibb.co/ctx6B8v/mod-support-section-error.png" alt="mod-support-section-error" border="0"></a>
On default, errors in pages are hidden. This is to prevent the game from getting into an unstable state. You can still show the errors, which is useful for developers. Pages are constructed using the _pcal_ function.

2020-08-13 19:13 UTC, HUSSAR-mtrela commented
I like most of these improvements and I will review your code later. 
@Garanas it would be awesome if you could make these new Mod Option work with modding blueprints, e.g. see this [PR#3017](https://github.com/FAForever/fa/pull/3017) made by @Exotic-Retard 
This way, a lot of similar mods:
- Resources Rich x2
- Resources Rich x4
- Resources Rich x10
could be replaced with just one mod that add Mod Option, e.g 
- Resources Rich X times (in Mod Options)

2020-08-13 22:07 UTC, Garanas commented
If I am correct, that would already be possible with this PR. The mod _Resources Rich_ would then have an option (a lot like King of the Hill in the images) and that would determine the multiplier. Which can range from anything you'd want it to. We could even add sliders and things if that would be interesting for some reason.

Famous last words. Tried to make a repo that shows that it is already possible, only to run into the exact problem I think you are describing. See also: https://gitlab.com/w.b.wijnia/resource-rich

The variable ScenarioInfo isn't defined there yet, hence no options can be passed along.

I've looked at the pull request you mention but I feel I am a bit in the deeps there - could someone give me a hand at how I should look at the code from Exotic? An approach to take?

2020-08-14 07:47 UTC, Garanas commented
It works!

If you add in a 'preload = true' field to the option inside the options file it becomes available to PreGameData, which in turn makes it available inside blueprint modding. 

The following version of Resource Rich is can be customized in the options:
https://gitlab.com/w.b.wijnia/resource-rich

I am not super satisfied with the naming conventions, as those are important to keep the code clear. Perhaps instead of:
 - preload -> blueprintOption
 - PreGameData -> blueprintData

I'm not really satisfied with that either. Next up is allowing map and mod options to be loaded from preferences, allowing you to keep the options from last time whenever you set them.

I am also thinking of adding presets of options that the developer can set. This allows you to ensure that the intended experience for some situation can be achieved. An example is for survivals: if the average rating is between 800-1200 then options will be set such that the developer things you get the desired experience. I am talking with Rainmakers in the back of my mind here :)

2020-09-27 22:44 UTC, JeroenDeDauw commented
Thanks for doing this!

Being able to set options for mods is a game changer for mod authors. And for map authors. No need to add the same option to every map if a mod can take care of all maps.

Better grouping of the options in the lobby is also most welcome

2020-09-29 05:48 UTC, Garanas commented
I'll continue working on it next week. The response has been low at best - at some point I thought the majority of people weren't that interested. Cheers for letting your opinion known!

2021-09-07 01:13 UTC, HUSSAR-mtrela requested changes
please make these minor changes

2021-09-07 01:13 UTC, HUSSAR-mtrela commented on lua/maui/layouthelpers.lua
> +--* Copyright � 2005 Gas Powered Games, Inc.  All rights reserved.
undo this change because we do not use this encoding

2021-09-07 01:13 UTC, HUSSAR-mtrela commented on lua/factions.lua
> +            WARN(repr(t))
remove these LOG and WARN function calls. I think you added them when debugging/testing, right?

2021-09-07 01:13 UTC, HUSSAR-mtrela commented on lua/system/Blueprints.lua
> +    LOG("Called!")
please remove these LOG

2021-09-07 01:13 UTC, HUSSAR-mtrela commented on lua/system/Blueprints.lua
> +        LOG(repr(PreGameData))
remove 1st LOG and change 2nd LOG to SPEW('PreGameData: ' ..  repr(PreGameData))

2021-09-07 01:13 UTC, HUSSAR-mtrela commented on lua/ui/dialogs/mapselect.lua
> +            -- ???
remove "- ???" comment

2021-09-07 01:13 UTC, HUSSAR-mtrela commented on lua/ui/game/tooltip.lua
> +--* Copyright � 2005 Gas Powered Games, Inc.  All rights reserved.
undo this change because we do not use this encoding

2021-09-07 01:13 UTC, HUSSAR-mtrela commented on lua/user/prefs.lua
> +--* Copyright � 2006 Gas Powered Games, Inc.  All rights reserved.
undo this change because we do not use this encoding

2021-09-07 12:39 UTC, Garanas commented
If I recall right there were a few things wrong with this PR. I may pick it up again in the upcoming weeks.

2022-01-17 16:51 UTC, The-Balthazar commented on loc/US/strings_db.lua
> +lobui_0164="Map Options"
If you're changing the text you should make a new LOC key for it. Recycling keys is unnessesary and just increases the chance of translation rot.

2022-01-18 12:43 UTC, Garanas commented on loc/US/strings_db.lua
> +lobui_0164="Map Options"
I agree!

2022-02-05 09:11 UTC, Garanas commented
Closing this pull request in favor of https://github.com/FAForever/fa/pull/3654 .

2022-02-05 09:11 UTC, closed without merging