Reduce GetBlueprint() calls in weapons
FAForever/fa pull request #3193
Opened 2020-11-05 15:50 UTC by speed2CZ

Some were pretty obvious, just save the first call in a local variable and reuse.
Then saving some values directly in the weapon table and reusing them.

2020-11-08 15:25 UTC, KionX approved these changes
https://github.com/FAForever/fa/blob/f5564ff23dc860631712bebf41217eea59c59174/lua/sim/defaultweapons.lua#L446
Can delete it as it is checked in OnCreate

2020-11-08 20:00 UTC, HUSSAR-mtrela requested changes
this is a good implement but there are a few small changes that should be done in this PR.

2020-11-08 20:27 UTC, speed2CZ commented on lua/cybranweapons.lua
> +        local bp = self:GetBlueprint()
the question is if it's worth saving it like this, it's a big table

2020-11-08 21:27 UTC, KionX commented on lua/cybranweapons.lua
> +        local bp = self:GetBlueprint()
There is a global __blueprints table. You can store a reference to the blueprint.
Example:
```self.bp = __blueprints[self.unit:GetUnitId()].bp```

2020-11-08 22:15 UTC, HUSSAR-mtrela commented on lua/cybranweapons.lua
> +        local bp = self:GetBlueprint()
@KionX I think you meant to say ```self.bp = __blueprints[self.unit:GetBlueprintId()]```
@speed2CZ it is worth it because you are going to call GetBlueprint() only once. Also, memory is not a resource that affects sim speed but CPU time spent on executing function is.

2020-11-08 22:17 UTC, HUSSAR-mtrela commented on lua/cybranweapons.lua
> +        local bp = self:GetBlueprint()
@speed2CZ are you going to make similar improvements in other classes where are calling GetBlueprintId() and/or GetBlueprint() function multiple times?

2020-11-08 22:19 UTC, speed2CZ commented on lua/cybranweapons.lua
> +        local bp = self:GetBlueprint()
I already did in the past, I missed weapon file on that run. These changes follow the same format at my previous ones. So I'd keep it this way and then any other even better improvements can be done in next run.

2020-11-09 00:36 UTC, HUSSAR-mtrela commented on lua/cybranweapons.lua
> +        local bp = self:GetBlueprint()
alright

2020-11-09 00:36 UTC, HUSSAR-mtrela approved these changes

2020-11-11 14:38 UTC, HUSSAR-mtrela approved these changes

2020-11-19 20:38 UTC, merged