add decals/tree falling to more projectiles
FAForever/fa pull request #3200
Opened 2020-11-15 12:08 UTC by shalkya

also contains a rework of billy fx

2020-11-15 12:32 UTC, speed2CZ requested changes

2020-11-15 12:32 UTC, speed2CZ commented on effects/Entities/UEFBillyNukeEffect02/UEFBillyNukeEffect02_script.lua
> +		NullShell.OnCreate(self)
Fix indentation please

2020-11-15 12:32 UTC, speed2CZ commented on effects/Entities/UEFBillyNukeEffect02/UEFBillyNukeEffect02_script.lua
> +		local army = self:GetArmy()
self.Army should work here

2020-11-15 12:32 UTC, speed2CZ commented on effects/Entities/UEFBillyNukeEffect03/UEFBillyNukeEffect03_script.lua
> +		NullShell.OnCreate(self)
indentation again

2020-11-15 12:32 UTC, speed2CZ commented on effects/Entities/UEFBillyNukeEffect03/UEFBillyNukeEffect03_script.lua
> +		local army = self:GetArmy()
And self.Army again

2020-11-15 12:32 UTC, speed2CZ commented on lua/aeonprojectiles.lua
> +            local RandomFloat = import('/lua/utilities.lua').GetRandomFloat
move this import to the beginning of the file

2020-11-15 12:32 UTC, speed2CZ commented on lua/aeonprojectiles.lua
> +            DamageArea(self, pos, radius, 1, 'Force', true)
Why is this function called twice?

2020-11-15 12:32 UTC, speed2CZ commented on lua/sim/DefaultProjectiles.lua
> -        if not TargetEntity or not EntityCategoryContains(categories.PROJECTILE, TargetEntity) then
We have TECH1 to TECH3 categories, dont introduce there new hybrids

2020-11-15 13:34 UTC, shalkya commented on lua/aeonprojectiles.lua
> +            DamageArea(self, pos, radius, 1, 'Force', true)
that's how it works... I can't really tell you why. If you put it only once, trees disappears but if you put it twice, they fall down

2020-11-15 13:40 UTC, shalkya commented on lua/sim/DefaultProjectiles.lua
> -        if not TargetEntity or not EntityCategoryContains(categories.PROJECTILE, TargetEntity) then
I did try that, but for some reason it wasn't working.
I tested aeon tmd to stop billy. If i've TECH2 instead of TECH_TWO, the billy explode on impact.
No idea why though.

2020-11-15 14:05 UTC, speed2CZ commented on lua/sim/DefaultProjectiles.lua
> -        if not TargetEntity or not EntityCategoryContains(categories.PROJECTILE, TargetEntity) then
Im pretty sure its possible to make it work without introducing these categories

2020-12-06 18:14 UTC, shalkya commented
i'm summing up the value of LOD and duration of decals, that we have so far. It's not equalized so far.

1st value : LOD
2nd value : duration

AEON:
ACU OC : 150 40
ACU : 70 20
SCU with gun upgrade : 100 50
SCU : 70 20 

missile : 150 70

destro/battleship/T2 pd/T2 gunship : 150 50

T1 aeon bomber : 150 30
mercy : 200 70

salvation : 200 50
T3 static arty : 250 200
T3 mobile arty : 200 150
T2 arty : 200 100
T1 arty : 100 10

tempest : 250 100
CZAR : 200 150
GC : 100 100



CYB :
ACU OC : 150 40
ACU : 100 50

subnuke missile : 200 90
tml : 150 70
mml : 100 50

frigate / destro / cruiser / bs : 250 50

brick : 70 20
loya (heavy weapon)/ wailers : 70 20
loya (weak weapon)/ wagner / ML / SR : 50 15
heavyelectronbolter : 250 50

T2 gunship, SR, hoplite : 250 50 OR 100 50
beetle : 250 120
hoplite : 100 50
wagner : 70 20

T2 pd : 70 20

strat : 300 200
corsair : 150 50
T1 bomber : 150 30

scathis : 250 200
T3 static arty : 250 200
T3 mobile arty : 200 150
T2 arty : 200 100
T1 arty : 100 10

megalith : 400 70
ML / ACU lazer : 100 100



SERAPHIM :
ACU / SCU OC : 150 40
ACU with gun upgrade : 120 70
ACU / SCU : 70 20 

ACU / SCU / TML /MML : 200 90

BS : 250 50
destro / T2 pd : 70 50

ilshy / othuum : 120 50
T2 hover / othuum : 120 50
T2 gunship : 130 15

strat : 300 250
T2 bomber : 300 70
T1 bomber : 150 30

T3 static arty : 250 200
T3 mobile arty : 200 150
T2 arty : 200 100
T1 arty : 100 10

ythotha : 300 80 & 200 50



UEF :
ACU OC : 150 40
ACU : 70 20
SCU : 70 20

T3 MML : 70 20
T2 MML : 70 20
cruise missile (tml ?) : 70 50
cruiser : 70 20

BS : 100 70
BC : 85 70
fatboy / T2 pd / destro : 70 15
frigate : 50 15

perceval : 100 30
ravager : 70 30
mongoose : 100 50

T3 gs / T3 transport : 50 15
Titan : 50 15

sat : 250 100
mavor : 250 200
T3 static arty : 250 150
T3 mobile arty : 200 150
T2 arty : 200 100
T1 arty : 100 10

strat : 250 200
T2 bomber : 150 50
T1 bomber : 150 30

2020-12-29 08:51 UTC, Uveso commented
I have tested it in several games (about 30) and found no errors. 
Also no odd effect on gamespeed.

2021-06-30 23:24 UTC, shalkya commented
alright so i made a major update on that one. Most of the previous issue have been fixed (ie, friendlyfire, wrong damage for some projectiles...)
updated the list of LOD. It has been equalized, some values might still be a bit weird. I guess we will update that with player feeling, if they suggest values after playing with the decals.

2021-07-01 00:01 UTC, Uveso commented
Tested, did not found any errors.

2021-07-03 18:55 UTC, merged