Set rebuild progress based on ratio of mass to max possible wreckage mass
FAForever/fa pull request #3243
Opened 2020-12-30 15:15 UTC by Sheikah45

Addresses #3095 

This sets the rebuild progress from a wreck proportionally to the amount of mass left in the wreck compared to the buildCost*wreckageMult.

This has to retrieve the unit blueprint first to calculate the max wreckage mass for the unit. This could be avoided if overkill damaged the wreck rather than just changing the initial mass value.

Additionally this sets the maximum rebuild progress after ctrl king a building to 45% from 50% due to the difference in intial reclaim left vs the buildCost*wreckageMult.

2020-12-30 15:25 UTC, shalkya requested changes

2020-12-30 15:25 UTC, shalkya commented on lua/sim/Unit.lua
> +                    local MaxMassReclaim = bp.Economy.BuildCostMass * (bp.Wreckage.MassMult or 0);
there is no ; in lua

2020-12-30 15:35 UTC, Sheikah45 commented on lua/sim/Unit.lua
> +                    local MaxMassReclaim = bp.Economy.BuildCostMass * (bp.Wreckage.MassMult or 0);
whoops, habit

2020-12-31 07:34 UTC, Crotalus commented on lua/sim/Unit.lua
> +                    local progress = (p.ReclaimLeft * p.MaxMassReclaim) / MaxMassReclaim * 0.5
MaxMassReclaim could be 0 so need to add check for division by zero here,

2020-12-31 13:54 UTC, Sheikah45 commented on lua/sim/Unit.lua
> +                    local progress = (p.ReclaimLeft * p.MaxMassReclaim) / MaxMassReclaim * 0.5
Added a check

2020-12-31 13:55 UTC, Sheikah45 commented
As a note this also would change the rate for structures in water since they have halved mass anyway although this could be accounted for if desired

2021-04-10 17:34 UTC, shalkya commented
alright so i tested, this fix the main issue of rebuilding at 50% is fixed. It doesn't fix the issue of requiring to have a unit building the construction while it get killed in order to get the wreck.
As for water building, i would be up to take it with balance team, to not lower the mass if they get killed.

2021-04-10 17:37 UTC, merged

2021-04-10 17:39 UTC, Sheikah45 commented
I will look into it not leaving a wreck if not being built