Emojis
FAForever/fa pull request #3300
Opened 2021-06-04 17:50 UTC by 4z0t

Adds emojis in game chat and lobby chat
still required mod to access Packs for user emojis

2021-06-04 18:06 UTC, speed2CZ requested changes
Please put back table.empty() calls, that's the fastest way to find out if the teable is empty
Can you cleanup all the useless comments?

2021-06-04 19:23 UTC, 4z0t commented
> Please put back table.empty() calls, that's the fastest way to find out if the teable is empty
> Can you cleanup all the useless comments?

Done

2021-06-05 13:04 UTC, KionX commented
The code looks dirty. Trailing spaces, lots of empty lines, confused tabulation.
It looks like the PR is based on old code and can undo other changes.
Also, this PR is not self-sufficient. Should consider the option without mods.

2021-06-11 12:10 UTC, 4z0t commented
Any problems left? I think its done, and im awaiting your decision.

2021-06-11 12:42 UTC, speed2CZ commented
Well I look at the first file lua/ui/game/chat.lua and it has tons of commented out code.

2021-06-11 17:08 UTC, 4z0t commented
Seems to better now 🙂

2021-06-18 15:07 UTC, 4z0t commented
> Well I look at the first file lua/ui/game/chat.lua and it has tons of commented out code.
So, I think its about to be done, what do you think?

2021-06-21 18:42 UTC, Uveso commented
@4z0t 

How can i test this ?

2021-06-21 20:30 UTC, 4z0t commented
@Uveso i can send u some emojis to test

2021-06-23 01:05 UTC, Uveso approved these changes
Tested; also in multiplayer. Works good.
table.empty are also back.

2021-06-23 06:36 UTC, speed2CZ requested changes
There's still a lot of white spaces that needs to go. Clean it up please

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/chatarea.lua
> +        -- ChatLines = {
Why all this new whitespace?

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/chatarea.lua
> +
and here

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/chatarea.lua
> +
and so on

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/chatarea.lua
> +
two extra lines for nothing?

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/chatarea.lua
> +            authorName = '['..authorName..'] '
again spaces for nothing

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/chatarea.lua
> +                                                text = authorName,
If you're using tabs, convert it to 4 spaces

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/chatarea.lua
> +        table.insert(self.ChatLines, line)
again white spaces around this area

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/chatarea.lua
> +
one empty line is enough

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/chatarea.lua
> +
again just one  empty line please

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/emojis.lua
> +do
you dont need "do end" here, the code is executed when the file is imported. So just the function call is enough

2021-06-23 06:36 UTC, speed2CZ commented on lua/ui/lobby/lobby.lua
> +    while not table.empty(players)  do
Alse clean this file of white spaces

2021-07-01 00:20 UTC, Uveso commented
Tested (also multiplayer), works good.

2021-07-04 17:51 UTC, shalkya commented on lua/ui/lobby/lobby.lua
> +    --This is necessary because we don't want LUA searching through the globals as part of the benchmar
benchark
smh the k got eaten up in this pr

2021-07-04 17:55 UTC, shalkya commented on lua/ui/lobby/lobby.lua
> +    --scrlling
scrolling

2021-07-04 17:56 UTC, shalkya commented on lua/ui/lobby/lobby.lua
> +                LOG('set '..repr(checked)..' on '..repr(self.id))
LOG should be removed or at least commented

2021-07-11 23:16 UTC, shalkya commented
alright so from what I tested, it doesn't work in the lobby at first, even if it's ticked on by default. You actually need to untick, tick it on again, to make it work.
I would be better to fix that, so people aren't confuse. Either make it unticked by default, so they have to tick it. Or fix the issue of it not working the first time. I think you said something about having no data in the gamepref.

2021-07-14 22:19 UTC, shalkya commented
you still have the emoji completion on, even with the setting turn off in the lobby. It shouldn't display the completion, if that setting is off, like it's working in the game chat.

2021-07-14 22:42 UTC, 4z0t commented
@shalkya yeah, those options are separated, that means one could be turned on, but another off

2021-07-18 21:03 UTC, shalkya commented
i'm sorry but i don't see the setting to turn off to remove the completion in lobby for emojis. 
![image](https://user-images.githubusercontent.com/11618427/126081969-e9799dcc-2337-43a0-b459-5137c25661b0.png)
anyway (if there is several option like you are saying) the option for emojis showing in lobby and the one for completion of emojis in lobby should be the same.
But i think you didn't understand what i said before, and you were only commenting on the fact that there is one option for the lobby and another for the game. Which is not an issue.

2021-08-03 07:46 UTC, speed2CZ approved these changes

2021-08-13 17:22 UTC, Garanas commented
If I am correct these changes are reviewed and approved. I've fixed the conflict / will fix future conflicts and I'll merge this on Monday morning. Great work everyone!

2021-11-06 20:39 UTC, Garanas commented
[Packs.zip](https://github.com/FAForever/fa/files/7491211/Packs.zip)

Emoji pack provides by @4z0t to be stored here:

![image](https://user-images.githubusercontent.com/15778155/140623174-062700a5-fe67-42b3-b084-ecaf21424245.png)

2021-12-07 12:23 UTC, Garanas commented
Moved this PR to the next milestone. I intent to introduce a similar structure to the custom strategic icons where you can define a mod_emoticons.lua file that has a mapping of `key -> emotion`. In its current state other UI mods can not introduce emoticons.

2021-12-08 03:36 UTC, Sheikah45 commented
Shouldn't all emoticons supported be packaged with the base game? Since this is not something like strategic icons where only you will and are supposed to see it. If UI mods are the source for the emoticons then it will very easily end up being the case where one person thinks they are sending emoticons but the other person can only see text. And has no way of getting the emoticons unless they know exactly which UI mod to install. And even then there could be collisions between UI mods in terms of emoticon names.

2021-12-08 05:36 UTC, 4z0t commented
@Sheikah45 all emojis have package name and then their in-package name like `faf/uef`, so collisions may be only if packages are the same.

2021-12-08 08:32 UTC, Garanas commented
I'm fine if they become part of the base game, but then I propose we first make a selection and add it in before merging this.

2021-12-08 08:42 UTC, 4z0t commented
If we are going to add them in base game, then mb we have to ask community what emojis to add, that I'll convert into dds.

2021-12-08 08:54 UTC, Garanas commented
@4z0t Could you make a forum post about this? I'll get it into the news. Please make sure that you have the specifications (width, height, resolution - etc) and add that a submission doesn't mean it gets embedded - it merely means we'll consider it 😄 .

We can make this a bi-monthly thing - as embedding emoticons to the game is as easy as waiting for the next developers patch.

2021-12-09 15:02 UTC, Garanas commented
Reminder to ping the moderators before we merge any emoticons:
 - [ ] Moderators confirmed emoticons are good to go.

2022-02-06 21:37 UTC, Garanas commented
After discussing it with 4z0t, I am closing this pull request. The forum post on what emoticons to add didn't get enough traction. This pull request still requires quite a bit of work - as an example, if UI mod support is enabled then it needs a similar framework as the strategic icons loading has. But then during the lobby already.

2022-02-06 21:37 UTC, closed without merging