Category miss match
FAForever/fa pull request #3324
Opened 2021-07-13 08:39 UTC by Garanas

A few units from FA that has strange categories. I suspect from features that they didn't end up having.

2021-07-18 23:32 UTC, shalkya commented
in the case of the battlecruiser, we can then remove the battleship tag i guess, no ?

2021-07-19 09:40 UTC, speed2CZ commented
I would be careful with removing it, as the AI uses it for sure, some of the missions as well, formation code surely uses it to place it correctly and maybe some more things.

2021-07-19 09:41 UTC, speed2CZ commented
Same goes for removing it from the missile ship. Adding a new tag that is not used anywhere is not useless, but removing current ones will break things @Garanas ^^

2021-07-20 15:30 UTC, Garanas commented
> Same goes for removing it from the missile ship. Adding a new tag that is not used anywhere is not useless, but removing current ones will break things @Garanas ^^

I've been asked by an AI dev to make it more distinguishable.

2021-07-20 15:32 UTC, Garanas commented
> in the case of the battlecruiser, we can then remove the battleship tag i guess, no ?

I didn't do that for the reason Speed2 writes out - for example selection mods will assume that it is a battleship of some kind.

2021-07-21 04:51 UTC, Azraeel commented
Categories are extremely valuable. These are very helpful changes ^^

2021-07-25 19:48 UTC, Uveso commented
NUKESUB in unit XSS0304 is used in formations:

`local SubNaval = [...] + (categories.NUKESUB * categories.ANTINAVY - categories.NUKE)`

So NUKESUB without NUKE inside the blueprint has a meaning here.

2021-07-26 13:52 UTC, Garanas commented
I've reverted the changes to the missile ship and battlecruiser there are bigger fish to catch then fixing the formations. I did fix the formation for the t3 seraphim non-nuke sub.

2021-08-03 07:25 UTC, speed2CZ requested changes

2021-08-03 07:25 UTC, speed2CZ commented on units/XES0307/XES0307_unit.bp
> +        'T3SUBMARINE',
XES0307 is battlecruiser, isnt it?

2021-08-03 07:25 UTC, speed2CZ commented on units/XSS0304/XSS0304_unit.bp
> -        'NUKESUB',
Maybe add T3SUBMARINE here?

2021-08-03 07:25 UTC, speed2CZ commented on lua/formations.lua
> +local SubNaval = categories.T1SUBMARINE + categories.T2SUBMARINE + categories.T3SUBMARINE +(categories.NUKESUB * categories.ANTINAVY - categories.NUKE)
This looks like it should be all subs - nuke subs right? since on line 449 there's NukeSubNaval
If there is new T3SUBMARINE category, then you should be able to simply substract NUKESUB from it.

2021-08-18 20:32 UTC, Dragun123 commented on lua/formations.lua
> +local SubNaval = categories.T1SUBMARINE + categories.T2SUBMARINE + categories.T3SUBMARINE +(categories.NUKESUB * categories.ANTINAVY - categories.NUKE)
If we are changing formations.lua for the land code where the deceiver is listed can we add/change to stealthfield instead?

2021-12-10 09:34 UTC, Garanas commented
Closing this PR - there are discussions among the AI developers to do a better category overhaul.

2021-12-10 09:34 UTC, closed without merging