Reduce the Agro range of Snoop & Spirit
FAForever/fa pull request #3328
Opened 2021-08-02 14:33 UTC by Tagada14

Remove the GuardScanRadius to prevent the scouts from agro'ing onto units and buildings from very far away, now they will trigger based on their weapon's maxRadius which is still much larger then their tank counterparts which should prevent them from suiciding too often when attack moved while removing the great annoyance of your scouts getting stuck if they are attack moved or assisted.

2021-08-03 07:15 UTC, speed2CZ requested changes

2021-08-03 07:15 UTC, speed2CZ commented on units/UAL0101/UAL0101_unit.bp
>      AI = {
You should remove the whole AI table if it has no entry

2021-08-04 22:33 UTC, speed2CZ approved these changes

2021-08-22 13:43 UTC, Tagada14 commented
Needs more testing and adjustment to find sweet balance between scouts suiciding and agro'ing on random stuff when they shouldn't.

2021-08-24 17:58 UTC, Tagada14 commented
UEF and Cybran :
Weapon range -> 26
GuardScanRadius -> 26
They shouldn't suicide into T1 tanks that are not Aurora
Aeon :
Weapon Range ->33
Guard Scan Radius -> 33
The Spirit shouldn't suicide into any T1 tanks including Aurora (Sometimes it depends on the refresh rate of the radar but I didn't want to increase it's weapon range too much)
Selen :
Adjusted the GuardScanRadius -> 26 same as UEF & Cybran for similar behaviour.
Selen will suicide into all T1 tanks because it's weapon range is only 18 (you need 25 at least) and because of gameplay reasons it can't be adjusted.
Doubled Aeon, UEF, Cybran Break Speed so they stop a bit faster and you can shave of 1 range from their weapon + Guard Scan Radius for better behaviour.

2021-08-28 10:29 UTC, merged