Strategic bombers rework
FAForever/fa pull request #3342
Opened 2021-08-11 13:22 UTC by Tagada14

Increase the mass killed required for a vet from 1.25x mass cost -> 2x mass cost (4.2k mass)  for all Strategic Bombers

All strats: 
Reduce the GuardScanRadius and MaxRadius to 65 (radar range), this reduces the trigger range for the strats which should limit the frustration of bombers randomly triggering on units far far away.

Cybran Strat :
AoE Radius 7 -> 6.5
EMaintananceCost 60 -> 150

UEF Strat :
Damage 3000 -> 3100
AoE Radius 6 -> 5.5

Sera Strat
Damage 3250 -> 3000
AoE Radius 5 -> 6

Aeon Strat
Damage 3450 -> 3000
AoE Radius 4 -> 5.25
Added 3s stun to its bomb
Added a Chrono-like effect to the Aeon Bomb
Note: The Stun radius is set to 5.80 which is the closest approximation I could get after many tests since before even with the same value as the weapon AoE it had a lot less range allowing the bomb to damage units without stunning them. With a 5.80 range, it's both possible to stun without damaging and damage without stunning but in 95%+ of cases, the bomb should both stun and damage the target.

To do :
Edit the emitter effects to better reflect the new AoE ranges. - Not needed, it's pretty close already
Add a Chrono-like effect to the Aeon Bomb. - Done

2021-08-11 14:28 UTC, speed2CZ requested changes

2021-08-11 14:28 UTC, speed2CZ commented on units/URA0304/URA0304_Script.lua
> +        Turns Stealth off when unit is built
This should be a comment

2021-08-11 14:28 UTC, speed2CZ commented on units/URA0304/URA0304_Script.lua
> +
No need for extra line here

2021-08-12 11:00 UTC, Tagada14 commented on units/URA0304/URA0304_Script.lua
> +        Turns Stealth off when unit is built
Fixed.

2021-08-12 11:00 UTC, Tagada14 commented on units/URA0304/URA0304_Script.lua
> +
Fixed

2021-08-12 11:25 UTC, speed2CZ approved these changes

2021-10-25 01:47 UTC, merged