Optimizing AIUtils
FAForever/fa pull request #3375
Opened 2021-08-24 15:10 UTC by Azraeel

This branch is for bugfixes, general improvements, and new features. If your change is designed to alter balance, please make 
sure your changes are rebased onto [development/balance] (https://github.com/FAForever/fa/tree/development/balance), and target that branch with your PR.

2021-08-25 06:37 UTC, Garanas requested changes
Good work overall!

Note that removing a function is dangerous - as maybe it is not being used in the code bases that are available to you.

I think caching the markers in a local cache (similar to the PR I linked you) is better in general. It makes it more clear that this is intended for AI use. 

Regardless, great work and keep it up.

edit: and please keep the logs in as comments, it makes it easier to test for me (and Uveso).

2021-08-25 06:37 UTC, Garanas commented on lua/AI/aiutilities.lua
> +    if ScenarioInfo.Env.Scenario.MasterChain[markerType] then
This isn't completely error proof. Imagine playing on the crazy rush map where new extractors are introduced over time.

In another branch I solved it like this, see also ScenarioUtils and the history of the branch.
 - https://github.com/Garanas/fa/commits/marker-refactor

You can then hook the global function that creates deposits to add to the correct cache type when it is called to create a certain resource.

2021-08-25 06:37 UTC, Garanas commented on lua/AI/aiutilities.lua
> +        local markers = Scenario.MasterChain._MASTERCHAIN_.Markers
Best to cache this in an up value to prevent all the table operations.

2021-08-25 06:37 UTC, Garanas commented on lua/AI/aiutilities.lua
> +        counter = counter + 1
Better to use 'next' over 'counter' idea - add one after you inserted the value. The reason is that there is now a direct dependency of the table operation over the counter, e.g., the table operation can not be queued in the CPU until the counter has gone through the entire pipeline. See also:
 - http://www.edwardbosworth.com/CPSC5155/PH4/Ch04/Ch04_Piplelining.pdf

And, as practical proof:
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/benchmarking/benchmarks/table-insert.lua#L8

Where the alternative version is still 20% - 30% faster!

2021-08-25 06:37 UTC, Garanas commented on lua/AI/aiutilities.lua
> +        if not TableEmpty(data.Units) then
Best not to use table.empty or table.getn at all when you just want to know if it is empty, see also this benchmark:
 - https://gitlab.com/supreme-commander-forged-alliance/other/profiler/-/blob/main/mods/profiler/modules/benchmarking/benchmarks/table-empty.lua#L8

Just use if table[1] then ... .

2021-08-25 06:44 UTC, Garanas requested changes
I'm not sure how often this function is called - but even if it is only a few times a seconds, best to refactor it to use a proper sorting algorithm.

2021-08-25 06:44 UTC, Garanas commented on lua/AI/aiutilities.lua
> +    for i = 1, TableGetn(points) do
This function is performing bubble sort. That has an O(n^2) complexity while sorting can be solved in O(n) for integral numbers and O(n*lg2(n)) for real numbers.

2021-08-25 06:45 UTC, Garanas commented on lua/AI/aiutilities.lua
> +    for i = 1, TableGetn(points) do
(couldn't add a comment where you didn't make a change)

2021-08-25 07:16 UTC, KionX commented on lua/AI/aiutilities.lua
> +        if not TableEmpty(data.Units) then
This is madness.

2021-08-25 13:33 UTC, Garanas commented on lua/AI/aiutilities.lua
> +        if not TableEmpty(data.Units) then
You're right - and in this case they are.

2022-02-06 21:32 UTC, Garanas commented
After discussing it with Azreal, I am closing this pull request due to it being aged. It can be re-opened in the future.

2022-02-06 21:32 UTC, closed without merging