Check for any pre-defined game options on the command line
FAForever/fa pull request #3385
Opened 2021-08-28 04:33 UTC by Askaholic

This is not really my ideal solution but it would work if I don't come up with anything better. With these changes you can set the fullshare option with the args `/Share FullShare`. 

Ideally it would work like this:
`/GameOption Share FullShare /GameOption Victory Demoralization /GameOption ...`
But that might be hard / impossible to implement given the way `GetCommandLineArg` works

2021-08-28 05:38 UTC, Garanas commented
I would suggest using key-value pairs as arguments. As an example: `/gameoptions share:fullshare victory:demoralization`.

The function `GetCommandLineArg` returns the number of parameters of an argument until it runs out of parameters, then it returns false. You can write a loop that stops when it hits false, uses the previous result and returns all the parameters (key-value pairs). A bit of parsing needs to happen to get the values. This would make it quite flexible, as it will even allow you to set options of mods, maps and other random things the server deems important to let the game now in the future. 

The map options are added right before launch, see also https://github.com/FAForever/fa/pull/3138 .

2021-08-28 17:45 UTC, BlackYps commented
I don't understand what we would input as num in `GetCommandLineArg(arg, num)`. I found no definition, probably because it is an engine function. It seems that num specifies how many parameters it reads and returns, but what do we do, if they are unknown?

2021-08-28 18:04 UTC, Garanas commented
I think this could work:

```lua
local next = 1
while GetCommandLineArg("gameoptions", next) do 
  next = next + 1
end

local args = GetCommandLineArg("gameoptions", next - 1)
```

At some point GetCommandLineArg runs out of arguments (next is too high) and then we take the previous entry. This would make it dynamic for any number of arguments and any key / value pair we wish to inject into the game options.

2021-08-28 20:06 UTC, BlackYps commented
I haven't tested this yet, but I think the idea becomes clear:
```lua
local next = 1
while GetCommandLineArg("gameoptions", next) do 
    next = next + 1
end

local args = GetCommandLineArg("gameoptions", next - 1)

for arg in args do
    local option, local value = string:match("([^:]+):([^:]+)")
    if option == nil or value == nil then
        LOG("Malformed gameoption. ignoring...")
    else
        gameInfo.GameOptions[option] = value
    end
end
```
I don't really know what string options are available with the supcom lua version.

2021-08-28 20:13 UTC, Garanas commented
Something like that would work - I'd need to check the string options myself too.

2021-09-02 19:47 UTC, Askaholic commented
It would make sense to me to put that into a helper function so it can be used elsewhere. What file would that go into?

2021-09-03 09:13 UTC, Garanas commented
I honestly don't know - anyone else has suggestions? I suspect making a new utils file for this type of thing doesn't particularly harm.

2021-09-03 20:13 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +        local option, value = string.match(arg, "([^:]+):([^:]+)")
Problem is, I don't think `string.match` exists in GPG's version of lua

2021-09-12 20:50 UTC, Askaholic commented
Now another problem we have is that if someone who doesn't have an updated client becomes the host and doesn't pass the game options to the game, then the game will be played using wrong game settings. Is there some way we can have each of the joining players verify the game options as well and refuse to launch the game if the game options don't agree to what they're expecting?

2021-09-12 20:58 UTC, 1-alex98 requested changes

2021-09-12 20:58 UTC, 1-alex98 commented on lua/ui/lobby/autolobby.lua
> +        for _, arg in args do
```suggestion
        for _, arg in nextArgs do
```

2021-09-12 22:52 UTC, BlackYps commented
I don't know if that is a good solution, but we could set the required client version to be that version, so everybody with an older client is forced to update to be able to log in.

2021-09-12 23:25 UTC, Askaholic commented
We should definitely do that too, but that’s not even going to get everyone since it won’t  hit py client users and those random people who are still on the tmm beta test client or other weird ass builds of the client. I’d rather that games for those people become completely unplayable so that they are forced to update.

2021-09-13 08:14 UTC, KionX commented
_I’d rather that games for those people become completely unplayable so that they are forced to update._
Pass the client version to the game and check it.
Or compare the settings of the players:
https://github.com/FAForever/fa/blob/7542596ea1c16be28615fdc40cc9bf9c8bb5481a/lua/ui/lobby/autolobby.lua#L269

2021-09-13 11:30 UTC, BlackYps commented
I tested this some more toady and the code works as expected. I.e. gameoptions from the db get applied, a ladder queue without any custom options launches with default option, and old that don't relay the options still make the game launch with default options if they are the host.
The tests were overshadowed by a faction selection bug, but that is because the client on the develop branch interprets the server commands wrong and that needs to be fixed either in the client or the server.

2021-09-13 11:33 UTC, BlackYps commented
Regarding the client version check: I'd rather have the game compare the player settings than the client version. The settings are the actual important part that needs to match and later we could have different client versions that all support relaying the options correctly.

2021-09-13 15:10 UTC, Askaholic commented
@KionX thanks, I think I mostly want to compare the game options so I guess I’d do that here:

https://github.com/FAForever/fa/blob/7542596ea1c16be28615fdc40cc9bf9c8bb5481a/lua/ui/lobby/autolobby.lua#L284

2021-09-24 03:39 UTC, Askaholic commented on lua/system/utils.lua
> +    string.gsub(str, pattern, function(c) fields[table.getn(fields)+1] = c end)
Need to check if this change is actually needed, because I'm pretty sure its not.

2021-09-24 18:03 UTC, Garanas commented
Should this be included in the hotfix too?

2021-09-24 23:40 UTC, Askaholic commented
Needs to be tested first, but once it’s ready it can go out whenever.

2021-09-25 22:54 UTC, BlackYps commented on lua/system/utils.lua
> +    string.gsub(str, pattern, function(c) fields[table.getn(fields)+1] = c end)
Testing showed that this is not needed.

2021-09-26 01:23 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +function GetCommandLineArgTable(arg)
Should this move to utils?

2021-09-26 02:31 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +        SetDialog(Group(parent, "controlGroup"), Strings.LaunchRejected, "<LOC _Exit>", CleanupAndExit)
The UI doesn't seem to come up here. It just spams 'LazyVar' errors in the log

2021-09-26 03:59 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +    SetDialog(parent, "<LOC lobui_0201>Setting up automatch...", "<LOC _Cancel>", ExitApplication)
What are the implications of attaching stuff to the parent directly instead of using this `controlGroup`? As far as I can see the result looks to be the same, however because the code in `InitLobbyComm` didn't call the LayoutHelpers as was done here, it was throwing a bunch of errors that prevented the dialog from being rendered properly. Instead only the message text would be added at the top right of the screen.

2021-09-26 06:33 UTC, Garanas commented on lua/ui/lobby/autolobby.lua
> +    SetDialog(parent, "<LOC lobui_0201>Setting up automatch...", "<LOC _Cancel>", ExitApplication)
All UI elements need to have certain values set or it doesn't know where to render it. For example: you can set Left, Top, Width and Height. If you'd skip Top in that list then it'd try to determine the height using Bottom, which isn't defined, then it tries with Top, which isn't defined - etc. That is the cyclic dependency warning - and it is annoying. This is most relevant for images - text appears to allows spawn in the top left (right?) of the screen.

2021-09-26 06:33 UTC, Garanas commented on lua/ui/lobby/autolobby.lua
> +function GetCommandLineArgTable(arg)
That sounds good, if you do so make sure to make the split value (':') a parameter of the function.

2021-09-26 06:57 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +    SetDialog(parent, "<LOC lobui_0201>Setting up automatch...", "<LOC _Cancel>", ExitApplication)
So what does the `controlGroup` do?

2021-09-26 07:01 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +function GetCommandLineArgTable(arg)
I kindof intentionally made it not a parameter so that all usages of it would be consistent. It doesn't sound like a great idea to me to use i.e. `key:value` for `/gameoptions` but then use `key|value` for `/somethingelse`. That's just going to be confusing and annoying to deal with in the client.

2021-09-26 09:12 UTC, Garanas commented on lua/ui/lobby/autolobby.lua
> +    SetDialog(parent, "<LOC lobui_0201>Setting up automatch...", "<LOC _Cancel>", ExitApplication)
In this case not much - it is just a container of UI elements such that any UI element attached to it receive the same signals are the control group does. As an example: if you destroy the controlGroup then all children are destroyed too. Or, if you hide / show the controlGroup then all children are hidden / shown too.

2021-09-26 09:14 UTC, Garanas commented on lua/ui/lobby/autolobby.lua
> +    SetDialog(parent, "<LOC lobui_0201>Setting up automatch...", "<LOC _Cancel>", ExitApplication)
A more practical example is [this](https://github.com/FAForever/fa/pull/3351/files#diff-d26022466a15cb8b0e34ecd6f22bf7902fb8050ee17bfedae18ebc206ad422bdR14) or [this](https://github.com/FAForever/fa/pull/3351/files#diff-45e96a5a8a17a1e521d6f8f75df6ca5e26b25957347230680d3f57f7174a5327R28), where we hide / show the entire UI element (button / tab bar) and all its sub elements.

2021-09-26 21:55 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +        SetDialog(parent, Strings.Ejected, "<LOC _OK>", CleanupAndExit)
Also just want to make a note of this since it's not obvious from the git diff. I added the "OK" button here since all of the other dialogs had it.

2021-09-26 21:57 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +                hostOptions = table.copy(data.GameInfo.GameOptions)
Need to make this local... Oops, python habits :P

2021-09-26 22:00 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +    for name, value in utils.GetCommandLineArgTable("/gameoptions") do
Have not tested this yet since refactoring GetCommandLineArgTable to utils

2021-09-26 22:01 UTC, Askaholic commented on lua/ui/lobby/autolobby.lua
> +        SetDialog(Group(parent, "controlGroup"), Strings.LaunchRejected, "<LOC _Exit>", CleanupAndExit)
This was happening because the control group didn't have a size and location set.

2021-10-03 10:47 UTC, Garanas requested changes
Overall I think the PR is good.

However, due to the nature autolobby.lua, we'll likely not touch them again for a long time. And by then, new people may be looking at these files and we may not be available anymore to help them out. Therefore I suggest adding comments to autolobby.lua:
 - [x] Add a description to each function, describing its intent and the parameters.
 - [ ] Add a general description to this file as to how the client and the server communicate with the game in general. This doesn't have to be extensive: the aim is to give future maintainers a direction to look into to understand the context of this file. As an example: how are the parameters chosen, if we'd need to edit that where do we do that?

Last but not least: is using the word 'client' in one of the error messages ambiguous? I am afraid people may interpret as their game not being up to date, instead of the Downlord FAF client.

2021-10-04 09:33 UTC, merged