Mod options
FAForever/fa pull request #3654
Opened 2022-01-29 00:06 UTC by Emperor-Penguin1

Added Mod Options section/functionality to lobby options list
Created ImportModOptions()
Changed ImportModAIOptions() to only add AI options from mods that are enabled
Created IsModEnabled(mod)
Created 'Mod Options' loc in US/RU/CN

2022-01-29 00:11 UTC, Sheikah45 commented
Note this is the same as https://github.com/FAForever/fa/pull/3144 so only one should be merged at the end of the day

2022-01-29 01:08 UTC, Emperor-Penguin1 commented
> Note this is the same as #3144 so only one should be merged at the end of the day

#3144 is more ambitious, but it's also not finished despite being around for about 1.5 years, and it doesn't seem like it will be finished soon (if ever) based on its rate of progress for most of that time... #3654 is already functional and ready to merge if no one has issues with it.  So, I think it would make sense to merge #3654, and if #3144 is ever finished, it could potentially replace or add to the functionality provided by #3654.

2022-01-29 11:13 UTC, Garanas commented
#3144 branched out a bit too much. Some of its functionality is already implemented by other PRs. I'll review this one tomorrow.

2022-01-30 13:18 UTC, Emperor-Penguin1 commented
Here is a example mod that demonstrates using mod options with this pr.
[Example Mod.zip](https://github.com/FAForever/fa/files/7965959/Example.Mod.zip)

2022-01-30 14:42 UTC, Garanas requested changes
Request for change: it is important that the available options get refreshed when you select / deselect an option from the map selection window. There are callback functions for this.

With regard to the map selection dialogue: 
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/ui/dialogs/mapselect.lua#L707

With regard to the lobby: use the callback `OnModsChanged` in `lua/lobby.lua`:
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/ui/lobby/lobby.lua#L2411
 
Quality of life feature: I think it would be nice if you could see the origin of some options. As an example, that you can see option X is from mod Y. Similar to #3144 .

2022-01-30 14:42 UTC, Garanas commented on lua/ui/lobby/lobby.lua
> +    local simMods = import('/lua/mods.lua').AllMods()
I don't think we should support options for UI mods, if we do then we need some more extensive checks. We can start by just allowing sim mods. You can use `GetSelectedSimMods()` from `/lua/mods.lua`:
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/MODS.LUA#L249
 
It makes a table of all enabled sim mods. Best to re-use code for a specific purpose, it will simplify your loop.

2022-01-30 14:42 UTC, Garanas commented on lua/ui/lobby/lobby.lua
> +            OptionData = import(ModData.location..'/options.lua').options
To remain consistent it is better to call the file `mod_options.lua`, that is consistent with `mod_info.lua` and `mod_icons.lua`.

2022-02-01 21:24 UTC, Emperor-Penguin1 commented on lua/ui/lobby/lobby.lua
> +            OptionData = import(ModData.location..'/options.lua').options
done

2022-02-01 21:27 UTC, Emperor-Penguin1 commented on lua/ui/lobby/lobby.lua
> +    local simMods = import('/lua/mods.lua').AllMods()
I changed it to refresh as well as to only show options for sim mods

2022-02-01 21:31 UTC, Emperor-Penguin1 commented on lua/ui/lobby/lobby.lua
> +    local simMods = import('/lua/mods.lua').AllMods()
Regarding the potential QoL feature; I'm not opposed to it, but I don't think it's necessary for this pr, and it could be accomplished by others in the future if they desire it.

2022-02-01 21:37 UTC, Emperor-Penguin1 commented
Here is a example mod that demonstrates using mod options with this pr
[Example Mod.zip](https://github.com/FAForever/fa/files/7982076/Example.Mod.zip)
.

2022-02-01 21:45 UTC, Sheikah45 commented on lua/ui/lobby/lobby.lua
> +            end
Is it intended to make it impossible for a mod to have both AI lobby options and mod_options?

2022-02-02 03:06 UTC, Emperor-Penguin1 commented on lua/ui/lobby/lobby.lua
> +            end
I hadn't expected desire for both in the same mod, but that's a good point, as some people may do try to do that anyway even though it's unnecessary.  So, I'll make it possible to have both.

2022-02-02 08:30 UTC, speed2CZ commented on lua/ui/dialogs/mapselect.lua
> +        OptionSource[i + 4] = {title = mod[2], options = mod[1]}
Why dont you use the table constructor for the for the first 4 and then table.insert for the mod options?

2022-02-02 13:53 UTC, Emperor-Penguin1 commented on lua/ui/dialogs/mapselect.lua
> +        OptionSource[i + 4] = {title = mod[2], options = mod[1]}
I was trying to stick closer to the old formatting which didn't do it that way, but I'll change it to that.

2022-02-02 16:52 UTC, Garanas commented
This is looking good - I'll review it again on Friday.

2022-02-02 16:53 UTC, Garanas commented on lua/ui/lobby/lobby.lua
> +AIOpts = import('/lua/ui/lobby/lobbyOptions.lua').AIOpts
What was the reason for not having these as locals?

2022-02-02 19:03 UTC, Emperor-Penguin1 commented on lua/ui/lobby/lobby.lua
> +AIOpts = import('/lua/ui/lobby/lobbyOptions.lua').AIOpts
They'd normally be globals in lobbyOptions.lua anyway, and there was a combination of errors, missing functionality, and refresh issues (ie: mods not being removed from lobby options list when the mod is deselected in lobby) with different attempts to keep them local in lobby.lua.  I tried a number of workarounds, but all of them had issue(s).  This way works and I'm satisfied with it.

2022-02-06 10:03 UTC, Garanas commented
When a user has a faulty mod enabled it prevents the entire lobby from functioning:

```yaml
WARNING: SCR_LuaDoFileConcat: Loading "c:\programdata\faforever\user\my games\gas powered games\supreme commander forged alliance\mods\battle-royale\lua\ai\lobbyoptions\lobbyoptions.lua" failed: ... forged alliance\mods\battle-royale\lua\ai\lobbyoptions\lobbyoptions.lua(9): `}' expected (to close `{' at line 4) near `values'
WARNING: ...ocuments\supreme commander\fa\lua\ui\lobby\lobby.lua(117): access to nonexistent global variable "AIOpts"
WARNING: stack traceback:
WARNING:         [C]: in function `error'
WARNING:         ...alliance\gamedata\mohodata.scd\lua\system\config.lua(53): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:52>
WARNING:         ...ocuments\supreme commander\fa\lua\ui\lobby\lobby.lua(117): in function `ImportModOptions'
WARNING:         ...ocuments\supreme commander\fa\lua\ui\lobby\lobby.lua(133): in main chunk
WARNING:         [C]: in function `doscript'
WARNING:         [C]: ?
WARNING:         ...documents\supreme commander\fa\lua\system\import.lua(87): in function `import'
WARNING:         ...documents\supreme commander\fa\lua\system\import.lua(72): in function `import'
WARNING:         ...documents\supreme commander\fa\lua\ui\menus\main.lua(835): in function `StartLobby'
WARNING:         ...documents\supreme commander\fa\lua\ui\menus\main.lua(840): in function <...documents\supreme commander\fa\lua\ui\menus\main.lua:832>
WARNING:         ...documents\supreme commander\fa\lua\ui\menus\main.lua(749): in function <...documents\supreme commander\fa\lua\ui\menus\main.lua:741>
WARNING:         ...documents\supreme commander\fa\lua\ui\menus\main.lua(310): in function <...documents\supreme commander\fa\lua\ui\menus\main.lua:295>
WARNING: Error running OnFrame script in CScriptObject at 101a92c0: ...documents\supreme commander\fa\lua\system\import.lua(72): Error importing '/lua/ui/lobby/lobby.lua'
         stack traceback:
         	[C]: in function `error'
         	...documents\supreme commander\fa\lua\system\import.lua(92): in function `import'
         	...documents\supreme commander\fa\lua\system\import.lua(72): in function `import'
         	...documents\supreme commander\fa\lua\ui\menus\main.lua(835): in function `StartLobby'
         	...documents\supreme commander\fa\lua\ui\menus\main.lua(840): in function <...documents\supreme commander\fa\lua\ui\menus\main.lua:832>
         	...documents\supreme commander\fa\lua\ui\menus\main.lua(749): in function <...documents\supreme commander\fa\lua\ui\menus\main.lua:741>
         	...documents\supreme commander\fa\lua\ui\menus\main.lua(310): in function <...documents\supreme commander\fa\lua\ui\menus\main.lua:295>
```

Best to use `pcall` when you load in these options and then inform the user using 'WARN" instead of 'error'. For more information about pcall:
 - http://www.lua.org/pil/8.4.html

When you change an option in the map select dialogue you need to invoke CalcVisible (the function that updates the list) again to prevent this:

![image](https://user-images.githubusercontent.com/15778155/152675875-fda5b7fd-6a3a-4d8c-8101-08dd2f79dc5f.png)

2022-02-06 10:13 UTC, Garanas requested changes
It is starting to look good - just a few more hiccups.

2022-02-06 10:13 UTC, Garanas commented on lua/system/Blueprints.lua
> +local PrefsPreGameData = false
Best to call this `PreGameData` to match it with the lobby. Also add a comment so that people can read up about how this value is populated.

2022-02-06 10:13 UTC, Garanas commented on lua/ui/lobby/lobby.lua
> +local function AddModOptions(OptionData, modName)
Add more informative comments about the arguments. As an example:
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/ui/game/commandmode.lua#L396
 
In particular, because Lua has no static typing system it is important to describe the parameters and what a developer can expect from them.

2022-02-06 10:13 UTC, Garanas commented on lua/ui/lobby/lobby.lua
> +function IsEnabledSimMod(mod)
Add more informative comments.

2022-02-06 10:13 UTC, Garanas commented on lua/system/Blueprints.lua
> +local OptionChoices
Same here - add a comment so that people understand how this value is populated. An example may be useful here too.

2022-02-06 10:13 UTC, Garanas commented on lua/system/Blueprints.lua
> +LoadPrefsData()
Refactor this to call the function in question immediately after it is defined. As an example, line 93. No need to hide it down here.

2022-02-10 15:31 UTC, Emperor-Penguin1 commented on lua/system/Blueprints.lua
> +local PrefsPreGameData = false
Okay

2022-02-10 15:57 UTC, Emperor-Penguin1 commented on lua/ui/lobby/lobby.lua
> +function IsEnabledSimMod(mod)
Okay

2022-02-10 16:00 UTC, Emperor-Penguin1 commented on lua/ui/lobby/lobby.lua
> +local function AddModOptions(OptionData, modName)
Okay

2022-02-10 16:01 UTC, Emperor-Penguin1 commented on lua/system/Blueprints.lua
> +local OptionChoices
Okay

2022-02-10 16:33 UTC, Emperor-Penguin1 commented on lua/system/Blueprints.lua
> +LoadPrefsData()
Okay

2022-02-12 17:27 UTC, SomeDev-v0-9 commented on loc/RU/strings_db.lua
> +uilobby_0004="настройки мода"
Should it be in lower case, or is it a typo?

2022-02-12 19:59 UTC, Emperor-Penguin1 commented on loc/RU/strings_db.lua
> +uilobby_0004="настройки мода"
It was a typo.

2023-02-28 20:00 UTC, Hdt80bro commented
@Garanas if we're not going to redo the lobby soon, is this one good to go?

2023-04-12 19:30 UTC, closed without merging