Refactor various utility functions
FAForever/fa pull request #3678
Opened 2022-02-23 15:45 UTC by Tagada14

Refactor the following list of getters / setters:

 SetCanTakeDamage
 CheckCanTakeDamage
 CheckCanBeKilled
 SetCanBeKilled
 SetDead
 IsDead
 GetCachePosition

Add a deprecation warning for all of them.

Move all deprecated functions to the bottom of the unit class. Include other deprecated functions that were not moved there before.

Add a deprecated functions header (a comment that says all functions below it are deprecated).
Replace all known references to the list of getters/setters with their actual value instead.
(Yes, I know I should have used multiple commits for this :/ )

2022-02-24 10:24 UTC, Garanas commented on lua/proptree.lua
> -		local pos = self:GetCachePosition()
The pull request was limited to units. Props do use the cached position as one would expect:
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Prop.lua#L89
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Prop.lua#L50
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Prop.lua#L43

2022-02-24 10:25 UTC, Garanas commented on lua/proptree.lua
> -		local pos = self:GetCachePosition()
You could rewrite it to `self.CachePosition` however, but that is for a future pull request.

2022-02-25 11:07 UTC, Tagada14 commented on lua/proptree.lua
> -		local pos = self:GetCachePosition()
Reverted changes to this file

2022-02-27 09:27 UTC, Garanas requested changes
Running a test game with AIs reveals:

```
WARNING: Formation script GuardFormation threw an error:
         ...ip\documents\supreme commander\fa\lua\formations.lua(838): table index is nil
         stack traceback:
         	...ip\documents\supreme commander\fa\lua\formations.lua(838): in function <...ip\documents\supreme commander\fa\lua\formations.lua:823>
```

The game makes no distinction between dummy and regular units. A lot of the 'find units' functionality excludes dummy units. But the formations still take them into account. This means that the dummy unit needs the information used by the formation code cached too.

Besides that error, one game of two AIs appears to run fine. Code inspection also doesn't reveal any issues. I'll be running a few more games over the upcoming days to confirm it. Good job.

2022-02-27 09:27 UTC, Garanas commented on lua/aeonweapons.lua
> +            CreateEmitterAtEntity(target, target.Army, v):ScaleEmitter(0.25 * target.FootPrintSize/0.5)
interesting formula: `0.25 * X / 0.5` -> `0.125 * X`

2022-02-27 09:27 UTC, Garanas commented on lua/defaultunits.lua
> +        local x, y, z = unpack(self:GetPosition())
Better to use GetPositionXYZ here to prevent a table allocation and prevent unpacking the table

2022-02-27 09:27 UTC, Garanas commented on lua/sim/Unit.lua
> +        self.FootPrintSize = math.max(bp.Footprint.SizeX, bp.Footprint.SizeZ)
With regards to the general comment of the review, this value needs to be set on Dummy units too

2022-02-27 09:27 UTC, Garanas commented on lua/sim/Unit.lua
> +        local sx, sy, sz = self.Size.SizeX, self.Size.SizeY, self.Size.SizeZ
Refactor this further to:

```lua
local size = self.Size
local sx, sy, sz = size.SizeX, size.SizeY, size.SizeZ
```

Looks a lot less convoluted. Same for other places where this pattern shows up.

2022-02-27 09:27 UTC, Garanas commented on lua/sim/Unit.lua
> +-- upvalued math functions for performance
Heh

2022-02-27 09:27 UTC, Garanas commented on lua/ui/game/construction.lua
> +        if not frontOfQueue or frontOfQueue.Dead then
This is UI code: that has a different Lua state. Better to use `IsDead()` , as any value set to the table on the sim side is not synced.

2022-02-27 09:27 UTC, Garanas commented on lua/ui/game/unittext.lua
> +#* Copyright � 2008 Gas Powered Games, Inc.  All rights reserved.
Glad I am not the only one with these issues.

2022-02-27 09:27 UTC, Garanas commented on lua/ui/game/rallypoint.lua
> +        if not mesh.unit.Dead then
As per the previous comment, UI code - better not to change it.

2022-02-27 09:27 UTC, Garanas commented on lua/ui/game/unittext.lua
> +            if self.userEntity and not self.userEntity.Dead then
As per the previous comment, UI code - better not to change it.

2022-02-27 09:27 UTC, Garanas commented on testmaps/PerfTestOriginal/perftest_script.lua
> +-- Copyright � 2006 Gas Powered Games, Inc.  All rights reserved.
Glad I am not the only one with these issues, x2. Revert it back to the copyright symbol

2022-02-27 09:27 UTC, Garanas commented on units/UAA0310/UAA0310_script.lua
> +        explosion.CreateDebrisProjectiles(self, explosion.GetAverageBoundingXYZRadius(self), {self.Size.SizeX, self.Size.SizeY, self.Size.SizeZ})
Interesting pattern, where we immediately allocate the values back into a table. It appears this is only the case for four units, and those are experimentals. Otherwise this was a nice performance target again.

2022-03-08 20:51 UTC, Garanas commented
Pull request is all good. Merging it once I've discussed with someone how to fix the conflicts with faf develop 😄 .

2022-03-11 18:30 UTC, merged