Profiler improvement
FAForever/fa pull request #3700
Opened 2022-03-13 19:06 UTC by 4z0t

Profiler UI improvement. 
_Still working on it..._

2022-03-13 23:37 UTC, HUSSAR-mtrela requested changes

2022-03-13 23:37 UTC, HUSSAR-mtrela commented on lua/ui/game/Profiler.lua
> +        end)
Moving such short code to be on a new line, goes against FA programming style where authors made an effort to keep code easier to read and shorter by not adding new lines in dynamic functions.  Please can you undo adding new lines and keep your other changes?

2022-03-13 23:42 UTC, 4z0t commented on lua/ui/game/Profiler.lua
> +        end)
I haven't completed everything yet, so yeah, i will do. Also, it does formatter, not me ☺️

2022-03-13 23:44 UTC, HUSSAR-mtrela requested changes

2022-03-13 23:44 UTC, HUSSAR-mtrela commented on lua/ui/game/Profiler.lua
> +ProfilerWindow = Class(Window.Window) {
please move ProfilerWindow class to a new file, e.g. ProfilerWindow.lua

2022-03-13 23:44 UTC, HUSSAR-mtrela commented on lua/ui/game/ProfilerElements.lua
> +ScrollArea = Class(Group) {
the ScrollArea class is not used anywhere in this PR. Did you forget to use it or is still work-in-progress? If you want to keep it then you should move it to a new file under:
/lua/ui/controls/ScrollArea.lua

2022-03-14 08:28 UTC, Garanas commented on lua/ui/game/Profiler.lua
> +ProfilerWindow = Class(Window.Window) {
Please to keep the `Profiler` keyword somewhere in there, it makes it easier to find all the profiler related files.

@HUSSAR-mtrela I've messaged you on Zulip - I don't know how to send messages on Github 😄

2022-03-15 21:15 UTC, Garanas commented
10/10, will merge twice

2022-03-16 13:39 UTC, Garanas commented
@4z0t Do you intend to make other changes? Otherwise I'll review the pull request and try to merge later tonight or tomorrow.

2022-03-16 14:43 UTC, 4z0t commented
@Garanas I would like to do other tabs at least define methods for switching between them.

2022-03-16 14:52 UTC, Garanas commented
I'll finalize the information to display for the benchmarks tab and the toggles for the options tab.

2022-03-16 19:56 UTC, merged