UI refactor
FAForever/fa pull request #3707
Opened 2022-03-17 16:11 UTC by 4z0t

_Something's wrong i can feel it..._

2022-03-24 01:18 UTC, HUSSAR-mtrela requested changes

2022-03-24 01:18 UTC, HUSSAR-mtrela commented on lua/ui/maputil.lua
> +    return not not scenario.Configurations.standard.teams[1].armies
this should be simplified to:
```return scenario.Configurations.standard.teams[1].armies```

2022-03-24 01:18 UTC, HUSSAR-mtrela commented on lua/ui/notify/customiser.lua
> +    txt = txt or '?'
good job!

2022-03-24 01:18 UTC, HUSSAR-mtrela commented on lua/ui/uiutil.lua
> +            local worldCover = worldCovers[index]
defining `worldCover` locally on line 982 and again `worldCover` on line 1001 might lead to bugs if someone refactors these code or try to understand it. I suggest to renaming one of these local variables:
```local worldCover = worldCovers[index]```
to something like this:
```local frameCover = worldCovers[index]```

2022-03-24 05:36 UTC, 4z0t commented on lua/ui/maputil.lua
> +    return not not scenario.Configurations.standard.teams[1].armies
It must return bool, so, I cheated 😁

2022-03-24 07:20 UTC, Garanas commented on lua/ui/uiutil.lua
> +            local worldCover = worldCovers[index]
I agree.

2022-03-24 16:59 UTC, Garanas commented
I'd like to note that I am in favor of several smaller pull requests instead of one larger pull request.

2022-03-24 17:49 UTC, 4z0t commented
I don't think it's gonna be that large, currently just removing strange and useless stuff and changing code for better readability

2022-03-28 11:51 UTC, ChrisKitching commented on lua/ui/maputil.lua
> +    return not not scenario.Configurations.standard.teams[1].armies
Maybe consider a function like `Bool()` to perform the conversion, then? Javascript-style implicit conversion to boolean may cause engineer killing sprees.

2022-03-28 11:51 UTC, ChrisKitching commented on lua/ui/menus/eula.lua
> +--* Copyright � 2005 Gas Powered Games, Inc.  All rights reserved.
You saved this file with non-UTF-8 encoding, breaking this character. Reconfigure your editor appropriately ;)

2022-03-28 12:10 UTC, 4z0t commented on lua/ui/menus/eula.lua
> +--* Copyright � 2005 Gas Powered Games, Inc.  All rights reserved.
it is utf-8
![image](https://user-images.githubusercontent.com/84857900/160394963-ffb609e4-5fd0-4831-8923-4a6f58e22a0a.png)

2022-03-28 13:04 UTC, 4z0t commented
I also know why would chat crash if you spamed messages a  lot

2022-03-28 13:40 UTC, Rackover commented
> I also know why would chat crash if you spamed messages a lot.
Because Mr [@Rackover](https://github.com/Rackover) decided to create for each message received a control...

it's Ms 😂   and do know that I receive this kind of ping by mail directly, so editing my name out doesn't change much...
but yes, i believe this is & was my only PR that ever dealt with Lua code , and supcom's Lua API is not one of my strong suits   Feel free to refactor and shuffle around in the way you feel is fit! ❤️

2022-03-28 13:50 UTC, 4z0t commented
Yeah, I think I will make new pr for this one, because it requires significant changes

2022-03-28 14:11 UTC, ChrisKitching commented on lua/ui/menus/eula.lua
> +--* Copyright � 2005 Gas Powered Games, Inc.  All rights reserved.
Huh, so why'd this break? :D

2022-03-30 20:33 UTC, 4z0t commented
Gonna separate on smaller PRs to prevent overgrowing

2022-03-30 20:33 UTC, closed without merging

2022-03-31 07:47 UTC, Garanas commented
Sounds better 😄 .