Layouter as alternative for LayoutHelpers
FAForever/fa pull request #3835
Opened 2022-05-01 11:33 UTC by 4z0t

Examples:
![image](https://user-images.githubusercontent.com/84857900/166143928-95f8509d-6fb1-4c48-839b-7a8b2d988c3c.png)
![image](https://user-images.githubusercontent.com/84857900/166143987-7658bbf3-f1ca-47f1-8d6c-fb34d8350840.png)

2022-05-05 07:42 UTC, Garanas commented
Could you copy / paste the code of the screenshots into your original post, instead of the screenshots?

2022-05-05 07:58 UTC, Garanas requested changes
And we should also look into generating the snippets for this builder pattern.

2022-05-05 07:58 UTC, Garanas commented on lua/maui/layouthelpers.lua
> +function LayouterMetaTable:Disable()
All these functions need a proper comment describing what it does, especially if we intend to make snippets as those are taken into account.

2022-05-05 07:58 UTC, Garanas commented on lua/maui/layouthelpers.lua
> +function LayouterMetaTable:BitmapColor(color)
These (and others) should just match the original name. As a few examples:
`LayouterMetaTable:TextColor` -> `LayouterMetaTable:SetColor`
`LayouterMetaTable:BitmapColor` -> `LayouterMetaTable:SetSolidColor`

That prevents contributors from having to learn a new syntax.

2022-05-05 07:58 UTC, Garanas commented on lua/maui/layouthelpers.lua
> +function LayouterMetaTable:NeedsFrameUpdate(state)
Do not use ambiguous names for values, I think this is a boolean. Call it a `bool` instead of `state`.

2022-05-05 07:58 UTC, Garanas commented on lua/maui/layouthelpers.lua
> +        error(":HitTest requires 1 positional argument \"state\"")
Do not use errors - use warnings. An error stops code executing, causing a gazillion lazy var errors. You can inform the user that something is wrong, and then tell them that it skipped processing the call in question.

2022-05-05 07:58 UTC, Garanas commented on lua/maui/layouthelpers.lua
> +    return self.c
It would be interesting here to see if we can add some error-managing code to detect the lazy var loops that can happen. I'm not 100% confident, but I think every control inherits from the Control class. That resets the layout here:
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/maui/control.lua#L33

It would be interesting to:
 - add an 'isDefault' flag to lazy vars, that is set to false after any Set function is called
 - Manually set the isDefault flag to true in the `ResetLayouts` function, after setting them to their default values
 - in this Get function, check whether (for example) both the left and the right definition are default. if they both are, then we are missing information. Give them a default value (left set to 0, right set to screen width - idk) and provide a warning indicating what you need to do to fix it.
 
And then for each combination of errors. The following are correct:
 - left and right defined
 - left and width defined
 - right and width defined
 - top and bottom defined
 - top and height defined
 - bottom and height defined
 
Anything else is incorrect and causes a lazy var loop.

2022-05-05 08:22 UTC, 4z0t commented
> Could you copy / paste the code of the screenshots into your original post, instead of the screenshots?
Done!

2022-05-05 08:26 UTC, Garanas commented on lua/maui/layouthelpers.lua
> +function LayouterMetaTable:BitmapColor(color)
I also think it should check if control-specific properties exist, and if it doesn't, it gives the user a friendly warning instead of crashing.

2022-05-05 08:36 UTC, 4z0t commented
@Garanas  I think it is possible, BUT:
* user can manually do a circular dependency, that is trackable by pcall, BUT
* parent control may have uncompleted layout whilest layouting child causing circular dependency
* I don't think it is worth doing this since finding circular deps is not that hard

2022-05-05 08:46 UTC, Garanas commented
> I don't think it is worth doing this since finding circular deps is not that hard

I disagree. Even with #3833 I frequently was at a loss what was causing the issue. Let alone for someone not as experienced as us that encounters a stream of errors.

Let's let it sink in a bit. Because having some more sane error messaging would help us, but also any UI modder and future contributor to understand what is going wrong.

2022-05-05 08:47 UTC, 4z0t commented on lua/maui/layouthelpers.lua
> +function LayouterMetaTable:BitmapColor(color)
> I also think it should check if control-specific properties exist, and if it doesn't, it gives the user a friendly warning instead of crashing.

I saw `IsInstance` like function, how suitable is it?

2022-05-05 08:49 UTC, Garanas commented on lua/maui/layouthelpers.lua
> +function LayouterMetaTable:BitmapColor(color)
I was more thinking in terms of:

```lua
function LayouterMetaTable:DropShadow(state)
    self.c:SetDropShadow(state)
    return self
end
```
to
```lua
function LayouterMetaTable:DropShadow(state)
    if self.c.SetDropShadow then 
        self.c:SetDropShadow(state)
    else
        WARN("UI element is likely no text and therefore you can not set a drop shadow. Skipping this instruction.)
    end
    return self
end
```

2022-05-05 13:06 UTC, 4z0t commented
excuse me where are my changes

2022-05-05 13:08 UTC, 4z0t commented on lua/maui/layouthelpers.lua
> +function LayouterMetaTable:BitmapColor(color)
> I was more thinking in terms of:
> 
> ```lua
> function LayouterMetaTable:DropShadow(state)
>     self.c:SetDropShadow(state)
>     return self
> end
> ```
> 
> to
> 
> ```lua
> function LayouterMetaTable:DropShadow(state)
>     if self.c.SetDropShadow then 
>         self.c:SetDropShadow(state)
>     else
>         WARN("UI element is likely no text and therefore you can not set a drop shadow. Skipping this instruction.)
>     end
>     return self
> end
> ```

if user does regularly it like `bitmap:c:SetDropShadow(true)` he gets error anyway, so, I dont think skipping problems is a good idea.

2022-05-06 14:02 UTC, 4z0t commented
Are you ok with this implementation of End?

2022-05-08 12:56 UTC, Garanas commented
> @Garanas also, what do you think about merging color method for both text and bitmap?

Sounds good to me.

2022-05-08 12:57 UTC, Garanas commented
> Are you ok with this implementation of End?

I'll look at it later this week - there is no rush, the release is not ready yet anyhow 😄 .

2022-05-24 20:13 UTC, Ejsstiil commented on lua/maui/layouthelpers.lua
> +    return self.c
Combinations of loop errors, nice! This should go somewhere to Dev Wiki

2022-05-25 08:44 UTC, 4z0t commented
Should I start making docs now or waiting for vs code extension?

2022-06-08 06:14 UTC, merged