Optimized weapon prioritization by re-using single table
FAForever/fa pull request #3845
Opened 2022-05-07 02:42 UTC by LilJoe7k4

For issue #3758 

Followed Approach 1 and added RecycledPriTable in the outer scope. This table is re-used and cleared each time SetWeaponPriorities() is run.

Followed the [table insertion benchmarks](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/benchmarking/benchmarks/table-insert.lua) for inserting into the priority table as well.

I ran through a few bot matches just to make sure I didn't break the game, but I'm new to Lua and FAF so I may have missed something, please let me know if you spot any issues and I'll attempt to fix them 😁

2022-05-07 08:38 UTC, Garanas commented
Great work - I'll give it a review later this weekend 😄 !

2022-05-08 10:53 UTC, Garanas requested changes
Inline the cleaning up of the recycled priority table. After that it is ready for a merge.

2022-05-08 10:53 UTC, Garanas commented on lua/sim/weapon.lua
> +local function ClearRecycledPriTable()
In this situation it is better to clear out the recycled table in-line as a function is relatively expensive in Lua. It doesn't get auto-inlined as other languages like C and C++ support. See also this benchmark:
 - https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/benchmarking/benchmarks/function-inlining.lua
 
 Where the functions have a small body, similar like yours.

2022-05-08 10:53 UTC, Garanas commented on lua/sim/weapon.lua
>                  self:SetTargetingPriorities(priorityTable)
Clear out the recycled table right after use

2022-05-08 10:53 UTC, Garanas commented on lua/sim/weapon.lua
>                  self:SetTargetingPriorities(priorityTable)
Clear out the recycled table right after use

2022-05-08 10:53 UTC, Garanas commented on lua/sim/weapon.lua
> +        ClearRecycledPriTable()
Don't forget to remove this call

2022-05-09 02:35 UTC, LilJoe7k4 commented on lua/sim/weapon.lua
> +local function ClearRecycledPriTable()
Ahh interesting good to know! I'll check out that benchmark. I've removed the function and moved everything inline.

2022-05-09 02:35 UTC, LilJoe7k4 commented
Please take another look, I've moved the function logic inline and removed it + the function call

2022-05-09 13:18 UTC, Garanas commented on lua/sim/weapon.lua
> +                for i = 1, table.getn(priorityTable) do
You know the length of the table: `count - 1`. Better to use that over re-computing the length with `table.getn`.

2022-05-09 13:18 UTC, Garanas requested changes
See the comment.

2022-05-09 21:11 UTC, LilJoe7k4 commented on lua/sim/weapon.lua
> +                for i = 1, table.getn(priorityTable) do
Whoops good call, changed that to count - 1

2022-05-10 20:12 UTC, Garanas commented
Tested with a Rhino and some t1 / t2 / t3 units. The priorities are set as usual. Great job - merging it.

2022-05-10 20:13 UTC, Garanas commented on lua/sim/weapon.lua
> -                    table.insert(priorityTable, ParseEntityCategory(v))
This is functionally different - was this an intended change?

2022-05-10 20:40 UTC, Garanas commented on lua/sim/weapon.lua
> -                    table.insert(priorityTable, ParseEntityCategory(v))
I can't seem to find a scenario where this code is being run.

2022-05-12 00:05 UTC, LilJoe7k4 commented on lua/sim/weapon.lua
> -                    table.insert(priorityTable, ParseEntityCategory(v))
Hmm no didn't intend to swap ParseEntityCategory for cachedPriorities (copy and paste error :roll_eyes:), this should have been:

`priorityTable[count] = ParseEntityCategory[v]`

I'll fix that, although it's weird that nothing seemed to break with that change, guessing that relates to not finding a scenario where this runs?

2022-05-17 15:07 UTC, merged

2022-05-17 19:54 UTC, LilJoe7k4 commented
No worries at all!

The issue was described very well, the detailed breakdown definitely made this issue super approachable. The [setup instructions](https://github.com/FAForever/fa/blob/deploy/fafdevelop/setup/setup-english.md) also made getting up and running pretty simple. So yeah I felt it was easy to pick up and go 😁