Optimize projectiles for:
FAForever/fa pull request #3880
Opened 2022-05-22 23:19 UTC by Ejsstiil

Optimize following projectiles. Unused code, added LODCutoff where applicable.
TIFMortar01
TIFNapalmCarpetBomb01
TIFNapalmCarpetBomb02
TIFSmallYieldNuclearBomb01
TIMAntiMissile01
TIMAntiTorpedo01
TIMAntiTorpedo02
TIMMissileIntercerptor01
TIMSonarBuoyCreator01
TorpedoShipAeon01
TorpedoShipTerran01
TorpedoShipTerran02
TorpedoShipTerran03
TorpedoSubTerran01

This branch is for bugfixes, general improvements, and new features. If your change is designed to alter balance, please make 
sure your changes are rebased onto [development/balance] (https://github.com/FAForever/fa/tree/development/balance), and target that branch with your PR.

2022-05-23 07:05 UTC, speed2CZ commented on projectiles/TIFMortar01/TIFMortar01_script.lua
> +TIFMortar01 = Class(import('/lua/terranprojectiles.lua').TArtilleryProjectile) {}
putting the import into the Class call makes it less readable

2022-05-23 07:06 UTC, speed2CZ requested changes

2022-05-23 07:06 UTC, speed2CZ commented on projectiles/TIFNapalmCarpetBomb01/TIFNapalmCarpetBomb01_script.lua
> +TIFNapalmCarpetBomb01 = Class(import('/lua/terranprojectiles.lua').TNapalmCarpetBombProjectile) { }
they can be used by mods, don't comment them out

2022-05-23 07:45 UTC, Garanas commented on projectiles/TIFNapalmCarpetBomb02/TIFNapalmCarpetBomb02_script.lua
> -local TNapalmHvyCarpetBombProjectile = import('/lua/terranprojectiles.lua').TNapalmHvyCarpetBombProjectile
I'll update the issue / pull request.

All locals that are removed should be placed beneath the class. That prevents them from being part of a closure (yah) while maintaining mod support.

Mod files are 'appended' to the bottom of each file. Therefore they can use the original imports.

2022-05-23 07:46 UTC, Garanas commented on projectiles/TIFNapalmCarpetBomb01/TIFNapalmCarpetBomb01_script.lua
> +TIFNapalmCarpetBomb01 = Class(import('/lua/terranprojectiles.lua').TNapalmCarpetBombProjectile) { }
I agree, the base game doesn't use all projectiles. But a mod may use it.

2022-05-23 16:17 UTC, Ejsstiil commented on projectiles/TIFNapalmCarpetBomb02/TIFNapalmCarpetBomb02_script.lua
> -local TNapalmHvyCarpetBombProjectile = import('/lua/terranprojectiles.lua').TNapalmHvyCarpetBombProjectile
Why then remove them?

2022-05-26 10:36 UTC, Garanas commented on projectiles/TIFNapalmCarpetBomb02/TIFNapalmCarpetBomb02_script.lua
> -local TNapalmHvyCarpetBombProjectile = import('/lua/terranprojectiles.lua').TNapalmHvyCarpetBombProjectile
Good point 😄

2022-05-26 10:37 UTC, Garanas commented
Made a decision, see also:

![image](https://user-images.githubusercontent.com/15778155/170471589-804cfb7c-bca6-43a8-8d03-9b9cb99c695c.png)

At no point should we remove top-file locals, we can move them to the bottom of the file however. At any point all the top-file definitions (outer scope) should remain available, as mods may depend on their existence.

2022-06-04 19:18 UTC, Garanas approved these changes
Looking good - fixed some of the comment / annotation style.

2022-06-04 19:18 UTC, merged