Auto jamming Toggle
FAForever/fa pull request #3927
Opened 2022-06-04 18:53 UTC by Spikey84

This will attempt to automatically toggle radar jamming occasionally. https://forum.faforever.com/topic/3866/jamming-ability-should-reset-when-vision-of-unit-is-lost

Very work in progress rn

2022-06-07 12:16 UTC, hahn-kev commented on lua/aibrain.lua
> +            CoroutineYield(1)
doesn't `WaitSeconds` just call `CoroutineYield` internally, so are both needed here?

2022-06-07 14:08 UTC, Garanas commented on lua/aibrain.lua
> +            CoroutineYield(1)
WaitSeconds is defined here: https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/simInit.lua#L26, which calls coroutine.yield at some point

2022-06-08 06:23 UTC, Garanas commented on lua/aibrain.lua
> +        if reconType == 'LOSNow' or econType == 'Omni' then
Typo!

2022-06-08 07:54 UTC, speed2CZ commented on lua/aibrain.lua
> +                if not jammer:BeenDestroyed() then
woudln't `jammer.Dead` do the same trick?

2022-06-08 08:16 UTC, Garanas commented on lua/aibrain.lua
> +                if not jammer:BeenDestroyed() then
No - there's a small window between a unit being destroyed and a unit being set to dead where any engine interaction can cause a crash. This was most notable when we used `unit.Dead` or the build animations in an attempt to evade an engine call, where we now often use `BeenDestroyed` instead.

2022-06-11 14:50 UTC, Garanas commented on lua/aibrain.lua
> +    AddJammer = function(self, unit)
Use `TrackJammer` instead of `AddJammer`

2022-06-11 14:51 UTC, Garanas commented on lua/aibrain.lua
> +    RemoveJammer = function(self, unit)
Similar, use `UntrackJammer`

2022-06-11 14:51 UTC, Garanas commented on lua/aibrain.lua
> +        self.jammers = { }
Entries in `self` should always be pascal case.

2022-06-11 14:53 UTC, Garanas commented on lua/aibrain.lua
> +                    RemoveJammer(jammer)
Better to untrack `OnDestroy` similar to how we start tracking during `OnCreate` of the unit itself. The if statement to check if the entity is still there is quite valid regardless.

2022-06-11 14:56 UTC, Garanas commented on lua/aibrain.lua
> +                            jammer:EnableUnitIntel('AutoToggle', 'Jammer')
As this thread needs to remain alive throughout the game, we'll need to make sure that any external call can not crash the thread. We can use `pcall` to help us do this, you can look at `ToggleEnergyExcessUnitsThread` for inspiration.

2022-06-11 14:56 UTC, Garanas commented on lua/aibrain.lua
> +                    unit.resetJammer = true
Unit fields (fields in `self`) should always be pascal case.

2022-06-11 15:03 UTC, Garanas commented on lua/aibrain.lua
> +                        WaitSeconds(0.3)
It appears this delay is required or the change is not being picked up. I suspect that the unit intel is disabled but only picked up / updated a few ticks later. After that we can re-enable it again. @KionX Do you know if intel is managed at a different tick rate than the simulation?

2022-06-11 15:03 UTC, Garanas requested changes
Exciting - looking promising 😄

2022-06-11 15:44 UTC, KionX commented on lua/aibrain.lua
> +                        WaitSeconds(0.3)
Don't know.

2022-06-11 18:00 UTC, Spikey84 commented on lua/aibrain.lua
> +                        WaitSeconds(0.3)
Yea i could not get intel to toggle any faster, it also creates a cool effect of many popping on one after another. I was thinking maybe we create an array from each army that way if army 1 has 100 frigs and army 2 has one sparky, army 2 wont have to wait for army 1's frigs in order to reload the sparky. Thoughts?

2022-06-11 18:51 UTC, Spikey84 commented on lua/aibrain.lua
> +            CoroutineYield(1)
fixed, thanks!

2022-06-11 18:52 UTC, Spikey84 commented on lua/aibrain.lua
> +        if reconType == 'LOSNow' or econType == 'Omni' then
lol ig thats why it was not working, thanks

2022-06-11 18:52 UTC, Spikey84 commented on lua/aibrain.lua
> +    AddJammer = function(self, unit)
done.

2022-06-11 18:52 UTC, Spikey84 commented on lua/aibrain.lua
> +        self.jammers = { }
Good to know.

2022-06-12 07:30 UTC, Garanas commented
@Spikey84 Make sure to hit the resolve button when you resolve them 😄 

And for future suggestions - note that these are suggestions. We can always discuss them if you happen to disagree.

2022-06-12 07:31 UTC, Garanas commented on lua/aibrain.lua
> +                        WaitSeconds(0.3)
Each army has its own brain, therefore each brain triggers their jammers on / off individually.

2022-06-12 14:27 UTC, Spikey84 commented on lua/aibrain.lua
> +                    RemoveJammer(jammer)
What would the difference be? Just consistency?

2022-06-12 14:36 UTC, Garanas commented on lua/aibrain.lua
> +                    RemoveJammer(jammer)
Just consistency, yes - I still need to do this for some other trackers too.

2022-06-13 10:22 UTC, Garanas commented on lua/sim/Unit.lua
> +        self.ResetJammer = false
This field does not need to be set by default - if the field doesn't exist then it defaults to `nil`, which is equal to `false` in the average if statement.

For your idea: a single hash entry takes up about 20 bytes. We can easily have 6000+ units in a game. That means we have over 120 kilobytes for a flag that at most 1% of the units may need at any given point.

2022-06-15 01:44 UTC, Spikey84 commented on lua/aibrain.lua
> +                            jammer:EnableUnitIntel('AutoToggle', 'Jammer')
I am unsure how this should work, should it be `ok, msg = pcall(jammer:DisableUnitIntel, 'AutoToggle', 'Jammer')`? what does this do?

2022-06-21 22:04 UTC, Spikey84 commented
@Garanas all tested and working! Ready to be put on faf dev unless u see any issues.

2022-06-22 05:29 UTC, Garanas commented on lua/sim/Unit.lua
> +        if self.Blueprint.Intel.JammerBlips > 0 then
Changing the state may kill the thread it is running on, this should be run before `ChangeState` runs.

2022-06-22 12:44 UTC, Spikey84 commented on lua/sim/Unit.lua
> +        if self.Blueprint.Intel.JammerBlips > 0 then
Fixed it!

2022-07-23 23:16 UTC, Hdt80bro commented on lua/aibrain.lua
> +                            jammer:EnableUnitIntel('AutoToggle', 'Jammer')
Almost!
You'd do `local ok, msg = pcall(jammer.DisableUnitIntel, jammer, 'AutoTggle', 'Jammer')` (and again for EnableUnitIntel), since the colon syntax needs the actual function call to insert the calling table into, instead of a reference. What this does is make sure that any errors don't break the rest of the AIBrain. If the `pcall` *does* return an error, you would report it like this:
```lua
if not ok then 
    WARN("JammingFollowUpThread: " .. repr(msg))
end
```

2022-07-24 01:10 UTC, Hdt80bro approved these changes

2022-07-24 01:26 UTC, merged