Feature/annotate campaign files
FAForever/fa pull request #3962
Opened 2022-06-15 21:30 UTC by Garanas

Annotates various campaign files to give a modern touch to campaign-related development. 

Progression:
- [ ] BaseManager.lua
- [ ] OpAI.lua
- [ ] Objectives2.lua
- [ ] ScenarioFramework.lua
- [ ] ScenarioUtils.lua
- [ ] Cinematics.lua

2022-06-15 21:31 UTC, Garanas commented
I broke it there for a second 😃

2022-06-17 03:42 UTC, hahn-kev requested changes
I did a bit of research and it doesn't seem there's a good way to leave comments on fields of classes unfortunately.

2022-06-17 03:42 UTC, hahn-kev commented on lua/AI/OpAI/BaseManager.lua
> +
this line 127 needs to be removed, for some reason it seems to break the class definition for `BaseManager` when it's removed then autocomplete on self inside functions works fine and shows all the other methods

2022-06-17 03:42 UTC, hahn-kev commented on lua/AI/OpAI/BaseManager.lua
> +---@class UnitGroup                             # Name reference to a unit group as defined in the map
not totally sure what you mean by types that originate from the map, but we should try and give these proper types. Right now they're not much help to the developer as they are, you call them all names, so are they strings? if they're a type that's returned by some map method, like `map:getMarker(1)` then we should also annotate that map method with the same type to link them together to help the developer, right now they might not know where to get a Area class instance or Marker.

2022-06-17 03:42 UTC, hahn-kev commented on lua/AI/OpAI/BaseManager.lua
> +---@class FileFunctionRef                       # { file, function }
Similar with these, though it looks like maybe they could be a couple different types. In which case I'd do something like this `@alias FileFunctionRef string|fun(someArg:number):string` that says that a `FileFucnctionRef` can be either a string (maybe a file name? just guessing here) or it can be a function who's first argument is a number and the function returns a string.

2022-06-17 03:42 UTC, hahn-kev commented on lua/AI/OpAI/BaseManager.lua
> +    ---@param levelTable any            # A table of { { UnitGroup, Priority } } that represents the priority of various sections of the base
it looks like from how it's used this should have the type `table<UnitGroup, number>`

2022-06-17 05:52 UTC, Garanas commented on lua/AI/OpAI/BaseManager.lua
> +---@class UnitGroup                             # Name reference to a unit group as defined in the map
These are defined in the map, as part of the `_save.lua` file. That was my intend, it is in the end a string. Initially I wanted to use an alias, but that only shows it as a string.

2022-06-17 05:53 UTC, Garanas commented on lua/AI/OpAI/BaseManager.lua
> +---@class FileFunctionRef                       # { file, function }
Ah, no - this is an array-based table with two entries: the file to look for a function, and a function name. They are both strings. I'm all for a better alternative.

2022-06-17 10:28 UTC, hahn-kev commented on lua/AI/OpAI/BaseManager.lua
> +---@class FileFunctionRef                       # { file, function }
hum, that is a bit tricky. It looks like we can at least do this
```lua
---@class FileName: string
---@class FunctionName: string
---@class FileFunctionRef # { file, function }
---@field [1] FileName
---@field [2] FunctionName
```

so the first 2 lines just create 2 simple classes that are just strings, this basically the same as an alias, but the names will be preserved as a sort of comment/hint to the developer. Then for the `FileFunctionRef` class we declare it as having 2 fields which are just index 1 and 2 and we can then specify the type of them. This is actually quite similar to how you can define tuples in ts.

2022-06-17 10:30 UTC, hahn-kev commented on lua/AI/OpAI/BaseManager.lua
> +---@class UnitGroup                             # Name reference to a unit group as defined in the map
ok, I think that makes sense. Since it's a string just indicate that the class extends a string like this `@class Area: string` this is pretty much the same as an alias but the name doesn't get removed.

2022-06-17 11:32 UTC, Garanas commented on lua/AI/OpAI/BaseManager.lua
> +---@class FileFunctionRef                       # { file, function }
I wasn't aware you could define index-based fields too, that is great!

2022-06-17 12:32 UTC, Garanas commented on lua/ScenarioPlatoonAI.lua
>  function DefaultOSBasePatrol(platoon)
@speed2CZ could you tell me more about this function?

2022-06-17 15:15 UTC, hahn-kev commented on lua/AI/OpAI/BaseManager.lua
> +---@class FileFunctionRef                       # { file, function }
me either, I found out when I tested it lol

2022-06-21 07:07 UTC, merged

2022-06-21 07:46 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +    ---@param radius number             # Radius of the base - any structure that is within this distance to the center of the base is considered part of the base
Radius is used for managing factories, engineers and forming platoons

2022-06-21 07:53 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +    ---@param initial boolean       # ??
if true, it skips sorting the build groups by priority
it should be false (or rather nil) for any group that is added after the base is initialized

2022-06-21 07:55 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +    --- Defines the radius of the base manager, which is used to search for factories and engineers
and forming platoons

2022-06-21 07:57 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +    --- Add to the engineer count, useful when gifting the base engineers.
This is used internally by the main base manager engineer thread to keep track of how many engineers are in the base

2022-06-21 07:58 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +    --- Defines the maximum number of construction engineers
constructions engineers are those that can start new construction projects, others can still assist them

2022-06-21 08:01 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +    ---comment
`self.ConstructionAssistBool` determines if the engineers that are not constructions engineers or permanently assisting engineers, should assist construciton projects

2022-06-21 08:03 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +    ---comment
Permanent assist engineers are assigned to only assist factories and are evenly split among all factories, these engineers won't do any other tasks in the base.

2022-06-21 08:06 UTC, speed2CZ commented on lua/ScenarioPlatoonAI.lua
>  function BuildOnce(platoon)
It's an extra function that can be set to run on the platoon when the platoon is formed. Setting it's priority to 0 so it won't be rebuild again when it dies.

2022-06-21 08:08 UTC, speed2CZ commented on lua/ScenarioPlatoonAI.lua
>  function DefaultOSBasePatrol(platoon)
This is some vanilla campaign function. The logic for the vanilla platoons is complicated and hard to manage, so I prefer to replace it to the FA format rather than investigating too much what it does and how.

2022-06-21 08:12 UTC, speed2CZ commented on lua/ScenarioPlatoonAI.lua
> +--- | PatrolChains          | Chain of locations to patrol
PatrolRoute or PatrolChain, not plural