Improve intel management
FAForever/fa pull request #4022
Opened 2022-07-06 05:50 UTC by Hdt80bro

Changes intel from checking the energy levels every half second to only using the AIBrain's `EnergyDependingEntity` callbacks. This also involves some cooperation from the enhancement code, since some enhancements add or create intel traits (it also keeps the radar flickering synced up to the enhancement completion). In order to not change the radar flickering behavior, I ended up partially restoring that half-second loop since the flickering was originally created by an interaction between it and the low energy level disabler. This does mean we now have freedom over the flicker duty cycle, which I've taken the liberty of implementing via `Blueprint.Intel.DeactivateTime` (to counterpart `ReactivateTime`).

A unit's `IntelDisables` are now only allocated for what they need; it is no longer the case that all units create the table with all fields, despite most units having nothing to do with intel, and even those that do not using all of the fields anyway. You will find that `IntelDisables` is now very often `nil`.

There may have been a bit of refactoring as well...

2022-07-06 06:58 UTC, Garanas commented on lua/sim/Unit.lua
> +            local vetMass = bp.VeteranMass
One of the other refactorings spotted

2022-07-06 06:59 UTC, Garanas commented on lua/sim/Unit.lua
>          local function DisableOneIntel(disabler, intel)
Best to not have this has a function inside a function - because of that it creates a new closure every time `DisableUnitIntel` is called

2022-07-06 07:00 UTC, Garanas commented on lua/sim/Unit.lua
> +    IntelFlickerThread = function(self)
I don't think intel should flicker - just like shields, if you have no power it should be just turned off.

2022-07-06 07:01 UTC, Garanas reviewed
Looking good - I'll review it more in-depth this weekend.

2022-07-06 07:04 UTC, Hdt80bro commented on lua/sim/Unit.lua
>          local function DisableOneIntel(disabler, intel)
Ah, good catch.

2022-07-06 07:10 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    IntelFlickerThread = function(self)
I was trying my best to preserve current behavior--I think lots of players are used to radar flickering as a visual indicator of a power stall. Note that it will also affect cloak and stealth flickering.
It's built into the blueprint with `ReactivationTime`--do you want to remove that altogether?

2022-07-06 07:27 UTC, Garanas commented on lua/sim/Unit.lua
> +    IntelFlickerThread = function(self)
Reactivation time is fine, but it should run once you have sufficient power again. The flickering makes the game more difficult to read and to understand, same as it did for the shields (where it would flicker on and catches a tactical missile).

2022-07-06 07:32 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    IntelFlickerThread = function(self)
Alright, I can remove it. Not dealing with flickering simplifies a couple other things too.

2022-07-24 08:37 UTC, Garanas commented
I'll pick this up when I'm back 👍

2022-08-03 07:03 UTC, Garanas commented on lua/sim/Unit.lua
> +        -- it's been depleted, and that removes any threads. Good to be safe though.
The correct answer to this is 'mods'

2022-08-07 07:51 UTC, Garanas commented on lua/sim/Unit.lua
> +        self:EnableUnitIntel('Construction')
This causes all fields to have at least an empty table.

2022-08-07 07:52 UTC, Garanas requested changes
Took a lot longer than expected - apologies for that.

The pull request works, but there's an issue. I've added a routine to log the intel state of a unit, you can find it in the hotkeys menu by searching for `intel` . For each unit all fields have at least an empty table due to the call to enabling intel after construction. Do you reckon there's a way to prevent this from happening? As an example, an Aurora should have an empty intel table.

edit: as an example, the `IntelDisabler` table looks like this for an Aurora:

```
INFO:  - Cloak: table: 1DCBA758
INFO:  - CloakField: table: 1DCBAA78
INFO:  - Omni: table: 1DCBA348
INFO:  - Radar: table: 1DCBA1B8
INFO:  - RadarStealth: table: 1DCBAB90
INFO:  - RadarStealthField: table: 1DCBA488
INFO:  - Sonar: table: 1DCBAF28
INFO:  - SonarStealth: table: 1DCBA0A0
INFO:  - SonarStealthField: table: 1DCBAD98
INFO:  - Spoof: table: 1DCBA618
```

2022-08-07 11:07 UTC, Garanas commented
Fixed the issue I mentioned. There's one more though: when you change the script bits (for say, a radar) then it adds in all remaining intel types into the table. See also:

```
    OnScriptBitSet = function(self, bit)
        if bit == 0 then -- Shield toggle
            self:PlayUnitAmbientSound('ActiveLoop')
            self:EnableShield()
        elseif bit == 1 then -- Weapon toggle
            -- Amended in individual unit's script file
        elseif bit == 2 then -- Jamming toggle
            self:StopUnitAmbientSound('ActiveLoop')
            self:SetMaintenanceConsumptionInactive()
            self:DisableUnitIntel('ToggleBit2', 'Jammer')
        elseif bit == 3 then -- Intel toggle
            self:StopUnitAmbientSound('ActiveLoop')
            self:SetMaintenanceConsumptionInactive()
            self:DisableUnitIntel('ToggleBit3', 'RadarStealth')
            self:DisableUnitIntel('ToggleBit3', 'RadarStealthField')
            self:DisableUnitIntel('ToggleBit3', 'SonarStealth')
            self:DisableUnitIntel('ToggleBit3', 'SonarStealthField')
            self:DisableUnitIntel('ToggleBit3', 'Sonar')
            self:DisableUnitIntel('ToggleBit3', 'Omni')
            self:DisableUnitIntel('ToggleBit3', 'Cloak')
            self:DisableUnitIntel('ToggleBit3', 'CloakField') -- We really shouldn't use this. Cloak/Stealth fields are pretty busted
            self:DisableUnitIntel('ToggleBit3', 'Spoof')
            self:DisableUnitIntel('ToggleBit3', 'Jammer')
            self:DisableUnitIntel('ToggleBit3', 'Radar')
        elseif bit == 4 then -- Production toggle
            self:OnProductionPaused()
        elseif bit == 5 then -- Stealth toggle
            self:StopUnitAmbientSound('ActiveLoop')
            self:SetMaintenanceConsumptionInactive()
            self:DisableUnitIntel('ToggleBit5', 'RadarStealth')
            self:DisableUnitIntel('ToggleBit5', 'RadarStealthField')
            self:DisableUnitIntel('ToggleBit5', 'SonarStealth')
            self:DisableUnitIntel('ToggleBit5', 'SonarStealthField')
```

Preferably, it wouldn't do that. Question is whether it is worth fixing?

2022-08-08 19:55 UTC, Hdt80bro commented
Well, it's very easy to fix. The question is whether it impacts mods dynamically enabling intel fields after the disable, as they then won't have the proper disables set on the field. This is already a problem for the construction disabler, but I think it's safe to presume that no radar field will be active while it's building.

2022-08-19 17:10 UTC, Garanas commented
The solution still expands the intel table to everything when disabling and enabling. It won't make it for this patch, maybe we need to rebuild how intel works from the ground up. What if we can solely enable / disable what the unit is able to produce (at any point in time)?

2022-08-19 17:12 UTC, Garanas commented
And there's also issues with animations and effects that trigger, even though the intel is disabled by say energy.

2022-10-23 09:19 UTC, Garanas commented
@Hdt80bro I am closing this, we'll need to find the time for a better solution someday.

2022-10-23 09:19 UTC, closed without merging