Intigrated STP with Category Support
FAForever/fa pull request #4101
Opened 2022-08-06 22:50 UTC by Spikey84

This PR integrates @4z0t's ui mod called Specific Target Priorities to the game. This mod allows a player to select with a hotkey the kind of unit they with their units to target. In addition to integrating the current mod i am also making modifications that will allow the targeting of all variations of units (different factions) without selecting each on individually.

2022-08-06 22:55 UTC, Spikey84 commented
Things to do here:
* Add default TP hotkey
* Make hotkey look cleaner
* Finish/rework the category table
* check with @Garanas that performance is not effected by this change

2022-08-15 21:54 UTC, MrRowey commented
![image](https://user-images.githubusercontent.com/20344151/184724933-903e6306-609f-445b-a0ec-0ce4ca72b410.png)
Set Hotkey to Units to P and this is my error

2022-08-15 22:08 UTC, Spikey84 commented
@MrRowey do u have ATP and/or STP?

2022-08-16 01:07 UTC, 4z0t commented on lua/keymap/misckeyactions.lua
> +    for _, c in categories do
Use hashed categories to check

2022-08-16 01:07 UTC, 4z0t commented on lua/keymap/misckeyactions.lua
> +    local masterTP = "{categories." .. bpID .. ", " .. tp .. ", " .. tp2 .. ", " .. tp3 .. ", " .. tp4 .. "}"
String format

2022-08-16 07:20 UTC, Garanas commented on lua/keymap/keydescriptions.lua
> +    ['set_target_priority'] = 'Set Target Priority',
Make normal english sentences - No Additional Capitals

2022-08-16 07:20 UTC, Garanas commented on lua/keymap/misckeyactions.lua
> +function SetWeaponPrioritiesSpecific()
Please add a description to the function, as the title is not that specific (even though it is suggesting that it is 😄 )

2022-08-16 07:20 UTC, Garanas commented on lua/keymap/misckeyactions.lua
> +function SetDefaultWeaponPriorities()
Please add a description to the function

2022-08-16 07:22 UTC, Garanas commented on lua/keymap/misckeyactions.lua
> +    local masterTP = "{categories." .. bpID .. ", " .. tp .. ", " .. tp2 .. ", " .. tp3 .. ", " .. tp4 .. "}"
For all of them 😄

2022-08-16 07:25 UTC, Garanas requested changes
The suggested changes still need some fine tuning, but look good in general. Functionally it appears to work already and I am already a huge fan 👍

2022-08-16 07:27 UTC, Garanas commented
You can set the target priority to units of yourself, which isn't necessarily a bad thing but just wanted to point it out.

![image](https://user-images.githubusercontent.com/15778155/184822037-df3108ce-051d-4e86-b366-853b43b7e57e.png)
The code needs some fail safes (for modded units, in particular) when a certain field does not exist. Take the command unit, it has no tech level.

2022-09-06 20:33 UTC, Garanas commented
As a few examples:

```
{ -- Shield disruptor
  categories.dal0310, 
  categories.TECH3 * categories.AEON * categories.DIRECTFIRE * categories.LAND, 
  categories.TECH3 * categories.DIRECTFIRE * categories.LAND, 
  categories.DIRECTFIRE * categories.LAND, 
  categories.LAND
}

{ -- Janus
  categories.dea0202, 
  categories.TECH2 * categories.UEF * categories.ANTIAIR * categories.AIR, 
  categories.TECH2 * categories.ANTIAIR * categories.AIR, 
  categories.ANTIAIR * categories.AIR, 
  categories.AIR
}

{ -- Bouncer
  categories.dal0310, 
  categories.TECH3 * categories.AEON * categories.DIRECTFIRE * categories.LAND, 
  categories.TECH3 * categories.DIRECTFIRE * categories.LAND, 
  categories.DIRECTFIRE * categories.LAND, 
  categories.LAND
}
```

The logic can be found in the changes, but roughly:
- unit id that we hover over
- common categories that the unit we hover over may share with similar units, including faction
- common categories that the unit we hover over may share with similar units
- common categories that the unit we hover over may share with similar units of any tech
- common categories that the unit we hover over may share with similar units of the same layer

2022-09-06 20:33 UTC, Garanas approved these changes

2022-09-06 20:34 UTC, merged