File Cleaning / Annotations Part 4
FAForever/fa pull request #4174
Opened 2022-08-25 10:27 UTC by MrRowey

2022-08-25 19:29 UTC, Garanas commented on engine/Sim.lua
> +---@alias AIPersonality any
string

2022-08-25 19:30 UTC, Garanas commented on engine/Sim.lua
> +---@alias EconomyEvent any
There's an economy event class, I think

2022-08-25 19:30 UTC, Garanas commented on engine/Sim/CPlatoon.lua
> +---@param squad? string Types: 'Attack', 'Artillery', 'Guard' 'None', 'Scout', 'Support'.
could you make this an alias?

2022-08-25 19:30 UTC, Garanas commented on engine/Sim/CPlatoon.lua
> +---@param squad? string Types: 'Attack', 'Artillery', 'Guard' 'None', 'Scout', 'Support'.
And then remove the comment

2022-08-25 19:36 UTC, Hdt80bro reviewed
Thank you!

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param entity Entity
The reclaiming 'entity' (should probably rename to `reclaimer` eventually) is a `Unit`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param fxBag any
`fxTable` is a `FileName[][]` (I know I said effects are `string[]` earlier but I'm realizing that `FileName` is more descriptive)
`fxBag` is `any[]` (an old-style trash bag, not a new-style `TrashBag`)--though maybe we should make a `Trash` annotation class in the future? There's so much to do...

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param massKilledTrue boolean|true
`massKilledTrue` is a worded a little confusingly--it should read like "true mass killed", so it's actually a `number`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@return string
Multiple returns again (I've only been making one comment per critique, so that I don't create 5 comments pointing out the same thing in different spots--let me know if it'd be easier to point out each one like I did here so that you don't have to go through and find all of the affected lines)

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param firingWeapon Unit The weapon that the projectile originates from
`firingWeapon`s should be a `Weapon`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param anim any
`anim` is a `string`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@return any
returns `Wreckage | nil`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@return nil
Returns `Wreckage`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +        local scale = (((bp.SizeX or 0) + (bp.SizeZ or 0)) * 0.5)
Nice catch!

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param bones string[] List of bones
We should use `Bone`, since it allows for bone indices as well as bone names.

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@return nil
Both return types should be `Weapon | nil`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param callback any
`callback` is of type `fun(unit: Unit)`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@return integer
I've no clue why, but the return value is always zero so you *could* do `@return 0` if you'd like :)
I think FAF uses this function as a callback from the engine to fix bugs, rather than actually informing it about a rebuild bonus, so that might be why--and also why `bp` isn't used.

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param intel BpIntel
Both of these parameters are `string`s

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param intel BpIntel
Still a `string`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param hook any
OnDetected `hook`s are `fun(unit: Unit, army: number)`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param TypeSuffix any
These two look like `string`s

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param bpTable BlueprintBase
Unit Blueprints are `UnitBlueprint`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@return number
Returns `time`, `energy`, `mass`, in that order

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param bpShield Shield
`BpDefense.Shield`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param spillingUnit any
spillingUnit is `Unit`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param location number
`Vector`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param progress integer
`number`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param transport any
Probably `BaseTransport`

2022-08-25 19:36 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@return number
`sizeX`, `sizeY`, `sizeZ`

2022-08-25 19:59 UTC, Hdt80bro commented on engine/Sim.lua
> +---@alias EconomyEvent any
I used `moho.EconomyEvent`

2022-08-25 20:03 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> +---@param squad? string Types: 'Attack', 'Artillery', 'Guard' 'None', 'Scout', 'Support'.
https://github.com/FAForever/fa/pull/4174#discussion_r955289938
It's not *fair* that your review shows up first despite being later. Does it sort by when it was started?

2022-08-25 21:50 UTC, MrRowey commented on lua/sim/Unit.lua
> +    ---@return integer
it comments out the 0

2022-08-27 15:29 UTC, MrRowey commented
@Hdt80bro this should be good to go once your happy

2022-08-29 19:50 UTC, Hdt80bro requested changes
looking good!

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/CollisionBeam.lua
> +    ---@param TargetType string
Can be `ImpactType`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/CollisionBeam.lua
> +    ---@param targetEntity Entity
same two comments

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/CollisionBeam.lua
> +    ---@param targetEntity Entity
`@param targetEntity? Unit | Prop`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param overRide boolean
overRide is `number`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param order integer
same also

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param order integer
same also

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param EffectsBag any
EffectsBag is a `TrashBag`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param TypeSuffix any
same two comments

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param motionState boolean
motionState is `string`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param treads any
treads can be `UnitBlueprintTreads`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param treads any
treads can be `UnitBlueprintTreadMarks`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param target_bp any
target_bp is `UnitBlueprint``

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param sound BpSound A string identifier that represents the sound to be played.
sound is `SoundBlueprint` now

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param bpShield BpDefense.Shield
bpShield is `UnitBlueprintDefenseShield` now

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param transport BpTransport
sorry, I was wrong, transport is `BaseTransport`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param orientation number
orientation is `Quaternion`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param orientation number
same also

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param orientation number
same also

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param source any
I think these are `string`s

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param shield BpDefense.Shield Requires an `IsDestroyed` check when using as the shield may have been destroyed when the missile impacts
sorry, changed to `UnitBlueprintDefenseShield`

2022-08-29 19:50 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param location number
location should be `Vector`

2022-08-29 22:12 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> +---@return true/false
boolean

2022-08-29 22:12 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> +---@return true/false
boolean

2022-08-29 22:12 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return command
---@return SimCommand

2022-08-29 22:12 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return Unit.
---@return Unit

2022-08-29 22:13 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return Unit.
---@return Unit

2022-08-29 22:13 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return Unit.
---@return Unit

2022-08-29 22:14 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
>  -- @return command
---@return PlatoonCommand

2022-08-29 22:14 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return true/false
---@return boolean

2022-08-29 22:14 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return true/false
---@return boolean

2022-08-29 22:14 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return true/false
---@return boolean

2022-08-29 22:15 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return true/false
---@return boolean

2022-08-29 22:15 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return true/false
---@return boolean

2022-08-29 22:15 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return command
---@return PlatoonCommand

2022-08-29 22:15 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return command
---@return PlatoonCommand

2022-08-29 22:16 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return command
---@return PlatoonCommand

2022-08-29 22:16 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return command
---@return PlatoonCommand

2022-08-29 22:16 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return number
---@return number

2022-08-29 22:17 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return command
---@return PlatoonCommand

2022-08-29 22:17 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return command
---@return PlatoonCommand

2022-08-29 22:17 UTC, Hdt80bro commented on engine/Sim/CPlatoon.lua
> --- @return command
---@return PlatoonCommand

2022-08-29 22:19 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param target Unit
---@param target Unit | Prop

2022-08-29 22:20 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param target Unit
---@param target Unit | Prop

2022-08-29 22:20 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param target Unit
---@param target Unit | Prop

2022-08-29 22:20 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param target Unit
---@param target Unit | Prop

2022-08-29 22:20 UTC, Hdt80bro commented on lua/sim/Unit.lua
> +    ---@param target Unit
---@param target Unit | Prop

2022-08-30 00:22 UTC, merged