Annotation work /File Cleaning part 5
FAForever/fa pull request #4183
Opened 2022-08-26 13:12 UTC by MrRowey

Files from the `/lua/*` Directory
- AIChatSorian.lua
- aeonprojectiles.lua
- aeonunits.lua
- aeonweapons.lua
- aibrain.lua
- cinematics.lua
- cybranprojectiles.lua
- cybranunits.lua
- cybranweapons.lua

2022-08-27 09:54 UTC, Garanas commented on lua/AIChatSorian.lua
> +---@param text any
this is a string

2022-08-27 09:55 UTC, Garanas commented on lua/AIChatSorian.lua
> +---@return table
table of indices, so `number[]`

2022-08-27 09:55 UTC, Garanas commented on lua/AIChatSorian.lua
> +---@return table
table of indices, so number[]

2022-08-27 09:56 UTC, Garanas commented on lua/aeonprojectiles.lua
> +    -- Strategic bomber
Best to put these type of comments above the class definition, and with triple `-` . Something like: `used by strategic bomber`

2022-08-27 09:58 UTC, Garanas commented on lua/aeonunits.lua
> +    ---@param order integer
not a number, but a string. Originates from `Unit:OnStartBuild` , not sure what all the possibilities are. It would be nice to document that somehow.

2022-08-27 10:09 UTC, Garanas requested changes
Good work, few changes here and there. @Hdt80bro feel free to merge as you see fit after Rowey has processed the feedback

2022-08-27 10:09 UTC, Garanas commented on lua/aibrain.lua
>          table.insert(self.IntelTriggerList, triggerSpec)
for the trigger spec we should make an alias / class and annotate it properly

2022-08-27 10:09 UTC, Garanas commented on lua/aibrain.lua
> +    ---@param callback any
function, you can find the arguments in the body

2022-08-27 10:09 UTC, Garanas commented on lua/aibrain.lua
> +    ---@param callback any
function

2022-08-27 10:09 UTC, Garanas commented on lua/aibrain.lua
> +    ---@param pltnTable table
Best to turn this into a separate (annotation) class and use that instead of `table`

2022-08-27 10:09 UTC, Garanas commented on lua/aibrain.lua
> +    ---@param primary number
appears to be a list of units

2022-08-27 10:09 UTC, Garanas commented on lua/aibrain.lua
> +    ---@return any
Returns a unit

2022-08-27 10:09 UTC, Garanas commented on lua/aibrain.lua
> +    ---@return table
Vector[]

2022-08-27 10:09 UTC, Garanas commented on lua/cinematics.lua
> +---@param units Unit
list of units

2022-08-27 10:09 UTC, Garanas commented on lua/cybranunits.lua
> +    ---@param built boolean
I think this is a Unit

2022-08-27 10:09 UTC, Garanas commented on lua/cybranunits.lua
> +    ---@param bots Unit
Unit[]

2022-08-27 10:09 UTC, Garanas commented on lua/cybranunits.lua
> +    ---@param order number
A string, see earlier comment. Originates from `Unit:OnStartbuilt`

2022-08-27 10:09 UTC, Garanas commented on lua/cybranunits.lua
> +    ---@param new string
these are layers, so `Layer`

2022-08-27 10:09 UTC, Garanas commented on lua/cybranunits.lua
> +    ---@param type string
I think there is a damage type annotation, @Hdt80bro ?

2022-08-27 10:09 UTC, Garanas commented on lua/cybranunits.lua
> +    ---@param order number
string, see earlier comments

2022-08-27 10:09 UTC, Garanas commented on lua/cybranunits.lua
> +    ---@param order number
string, see earlier comments

2022-08-27 10:22 UTC, Hdt80bro commented on lua/cybranunits.lua
> +    ---@param type string
`DamageType`--I wasn't sure what `type` was for, since the argument doesn't really get used, but damage type makes a lot of sense.

2022-08-27 11:01 UTC, MrRowey commented on lua/aibrain.lua
>          table.insert(self.IntelTriggerList, triggerSpec)
Im assuming everything that need to be in the trigger spec is the comment above it ?

2022-08-28 07:09 UTC, Garanas commented
@Hdt80bro feel free to merge as you see fit

2022-09-09 16:59 UTC, Hdt80bro reviewed
Sorry, I forgot to finalize my review!

2022-09-10 21:46 UTC, MrRowey commented on lua/aeonprojectiles.lua
> +    ---@param targetType string
what am i putting here as i cant find what it should be from defaultunits ? at first i thought it should be something like `TargetType` like `DamageType`

2022-09-13 07:48 UTC, Hdt80bro commented on lua/aeonprojectiles.lua
> +    ---@param targetType string
You know what, don't worry about it, it's fine

2022-09-13 07:49 UTC, merged