Annotation-work-/File-Cleaning-part-7
FAForever/fa pull request #4184
Opened 2022-08-26 21:49 UTC by MrRowey

Files from the `/lua/*` Directory
- EffectUtilities.lua
- EffectUtilitiesAeon.lua
- dataInit.lua
- defaultantiprojectile.lua
- defaultcollisionbeams.lua
- defaultexplosions.lua
- defaultunits.lua
- formations.lua
- game.lua
- kirvesbeams.lua

2022-08-27 10:10 UTC, Garanas commented on lua/EffectUtilities.lua
> +---@param buildEffectsBag any[] unused
TrashBag

2022-08-27 10:16 UTC, Garanas requested changes
Great work, requires a few small changes.

2022-08-27 10:16 UTC, Garanas commented on lua/defaultantiprojectile.lua
> +    ---@param spec any
You can decipher the spec based on what happens in `OnCreate` below, best to add in a separate class `FlareSpec`

2022-08-27 10:16 UTC, Garanas commented on lua/defaultantiprojectile.lua
> +    ---@param other any
a Projectile

2022-08-27 10:16 UTC, Garanas commented on lua/defaultantiprojectile.lua
> +    ---@param spec any
You can decipher the spec based on what happens in `OnCreate` below, best to add a separate class `DepthChargeSpec`

2022-08-27 10:16 UTC, Garanas commented on lua/defaultantiprojectile.lua
> +    ---@param other any
Projectile

2022-08-27 10:16 UTC, Garanas commented on lua/defaultantiprojectile.lua
> +        ---@param spec any
You can decipher the spec, see previous comments

2022-08-27 10:16 UTC, Garanas commented on lua/defaultcollisionbeams.lua
> +    ---@param targetEntity Projectile
Unit | Projectile | Prop | nil

2022-08-27 10:16 UTC, Garanas commented on lua/defaultcollisionbeams.lua
> +    -- used by ML & cyb ACU
Best to add these to the class description, or they are lost essentially

2022-08-27 10:16 UTC, Garanas commented on lua/defaultcollisionbeams.lua
> +    ---@param targetEntity Unit
`Unit | Projectile | Prop | nil`

2022-08-27 10:16 UTC, Garanas commented on lua/defaultcollisionbeams.lua
> +    ---@param targetEntity Unit
`Unit | Projectile | Prop | nil`

2022-08-27 10:16 UTC, Garanas commented on lua/defaultcollisionbeams.lua
> +    -- unknown unit (big size though)
See previous comments about this, best to add to class description

2022-08-27 10:16 UTC, Garanas commented on lua/defaultcollisionbeams.lua
> +    ---@param targetEntity Unit
Unit | Projectile | Prop | nil

2022-08-27 10:16 UTC, Garanas commented on lua/defaultcollisionbeams.lua
> +    ---@param targetEntity Unit
`Unit | Projectile | Prop | nil`

2022-08-27 10:16 UTC, Garanas commented on lua/defaultcollisionbeams.lua
> +    ---@param targetEntity Unit
`Unit | Projectile | Prop | nil`

2022-08-27 10:16 UTC, Garanas commented on lua/defaultcollisionbeams.lua
> +    ---@param targetEntity Unit
You get the picture, `targetEntity` in `OnImpact` should be `Unit | Projectile | Prop | nil`. Skipping the remainders (comment wise)

2022-08-27 10:16 UTC, Garanas commented on lua/defaultexplosions.lua
> +---@return Unit
Returns an Entity, not a Unit

2022-08-28 07:08 UTC, Garanas commented
@Hdt80bro feel free to merge as you see fit

2022-08-29 18:14 UTC, Hdt80bro commented on lua/formations.lua
> +---@return true
returns a `table`

2022-08-29 18:14 UTC, Hdt80bro commented on lua/formations.lua
> +---@param occupiedSpaces any
occupiedSpaces is a `boolean[][]`

2022-08-29 18:14 UTC, Hdt80bro commented on lua/formations.lua
> +---@param occupiedSpaces any
same

2022-08-29 18:14 UTC, Hdt80bro commented on lua/formations.lua
> +---@return Unit[]
Not actually a `Unit[]`; leave as `any`

2022-08-29 18:14 UTC, Hdt80bro commented on lua/game.lua
> +---@return number|unknown
This function accepts an `Army` and returns `number`

2022-08-29 18:14 UTC, Hdt80bro commented on lua/game.lua
> +---@param army number
army can be `Army` here

2022-08-29 18:14 UTC, Hdt80bro commented on lua/game.lua
> +---@param army number
army can be `Army` here

2022-08-29 18:14 UTC, Hdt80bro commented on lua/game.lua
> +--- Gets a table with ids of restricted units {Global = {}, PerArmy = {}}
return `UnitRestrictions`; see below

2022-08-29 18:14 UTC, Hdt80bro commented on lua/game.lua
> +--- Gets blueprints that can be upgraded, e.g. MEX, Shield, Radar structures
returns `UnitBlueprint[]`

2022-08-29 18:37 UTC, MrRowey commented on lua/defaultantiprojectile.lua
> +---@class FlareSpec
it this somthing that is TODO or somthing i need to add

2022-08-29 20:58 UTC, Hdt80bro commented on lua/defaultantiprojectile.lua
> +---@class FlareSpec
If you'd like, you can tackle that or leave it as to-do

2022-08-29 22:37 UTC, Hdt80bro commented on lua/game.lua
> +---@return Army|number
Sorry, I meant
```
---@param armyName Army
---@return number
```

2022-08-29 22:37 UTC, Hdt80bro commented on lua/defaultunits.lua
>      ---@param orientation number
orientation is `Quaternion`

2022-08-29 22:37 UTC, Hdt80bro commented on lua/formations.lua
> +---@param spacing any
`spacing? number defaults to 1`

2022-08-29 22:37 UTC, Hdt80bro commented on lua/formations.lua
> +---@param spacing any
`spacing? number defaults to 1`

2022-08-29 22:37 UTC, Hdt80bro commented on lua/formations.lua
> +---@param spacing any
`spacing? number defaults to 1`

2022-08-29 22:37 UTC, Hdt80bro commented on lua/game.lua
> +---@return number buildtimerate
let's call this `time`

2022-09-08 17:30 UTC, Hdt80bro commented on lua/defaultunits.lua
> +    ---@param bones Bone
`Bone[]`

2022-09-08 17:30 UTC, Hdt80bro commented on lua/formations.lua
> +---@param formationUnits Unit
`Unit[]`

2022-09-08 17:31 UTC, Hdt80bro commented on lua/formations.lua
> +---@param formationUnits Unit
`Unit[]`

2022-09-08 17:31 UTC, Hdt80bro commented on lua/formations.lua
> +---@param formationUnits Unit
`Unit[]`

2022-09-08 17:32 UTC, Hdt80bro commented on lua/formations.lua
> +---@param formationUnits Unit
`Unit[]`

2022-09-08 17:32 UTC, Hdt80bro commented on lua/formations.lua
> +---@param formationUnits Unit
`Unit[]`

2022-09-08 17:34 UTC, Hdt80bro commented on lua/formations.lua
> +---@param unitsList Unit[]
This (and anything called `unitsList`) is the `table` we don't have a type for

2022-09-08 17:35 UTC, Hdt80bro commented on lua/formations.lua
> +---@param unitsList Unit[]
`table` as well

2022-09-08 17:35 UTC, Hdt80bro commented on lua/formations.lua
> +---@param unitsList Unit[]
`table`

2022-09-08 17:35 UTC, Hdt80bro commented on lua/formations.lua
> +---@param unitsList Unit[]
`table`

2022-09-08 17:35 UTC, Hdt80bro commented on lua/formations.lua
> +---@param unitsList Unit[]
`table`

2022-09-08 17:35 UTC, Hdt80bro commented on lua/formations.lua
> +---@return any
`table`

2022-09-08 17:36 UTC, Hdt80bro commented on lua/formations.lua
> +---@param formationUnits Unit
`Unit[]`

2022-09-13 07:54 UTC, merged