Successive upgrades in hotbuild via keybind
FAForever/fa pull request #4219
Opened 2022-09-14 11:51 UTC by ChessBerry

Hello everyone, 

this PR is a proposed feature addition to hotbuild, namely being able to queue successive upgrades using the upgrade keybind, instead of having to use a mouse click.

Upgrading e.g. a T1 factory to T3 in one go previously required a mouse click to queue the upgrade to T3, if the upgrade to T2 was not finished. 
Now, pressing the upgrade hotkey on your keyboard a second time does queue the upgrade to T3, regardless of if the T2 upgrade is finished or not.

I tested it with factories, radars and sonars of different factions, and even with adding units into a factory queue between the T2 and T3 upgrade and it seems to work as intended.

TODO: I don't know how to adjust the icon in the command card so that it shows the correct keybind as, right now, the T3 upgrade doesn't show a keybind at all if the T2 upgrade is queued but not finished yet.

Tell me what you think :)

2022-09-14 12:12 UTC, Garanas commented
Looks like a good quality of life change. What is the behavior that you describe in the TODO? I don't entirely understand what it means / what you're trying to achieve. A screenshot can help.

2022-09-14 12:34 UTC, ChessBerry commented
Let's say I have hotbuild-upgrade bound to M and I select a T1 factory. I will see the following in my command card (or whatever it's called):
![Forged Alliance 14_09_2022 14_23_30 (2)](https://user-images.githubusercontent.com/90977374/190153421-2912bb9e-77f4-4928-a452-234e3bc4fb2f.png)
(Ignore the keybinds for all the other units)

If I now queue the upgrade to a T2 HQ, I will get access to the T2 build suite for unit queueing purposes, but notice that there is no keybind for the upgrade to the T3 HQ on the T3 HQ icon:
![Forged Alliance 14_09_2022 14_23_40 (2)](https://user-images.githubusercontent.com/90977374/190154053-8aaa8382-1b1f-405e-932f-738b7b3232ce.png)

After the upgrade to T2 is done, the T3 icon _does_ get the appropriate keybind:
![Forged Alliance 14_09_2022 14_23_52 (2)](https://user-images.githubusercontent.com/90977374/190154169-392bdd42-7e28-4936-96ee-1d3402ebcaf3.png)

What is TODO is to give the icon in the intermediate step, when the T2 upgrade is queued but not finished, where I drew the red arrows, to correct keybind symbol, in this case the letter M. 
I don't know how to do that do as I haven't been able to find the appropriate place in the code governing these icon changes

2022-09-14 12:40 UTC, 4z0t commented
Afaik it looks what blueprints it can build and upgrade into in construction.lua (have a nice day looking through __this__ code...)

2022-09-18 16:12 UTC, ChessBerry commented
Took me a while, but I found where the hotbuild upgrade icons are set in gamemain.lua. The icons and successive upgrades should now work correctly, even for factories or unconventional structures, like the four times upgradeable cybran shield.

2022-09-19 07:22 UTC, Garanas commented
Exciting, not sure why that code is there. I'll look at this tonight, see if I can break it 😄

2022-09-19 08:32 UTC, ChessBerry commented
I phrased that a bit misleadingly: The icons themselves are not directly set in gamemain.lua, but the table that governs what is a valid upgrade target (according to hotbuild) is.

Also yes, please break it, there is for sure stuff I've overlooked that could be improved :P

2022-09-20 04:52 UTC, Garanas commented
It doesn't work for build mode, but I think I'm the only user of that. @Hdt80bro do you happen to use hotbuild, and if so can you review this?

2022-09-20 05:36 UTC, Hdt80bro commented
Sorry, I don't

2022-09-20 06:43 UTC, Garanas commented
@4z0t do you use hotbuild, if so can you review this?

2022-09-20 06:58 UTC, 4z0t commented
Yes, It works! Nice job!

2022-09-20 13:56 UTC, 4z0t requested changes

2022-09-20 13:56 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +        successiveUpgrades = upgradeTab[bp.BlueprintId] or {bp.General.UpgradesTo}
Did you want it to be `local` variable?

2022-09-20 13:56 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +function issueUpgradeCommand(upgrades, buildableCategories)
PascalCase

2022-09-20 13:56 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +    for _, upgr in upgrades do
Dont short names

2022-09-20 15:01 UTC, ChessBerry commented on lua/keymap/hotbuild.lua
> +    for _, upgr in upgrades do
So,
```
for _, u in upgrades do
```
would be better?

2022-09-20 15:04 UTC, ChessBerry commented on lua/keymap/hotbuild.lua
> +        successiveUpgrades = upgradeTab[bp.BlueprintId] or {bp.General.UpgradesTo}
yes, there is no reason for successiveUpgrades to be global

2022-09-20 15:06 UTC, ChessBerry commented on lua/keymap/hotbuild.lua
> +function issueUpgradeCommand(upgrades, buildableCategories)
PascalCase for the issueUpgradeCommand function? All other functions in hotbuild.lua are camelCase though. Is the new, proper style guide to make all new functions PascalCase?

2022-09-20 19:42 UTC, Garanas commented on lua/keymap/hotbuild.lua
> +function issueUpgradeCommand(upgrades, buildableCategories)
Yes - we're trying to get a standard going. New content should use pascal case.

2022-09-21 06:21 UTC, Hdt80bro commented on lua/keymap/hotbuild.lua
> +    for _, upgr in upgrades do
It's a matter of style--the specific tradition 4z0t is referring to is one that uses one-letter variable names for loop iterators.  That's fine when you don't have lots of nested loops like you have here, but when there are--or when the variable does lots of heavy lifting--I prefer to see it spelled out completely (unless that creates a variable that has only a one-letter *difference* from another variable [e.g. `upgrade` and `upgrades`]). Abbreviations in general are fine. We don't actually a unifying standard on variable names, so pretty much whatever you do (within reason) is fine.

2022-09-21 15:51 UTC, ChessBerry commented on lua/keymap/hotbuild.lua
> +    for _, upgr in upgrades do
I changed 'upgr' to 'u' as mentioned above

2022-09-21 18:34 UTC, Garanas approved these changes

2022-09-23 21:25 UTC, ChessBerry commented
Anything still missing that's preventing a merge? 

If I understand correctly, I implemented the last requested change in 7a4c18c above

2022-09-24 02:04 UTC, 4z0t approved these changes

2022-09-24 15:11 UTC, Garanas commented
Yeah, I was discussing this in Zulip. Github doesn't understand when the requested changes are applied, hence we need 4z0t to do another review.

2022-09-24 15:11 UTC, merged