FAF UI Framework Part 2
FAForever/fa pull request #4288
Opened 2022-10-23 13:33 UTC by 4z0t

* Dict

2022-10-23 13:40 UTC, Garanas commented
Is this a dictionary?

2022-10-23 13:41 UTC, 4z0t commented
Yes, it is.

2022-10-23 13:48 UTC, 4z0t commented
Well, I can allow wrapping table, so, there wont be allocations, but wrapper

2022-10-23 14:03 UTC, Garanas commented
No - the reason I was asking is because it should then just be called a `Dictionary`, instead of `Dict`

2022-10-24 21:22 UTC, Hdt80bro requested changes
Couple of renaming & logical considerations, but the biggest thing is with use in synchronization code: if keys are allowed to be of any type, iteration order depends on a value's hash which can different for players for functions, tables, and userdata. So either limit keys to be strings (which are internalized by Lua and hash consistently) and booleans/numbers (which inherently have well-defined hashes) or document a warning and hope the user understands the risks (which is usually a forlorn one).

2022-10-24 21:22 UTC, Hdt80bro commented on lua/shared/Containers/Dict.lua
> +        end
```lua
local d = {}
self._data = d
if data then
    for ...
end
```
Personal preference :) -- this would be slightly faster for calls that provide `data` and slightly, slightly slower for calls that don't.

2022-10-24 21:22 UTC, Hdt80bro commented on lua/shared/Containers/Dict.lua
> +    Next = next,
If this is expected to be general-purpose, it should also be used in the library methods.

2022-10-24 21:29 UTC, 4z0t commented
@Hdt80bro well, as was mentioned before and had been pointed out, `Containers` are primarily created for UI, not for sim.

2022-10-24 21:40 UTC, 4z0t commented
In first part there is [README](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/UI-Framework/README.md)

2022-10-25 07:40 UTC, Hdt80bro commented
I'd recommend completing that first then and resolving the rest of the problems--I'd also recommend a general restructuring. I'd also advise not separating documentation from what it's documenting (especially across directories), or at least pointing readers of the code to the readme. Comments are invaluable.

2022-11-10 10:43 UTC, 4z0t commented
By @Hdt80bro 's concerns I decided to put these classes only as part of UI for now. It is UI Framework for obvious reasons. 🙂

2023-04-12 19:31 UTC, closed without merging