Base manager cleanup
FAForever/fa pull request #4306
Opened 2022-10-28 11:03 UTC by 4z0t

2022-10-28 12:55 UTC, Garanas commented
This appears to be just formatting, is that correct?

2022-10-28 12:59 UTC, 4z0t commented
Annotations, some logic fixes

2022-10-28 13:00 UTC, Garanas commented
Could you pinpoint the logic fixes?

2022-10-28 14:00 UTC, Garanas approved these changes

2022-10-28 19:02 UTC, Garanas commented
@4z0t what if we merge these in, before you make more changes? Further changes are then part of another pull request

2022-10-28 19:06 UTC, 4z0t commented
Is there a rush? If it is too necessary then ofc merge, but there are no that many changes. I'm a bit confused about fa-coop repo, that I can't change now 😔

2022-10-28 19:13 UTC, Garanas commented
The fa-coop repo is in my opinion one giant mistake 😄 

The only reason it should exist is to adjust the balance, but that is about it. All the other logic should at some point be transferred to this repository as it is only confusing and less trivial to make a release.

2022-10-28 19:13 UTC, Garanas commented
And there is no rush, but I prefer small pull requests over large ones. And this one is starting to become large

2022-10-28 19:14 UTC, 4z0t commented
Just imagine Advanced Scenario Framework PR for coop :)

2022-10-28 19:17 UTC, Garanas commented
I'd prefer if you'd make the PR for the base repository 😄

2022-11-03 07:18 UTC, 4z0t commented
What happened?

2022-11-03 11:52 UTC, Garanas commented on lua/AI/OpAI/BaseManager.lua
> +            brain:PBMRemoveBuildLocation(nil, "MAIN") -- remove main since we don't use it in ops much
Is this technically the same?

2022-11-03 11:54 UTC, Garanas commented on lua/AI/OpAI/BaseManager.lua
> +    end;
There's a `;` instead of a `,` , what is the idea of that?

2022-11-03 11:55 UTC, Garanas commented
It appears to be primarily formatting. Are there any functional changes too?

2022-11-03 14:47 UTC, speed2CZ requested changes
Overall I can't really approve of these changes. It's called cleanup but it makes everything much less readable. Trying to optimize a lot of things that runs usually just once.
On top of that some logic changes that were surely not tested. I've caught a couple of those but I wouldn't be surprised if there were more.

Then there are some weird changes to formatting, like replacing ' ' with " ", why?
; instead of ,

My doubt of how much the individual things were tested were reinforced further by the fact that the whole base manager is just broken.

2022-11-03 14:47 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +        return self:ConstructionAlwaysAssist() or self:GetConstructionEngineerCount() == 0
Not only this change makes this condition less readable, you also managed to change the logic of it so it's broken now.

2022-11-03 14:47 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +                continue
No more code is executed after `error`

2022-11-03 14:47 UTC, speed2CZ commented on lua/AI/OpAI/BaseManager.lua
> +        return a.Priority < b.Priority
This sorts the group from lowest to highest priority, changing the original logic, which was from highest to lowest.

2022-11-03 15:05 UTC, xXEddieXxx commented on lua/AI/OpAI/BaseManager.lua
> +            brain:PBMRemoveBuildLocation(nil, "MAIN") -- remove main since we don't use it in ops much
Less readable for me, i found not much of a difference in conditions. http://lua-users.org/wiki/ExpressionsTutorial

2022-11-03 23:54 UTC, Hdt80bro commented on lua/AI/OpAI/BaseManager.lua
> +                continue
This is not always the case, like how `pcall` doesn't always catch errors

2022-11-04 00:12 UTC, Hdt80bro commented on lua/AI/OpAI/BaseManager.lua
> +        return self:ConstructionAlwaysAssist() or self:GetConstructionEngineerCount() == 0
Mmh, good catch, should be `self:ConstructionAlwaysAssist() and self:GetConstructionEngineerCount() ~= 0`
Again, I disagree about the readability, especially when the returns are as inconsistent as this file.

2022-11-04 00:15 UTC, Hdt80bro commented
> It's called cleanup but it makes everything much less readable

It's interesting that you say that; to me, it was horrendous before and much better now. Looks like this is a good trial run of the new (code style contributions)[https://github.com/FAForever/fa/pull/4318] I'm writing - I'm excited to hear your thoughts.

Of course, a few things were focused on optimization that weren't mean to increase readability (like the caricature that was `LoadDefaultBaseEngineers` that I reduced by 468 table creations)--it's all clean up though.

You're right that I didn't test it as much as I should have, though I'm not sure that pointing out that I likely couldn't have to begin with makes that worse. I'll take a look again tonight to make sure it's logically consistent - alternatively, I can remove most of those changes if we don't want to deal with that right now or just revert the commit.

2022-11-05 21:05 UTC, Hdt80bro commented
I'll let this be 4z0t's PR; we can address the other concerns in the future.

2022-11-09 21:03 UTC, Hdt80bro commented
I don't agree with all of the formatting, but overall it's an improvement, so I'll merge this

2022-11-09 21:14 UTC, merged