Minor changes & code annotation work
FAForever/fa pull request #4317
Opened 2022-10-31 21:49 UTC by MrRowey

- `sim\weapon.lua`
- `spreadattack.lua`
- `terranprojectiles.lua`
- `terranunits.lua`
- `TriggerManager.lua`
- `victory.lua`
- `weather.lua`

2022-11-01 06:59 UTC, Garanas commented on lua/sim/weapon.lua
> +        if not self.PlaySound[sound] then return end
I'm not sure if this is correct, PlaySound is a c function and not a table look up.

2022-11-01 07:00 UTC, Garanas commented on lua/weather.lua
> -function CreateWeather()
Why is all of this removed?

2022-11-01 07:01 UTC, Garanas commented on lua/weather.lua
> -function CreateWeather()
oh, I see now. It got placed at the bottom 😄

2022-11-01 07:02 UTC, Garanas reviewed
Overall seems fine, except for the changes to `weapon.lua`

2022-11-01 07:54 UTC, MrRowey commented on lua/sim/weapon.lua
> +        if not self.PlaySound[sound] then return end
@Hdt80bro thoughs?

2022-11-01 11:56 UTC, Garanas commented on lua/sim/weapon.lua
> +        if not self.PlaySound[sound] then return end
Missed this one

2022-11-01 11:56 UTC, Garanas commented on lua/sim/DefaultProjectiles.lua
> +--- Lightweight Version That Limits Use To 1 Beam, polytrail and standard emitters
That looks better 😄

2022-11-01 11:57 UTC, Garanas reviewed
Everything else seems fine to me. @Hdt80bro could you review / merge as you see fit?

2022-11-04 08:38 UTC, Garanas commented
@MrRowey can you find the time to fix the conflicts? We've decided to lower case all imports.

2022-11-04 19:20 UTC, MrRowey commented
@Garanas that should be fixed ?

2022-11-09 20:09 UTC, Hdt80bro requested changes
Good work!

2022-11-09 20:09 UTC, Hdt80bro commented on lua/terranunits.lua
> +    ---@param layer string
`layer` can be `Layer`

2022-11-09 20:09 UTC, Hdt80bro commented on lua/terranunits.lua
> +    ---@param captor any
`captor` can be `Unit`

2022-11-09 20:09 UTC, Hdt80bro commented on lua/terranunits.lua
> +    ---@return unknown
Returns a `Unit`

2022-11-09 20:09 UTC, Hdt80bro commented on lua/terranunits.lua
> +    ---@param attachee any
`attachee` can be `Unit`

2022-11-09 20:09 UTC, Hdt80bro commented on lua/terranunits.lua
> +    ---@param attachee any
same also

2022-11-09 20:09 UTC, Hdt80bro commented on lua/terranweapons.lua
> +    ---@return Projectile | nil
In general, whenever `nil` isn't explicitly returned, lets use `@return type?` instead of `@return type | nil` to indicate that absence (there's a few places like that in here)

2022-11-09 20:09 UTC, Hdt80bro commented on lua/terranweapons.lua
> +    ---@param muzzle string
Turns out that muzzles are just `Bone`s

2022-11-09 20:09 UTC, Hdt80bro commented on lua/terranweapons.lua
> +    ---@param muzzle string
same, `Bone`

2022-11-09 20:26 UTC, Hdt80bro commented on lua/terranweapons.lua
> +    ---@return Projectile | nil
Actually, it looks reason you're adding this in the first place is that `Unit:CreateProjectile` is missing an annotated return type, so that should be added instead of this changing

2022-11-19 22:26 UTC, Hdt80bro approved these changes

2022-11-19 22:31 UTC, merged