More annotations / code changes
FAForever/fa pull request #4320
Opened 2022-11-01 13:42 UTC by MrRowey

Filles that have been affected in this PR
- `effects/Entities/SCUDeath01/SCUDeath01_script.lua` = File Tidy-up & Replaced Deprecated code
- `lua/aeonprojectiles.lua` = Some Commenting changes
- `lua/aeonweapons.lua` = Some Annotations work
- `lua/aibrain.lua` = added missing annotations & some commenting  rework
- `lua/editor/AMPlatoonHelperFunctions.lua` = Move functions around so functions could see each other
- `lua/editor/EconomyBuildConditions.lua` = move import to bottom of page
- `lua/sim/EngineerManager.lua` = Some annotation and code work
- `lua/ui/campaign/campaignmanager.lua` = commenting rework
- `lua/ui/campaign/campaignmovies.lua` = commenting rework
- `lua/ui/campaign/operationvars.lua` = commenting rework
- `lua/user/tasks/Tasks.lua` = Move functions around so functions could see each other

2022-11-09 21:22 UTC, Hdt80bro requested changes
Nice work!

2022-11-09 21:22 UTC, Hdt80bro commented on lua/sim/EngineerManager.lua
> +    ---@return boolean | number
Similar comments with how booleans are used for signalling for the next several methods; `@return number | true`

2022-11-09 21:22 UTC, Hdt80bro commented on lua/sim/EngineerManager.lua
> +    ---@param finishedUnit Unit|UserUnit
`EntityCategoryContains` does work with both `Unit` and `UserUnit`, but each Lua state only uses one of them. In this case, engineer manager is in the sim, so it'll be `Unit`.

2022-12-02 21:32 UTC, Hdt80bro requested changes

2022-12-02 21:32 UTC, Hdt80bro commented on lua/aeonweapons.lua
>              return blip
This function always returns the Unit of the Blip (unless it doesn't have one), so the return type should be `@return Unit | false`. When I was talking about adding `--[[@as Unit]]`, that would have gone on the actual return on line 143 (not the annotation), like `return blip --[[@as Unit]]` in case an actual Unit got passed instead of a Blip (but it isn't necessary to add it). Come to think of it, this also means that the `blip` parameter should have the type `Blip | Unit` as well.

2022-12-02 21:32 UTC, Hdt80bro commented on lua/aeonweapons.lua
> +    ---@return Projectile | nil
This isn't `nil`, `CreateProjectile` just doesn't have the correct return type.

2022-12-02 21:32 UTC, Hdt80bro commented on lua/aeonweapons.lua
> +    ---@return Projectile | nil
^

2022-12-02 21:32 UTC, Hdt80bro commented on lua/aeonweapons.lua
> +    ---@return Projectile | nil
^

2022-12-02 21:32 UTC, Hdt80bro commented on lua/aibrain.lua
> +    ---@param platoon Unit
It looks like this is actually a type we haven't named yet (set up around lines 2269-2297). Leave as `any` for now.

2022-12-02 21:32 UTC, Hdt80bro commented on lua/sim/EngineerManager.lua
> +    ---@return boolean | number
`@return number | true`

2022-12-02 21:32 UTC, Hdt80bro commented on lua/sim/EngineerManager.lua
> +    ---@return boolean | number
^

2022-12-02 21:32 UTC, Hdt80bro commented on lua/user/tasks/Tasks.lua
> -function GetUnitsScript(TaskName, SelectedUnits, data)
I discourage moving functions around like this since it breaks up the logical flow of the file, even though it "creates" error in the extension--that is a problem with the extension, not the code.

2022-12-04 21:56 UTC, MrRowey commented
@Hdt80bro ill get to these when i can :) got 2 week before i break up for Christmas so will look at them then :)

2022-12-11 18:08 UTC, MrRowey commented
@Hdt80bro this one should be done now

2022-12-16 22:25 UTC, Hdt80bro approved these changes

2022-12-16 22:25 UTC, merged