Changes some using files to prevent Intellisense popups
FAForever/fa pull request #4322
Opened 2022-11-01 18:38 UTC by MrRowey

2022-11-01 20:16 UTC, Garanas commented on units/DAA0206/DAA0206_script.lua
> -local EffectUtils = import('/lua/effectutilities.lua')
If they are unused it is better to put them at the bottom of the file

2022-11-01 20:17 UTC, Garanas commented on units/DSLK004/DSLK004_script.lua
> -local CollisionBeam = import('/lua/sim/CollisionBeam.lua').CollisionBeam
Is this a safe change on its own?

2022-11-01 20:18 UTC, Garanas commented on units/UAL0001/UAL0001_script.lua
> -            self:SetProductionPerSecondEnergy(bp.ProductionPerSecondEnergy + bpEcon.ProductionPerSecondEnergy or 0)
This change isn't logically the same, what am I missing that the extension would suggest this?

2022-11-01 20:48 UTC, MrRowey commented on units/DSLK004/DSLK004_script.lua
> -local CollisionBeam = import('/lua/sim/CollisionBeam.lua').CollisionBeam
The Variable is not even being called in this particular file. by renaming removed the Intellisense saying that it uses else where under a different name

2022-11-01 20:50 UTC, MrRowey commented on units/UAL0001/UAL0001_script.lua
> -            self:SetProductionPerSecondEnergy(bp.ProductionPerSecondEnergy + bpEcon.ProductionPerSecondEnergy or 0)
Logically it is ? I've done this one before and hdt said it was fine as your doing the bp calculation together first or it = 0 ? or am i miss interrupting how this should be working as the Intellisense is happy once i did this.

2022-11-01 20:52 UTC, MrRowey commented on units/UAS0401/UAS0401_script.lua
> -local CreateAeonTempestBuildingEffects = import("/lua/effectutilities.lua").CreateAeonTempestBuildingEffects
xD then we need to change that file name then as this is a common error that the Intellisense though with the file name being "different"

2022-11-02 08:32 UTC, Garanas commented on units/UAS0401/UAS0401_script.lua
> -local CreateAeonTempestBuildingEffects = import("/lua/effectutilities.lua").CreateAeonTempestBuildingEffects
Ah, gotcha. Maybe we can adjust the plugin instead to always recommend lower path import strings. @hahn-kev would that be possible?

2022-11-02 08:47 UTC, MrRowey commented on units/UAS0401/UAS0401_script.lua
> -local CreateAeonTempestBuildingEffects = import("/lua/effectutilities.lua").CreateAeonTempestBuildingEffects
this can be both either it says the FileName is diffrent or that the Import itself is diffrent EG `explosion` in one and then `Explosion` in another file all thats diffrent is the capital

2022-11-10 05:39 UTC, Hdt80bro requested changes

2022-11-10 05:39 UTC, Hdt80bro commented on units/URA0107/URA0107_Script.lua
>  local explosion = import("/lua/defaultexplosions.lua")
I'm not sure leaving both in here is necessary for a file this small. Of course, it'd be the safer thing to do, but at that point you might as well not rename it I think.

2022-11-10 05:45 UTC, Hdt80bro commented on units/DSLK004/DSLK004_script.lua
> -local CollisionBeam = import('/lua/sim/CollisionBeam.lua').CollisionBeam
I think that was due to the filename having different capitalization in different files, which is incidentally something we just fixed. I don't see the intellisense error, so I don't think renaming this is necessary.

2022-12-02 21:42 UTC, Hdt80bro requested changes

2022-12-02 21:42 UTC, Hdt80bro commented on units/UAL0401/UAL0401_Script.lua
> +local Utilities = import("/lua/utilities.lua")
If you rename it from lowercase, it doesn't keep any compatibility <--  check the spelling on the word too ;)
Likewise, perhaps we need `local explosion = Explosion` down here too (and something similar in the rest of the files we rename as well).

2022-12-16 22:44 UTC, Hdt80bro approved these changes
Looking good! @Garanas does renaming import modules (e.g. `explosion` t o`Explosion`) cause compatibility concerns?

2022-12-29 21:57 UTC, MrRowey commented
@Hdt80bro anything i need to do here to get this finalised ?

2022-12-29 22:28 UTC, Garanas commented
I see I got pinged. Renaming is a compatibility issue, unless the file is not used by any of the most common mods.

2022-12-29 22:47 UTC, MrRowey commented
@Hdt80bro @Garanas revert the import renaming so this should be all good to merge

2023-01-24 20:30 UTC, merged