Initial draft of the changelog
FAForever/fa pull request #4333
Opened 2022-11-04 21:12 UTC by Garanas

2022-11-04 21:28 UTC, Sheikah45 commented on changelog-dev.md
> +    with the limitated player base size.
This still only counts alive players right? If it does then this explanation does not make it clear.

2022-11-04 21:40 UTC, 4z0t requested changes

2022-11-04 21:40 UTC, 4z0t commented on changelog-dev.md
> +    Air units are now distroyed as soon as they reach the claw
*destroyed*

2022-11-04 21:40 UTC, 4z0t commented on changelog-dev.md
> +Jip (#4119, #4124#4188, #4190, #4191, #4212, #4205, #4232, #4241, #4243, #4244, #4248, #4250, #4253, #4260, #4254, #4262, #4249, #4025, #4267, #4266, #4264, #4281, #4270, #4282, #4285, #4286, #4292,
split these

2022-11-04 21:54 UTC, Garanas commented on changelog-dev.md
> +    with the limitated player base size.
Yes, I'll add that bit in.

2022-11-04 21:54 UTC, Garanas commented on changelog-dev.md
> +Jip (#4119, #4124#4188, #4190, #4191, #4212, #4205, #4232, #4241, #4243, #4244, #4248, #4250, #4253, #4260, #4254, #4262, #4249, #4025, #4267, #4266, #4264, #4281, #4270, #4282, #4285, #4286, #4292,
Yes, they will be once the changelog is finished.

2022-11-05 00:55 UTC, FemtoZetta commented on changelog-dev.md
> +    the leafs of the quad tree to create a graph. This graph is initially used for just path finding,
path finding -> pathfinding

2022-11-05 00:56 UTC, FemtoZetta commented on changelog-dev.md
> +    algorithm computes the answer. The algorithm needs to be simple, yet efficient as there
algorithm computes the answer -> algorithm that computes the answer

2022-11-05 00:56 UTC, FemtoZetta commented on changelog-dev.md
> +    is essentially no budged to perform computationally expensive algorithms.
budged -> budget

2022-11-06 11:47 UTC, MrRowey commented on changelog-dev.md
> +one of its dozen features is incompatible:the command feedback no longer riggers with Economy
I'm assuming you meant triggers not riggers

2022-11-06 11:47 UTC, MrRowey commented on changelog-dev.md
> +-- as per #4232 the reclaim view is completely overhauled
@Garanas Did you look at Rheclaim as that the Reclaim overlay i use

2022-11-06 11:55 UTC, Garanas commented on changelog-dev.md
> +-- as per #4232 the reclaim view is completely overhauled
Not compatible, added to the incompatible list

2022-11-06 12:05 UTC, merged

2022-11-06 12:22 UTC, Deribus commented on changelog-dev.md
> +    No more teleporting Cybran ACU with a laser attached to its chest.
hmm?

2022-11-06 12:22 UTC, Deribus commented on changelog-dev.md
> +Note that mods like Quality of Performance are no longer required - they barely have impact on the
I feel like this is the FAF version of "removed Herobrine"

2022-11-06 12:24 UTC, Garanas commented on changelog-dev.md
> +    No more teleporting Cybran ACU with a laser attached to its chest.
Good catch, it is supposed to be cloak

2022-11-06 13:54 UTC, Prohibitoram reviewed
A few typo's and remarks regarding punctuation. Rest is mostly a difference in writing style, so change as you see fit.

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +the same time make the game easier to customize to your liking. Some of the patch can be
...Some [elements of] the patch...

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +immediately visible but are a major step forward, like the navigational mesh we generate for
...like the AI's navigational mesh we generate for the map you're playing on.

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +Previous patches primarily made changes in the code directly related to the simulation. This
Points for alliteration, but we can do better!

Previous patches primarily pertained to processes particularly pertinent to the simulation of pieces and projectiles.

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +patch also includes changes to the code surrounding the user interface. Also refers to UI
...includes changes to the user interface, the relevant UI code, and UI mods. Consequently, this patch results in some incompatibility with existing UI mods.

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +add in a single feature, then it is to have one large UI mod that adds in many features. One
"...a single feature, then it is..."
, than

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +example is Economy Manager - a mod often used by players - is no longer compatible because
Use the proper Em-dashes, not these weak dashes:

..."example is Economy Manager—a mod often used by players—is no longer compatible because..."

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +one of its dozen features is incompatible:the command feedback no longer triggers with Economy
"...features is incompatible: the command"

space after punctuation!

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +And as this year ends I'd like to show my personal appreciation to some contributors and community
"As this year ends"

We don't start sentences with "and".

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +ready to help confirm the stability of it. And of course there is Rowey - always ready to assist
No really, we got specific dashes for specific uses. This is where we use an Em-dash. No spaces around the dash either!

"...there is Rowey—always ready..."

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +of this game, like being there when we were producing the game development series. a lot of the videos
"...development series. A lot..."

Capitalize new sentence.

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +on game development. And last I'd like to thank Sprouto - creator of the LOUD community - for being an
"A lot of the videos on game development"... what? We're missing part of a sentence I think?

Also more Em-dashes here.

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +And like that, a new year of development will start. And with a new year we'll take a new route
See previous point about starting parapgraphs with "and", but add extra minus points if the second sentence of that paragraph sentence also starts with "and".

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +to how we'll further develop this game. Instead of having a 'game team' - that introduces an arbitrary
"Instead of just having a 'game team'—needlessly introducing an arbitrary boundary between different type of contributors—we'll move towards a more open format of organization by creating a clear, properly scoped backlog of issues that contributors can pick up."

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +properly scoped backlog of issues that contributors can pick up. Anyone can add and discuss issues in
"Anyone will be able to add and discuss issues in this database"

Is it really a backlog if you're keeping track of active projects?

2022-11-06 13:54 UTC, Prohibitoram commented on changelog.md
> +towards a common vision. They make it immediately clear when you can expect your changes to be live.  Alas -
"Alas, there's too much"

Em-dashes are really cool, but sometimes a simple comma is just better.

2022-11-06 15:50 UTC, Prohibitoram reviewed
Saw some typos when actually reading the changelog and that just won't do. (jk jk thanks for massive update very cool)

2022-11-06 15:50 UTC, Prohibitoram commented on changelog.md
> +    Adds in a recall feature. Similar to a the 'concede' feature that other games provide,
"...to a the 'concede' feature..."

remove "the"

2022-11-06 15:50 UTC, Prohibitoram commented on changelog.md
> +    are with two or less alive players it requires all alive players of the same team to
"...with two or less alive players..."

Replace less with fewer.

2022-11-06 15:50 UTC, Prohibitoram commented on changelog.md
> +    with the limitated player base size.
"...with the limitated player base..."

Type: limited

2022-11-06 15:50 UTC, Prohibitoram commented on changelog.md
> +    textures / assets of units and acts as an inspiration to the shader implementation.
no spaces around interpunction

"...textures/assets of units"

2022-11-06 15:50 UTC, Prohibitoram commented on changelog.md
> +- (#4131) Introduced of shared armies
"Introduced of shared..."

Introduction

2022-11-06 15:50 UTC, Prohibitoram commented on changelog.md
> +- (#4254) Improve text markers
Improved

2022-11-06 15:50 UTC, Prohibitoram commented on changelog.md
> +    When you create a text marker it is also send to the chat with camera coordinates
"when you create a text marker, it is also..."