feat: Add new Keybind option "Select all navy, without mobilesonar"/ make the original beavior consistent #4459
FAForever/fa pull request #4463
Opened 2022-11-30 12:53 UTC by xXEddieXxx

## Description of the changes
I added a new Keybind option :"select_naval_no_sonar". 
It selects all navy units except sonar platforms (Ships with sonar trait still get selected, mabye the naming needs to be refactored).

I also changed the t2 seraphim sonar platform that actually was not selected when the select Navy keybind was used.(in contrast to all other mobile sonars)
It is now consisten with all sonarplatfroms that when u select all navy they also get selected. 

## Test setup for the changes
Spawn in as many navy units and sonarplatforms as you like and try the new Keybindoption. 

## Additional context
If there is anything off with description or naming just tell me i will change it :)

2022-11-30 21:15 UTC, 4z0t commented
> @4z0t is there no way to subtract categories using the console command `UI_SelectByCategory`?

@Garanas no, only union and intersection.

2022-12-01 08:39 UTC, Garanas approved these changes

2022-12-01 08:39 UTC, Garanas commented on lua/keymap/keydescriptions.lua
> +    ['select_naval_no_sonar'] = 'Select all Naval units except Sonarplatforms',
Is 'Sonarplatforms' one word?

2022-12-01 12:49 UTC, xXEddieXxx commented on lua/keymap/keydescriptions.lua
> +    ['select_naval_no_sonar'] = 'Select all Naval units except Sonarplatforms',
I will check it after work and change it acordingly. :D

2022-12-01 15:17 UTC, 4z0t requested changes

2022-12-01 15:17 UTC, 4z0t commented on lua/keymap/misckeyactions.lua
> +    UISelectionByCategory("NAVAL + MOBILE", false, false, false, false) SelectUnits(EntityCategoryFilterDown(categories.ALLUNITS - categories.MOBILESONAR, GetSelectedUnits()))
This plus doesn't do anything actually, remove it to not confuse anyone.

2022-12-01 16:36 UTC, xXEddieXxx commented on lua/keymap/misckeyactions.lua
> +    UISelectionByCategory("NAVAL + MOBILE", false, false, false, false) SelectUnits(EntityCategoryFilterDown(categories.ALLUNITS - categories.MOBILESONAR, GetSelectedUnits()))
Can you explain ?

2022-12-01 17:35 UTC, Garanas commented on lua/keymap/misckeyactions.lua
> +    UISelectionByCategory("NAVAL + MOBILE", false, false, false, false) SelectUnits(EntityCategoryFilterDown(categories.ALLUNITS - categories.MOBILESONAR, GetSelectedUnits()))
There's no need to cache this. The code path is not critical.

@xXEddieXxx this is caching of catories:
- https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/defaultunits.lua#L25-L27

It prevents re-computing the categories arithmetic's. Those arithmetic's are engine calls and are therefore expensive. Caching the computation is useful when you're dealing with critical paths (paths that are run so often that you want to get everything out of it that you can possibly get, performance-wise)

2022-12-01 17:35 UTC, Garanas commented on lua/keymap/misckeyactions.lua
> +    UISelectionByCategory("NAVAL + MOBILE", false, false, false, false) SelectUnits(EntityCategoryFilterDown(categories.ALLUNITS - categories.MOBILESONAR, GetSelectedUnits()))
If you happen to run into it - yes. But don't go looking for it 😄 !

2022-12-02 08:33 UTC, xXEddieXxx commented on lua/keymap/misckeyactions.lua
> +    UISelectionByCategory("NAVAL + MOBILE", false, false, false, false) SelectUnits(EntityCategoryFilterDown(categories.ALLUNITS - categories.MOBILESONAR, GetSelectedUnits()))
Love that sentence ! xD

2022-12-02 08:43 UTC, Garanas commented on lua/keymap/keydescriptions.lua
> +    ['select_naval_no_sonar'] = 'Select all Naval units except Sonarplatforms',
![image](https://user-images.githubusercontent.com/15778155/205252184-bcc5e5ff-a6d7-4fe5-9ac5-ceb413a76144.png)

I think it is two separate words. Could you adjust that? After that we can merge.

2022-12-02 11:02 UTC, xXEddieXxx commented
ok about my last PR i investigated a little bit more and found, that someone wrote a smart select(wich is used rarely), wich gives you the opportunity to use a Keybind and give it string attriubutes also substraction as you mentioned @Garanas. 
So i deleted my own function and used this instead, i dont know if this is better but it looked nicer to me then having a special function for each Keybind, that are all doing the same.(like my navalnosonar function or the Airnotransport function)
I would like your thoughts about this aswell @4z0t the function looked pretty old can this be used ?

2022-12-04 09:56 UTC, Garanas commented
I'm not a huge fan of smart selection because of the manual parsing. But for the sake of a hotkey - it is fine 😃

2022-12-04 09:56 UTC, Garanas approved these changes

2022-12-04 09:56 UTC, merged