Introduce mission briefings to the lobby
FAForever/fa pull request #4490
Opened 2022-12-11 12:03 UTC by speed2CZ

Briefing button shows up if the selected map has valid briefing data.
The button takes priority over patch notes button.

New UI screen with the briefing is created over the lobby.

Briefing screen can still be accessed via original Campaign selection.
Launch button is disabled there as it's unstable to launch the original missions with FAF changes.

Requires https://github.com/FAForever/faf-coop-maps/pull/394

Will also require the coop patch with the missing videos and voices.

2022-12-11 14:27 UTC, Garanas commented
Never seen the non-forged alliance campaign logs, quite exciting 😄 

It appears the background sound can't be found:
```lua
WARNING: Error resolving bank 'Op_Briefing_Vanilla' to audio engine
WARNING: Error resolving bank 'Op_Briefing_Vanilla' to audio engine
WARNING: Error resolving bank 'Op_Briefing_Vanilla' to audio engine
WARNING: Error resolving bank 'Op_Briefing_Vanilla' to audio engine
```

2022-12-24 00:15 UTC, 4z0t commented
*Please* use Layouter! It is impossible to read that whole UI code.

2022-12-24 00:17 UTC, 4z0t requested changes

2022-12-24 00:17 UTC, 4z0t commented on lua/ui/campaign/operationbriefing.lua
> +    end
Use Layouter.

2022-12-24 00:29 UTC, 4z0t requested changes

2022-12-24 00:29 UTC, 4z0t commented on lua/ui/lobby/lobby.lua
> +    end
Make a separate class that shows mission briefing.

2022-12-24 08:48 UTC, Garanas commented on lua/ui/campaign/operationbriefing.lua
> +    end
I think this code is copied from the base game, no need to refactor it if it works right 😄

2022-12-29 12:42 UTC, speed2CZ commented on lua/ui/lobby/lobby.lua
> +    end
I dont know what you mean by a new class

2022-12-29 12:44 UTC, speed2CZ commented on lua/ui/campaign/operationbriefing.lua
> +    end
I wont be converting it that. Its copy pasted code from the vanilla files, only merged into a single file to work for all styles at onces. As it was mostly the same code with some small faction differences.

It aint the most beatiful but it works. And I doubt anyone will touch it in the near future.

2023-01-24 21:43 UTC, speed2CZ commented
It's ready now. Updated description

2023-02-01 09:11 UTC, merged