Projectiles Fil Clean-up
FAForever/fa pull request #4517
Opened 2022-12-18 20:38 UTC by MrRowey

Clean Up of the projectile files removing unused commented code first

2022-12-19 19:45 UTC, Garanas commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> -        --LOG('Projectile impacted with: ' .. TargetType)
For this particular file, you can also refactor the VizMarker into VizMarkerOpti, you can search for examples. The opti version allocates as few tables as possible.

2022-12-19 19:55 UTC, Garanas reviewed
A lot more is possible then you're doing now. This particular sweep isn't so much about cleaning up the files, but also looking at the logic and wondering: do we really need this _here_?

For example: all the OnEnterWater functions create splash effects. If they all do this, why don't we do it in the base class for example?

A few other valid improvements:
- using the opti vision marker, located in the same file
- reducing table entries
- reducing engine calls (`self:GetArmy` -> `self.Army`, `self:GetBlueprint` -> `self.Blueprint` , `self:GetLauncher` -> `self.Launcher`)
- replace `WaitSeconds` with `WaitTicks`, but with corrected values (usually * 10, except for `WaitSeconds(0.1)` which is `WaitTicks(2)` , see also the definition of `WaitSeconds` in `simInit.lua`)
- and a lot more, if you closely look at the hierarchy.

And like that, a lot more is possible then you're doing right now. Not that what you're doing is bad, but it feels to me a lot more can be done.

2022-12-19 19:55 UTC, Garanas commented on projectiles/AANDepthCharge03/AANDepthCharge03_script.lua
> -        --LOG('Projectile impacted with: ' .. TargetType)
Same as the previous comment.

2022-12-19 19:55 UTC, Garanas commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> ---
One could also wonder what the practical value is of `EnterWaterMovementThread = function(self)` for this and similar projectiles, is it worth waiting 1 tick (which is - fun fact - the same tick, but at the very end) and create a separate thread for that all together?

It probably is not

2022-12-19 19:55 UTC, Garanas commented on projectiles/AANTorpedoCluster01/AANTorpedoCluster01_script.lua
> -        spec.Army = self.Army
Sounds like I touched this file before. But the same applies: you can refactor the vision marker into the opti version

2022-12-19 19:55 UTC, Garanas commented on projectiles/AANTorpedoClusterSplit01/AANTorpedoClusterSplit01_script.lua
> -
Same here, is the enter water movement thread _really_ doing anything? It doesn't even contain a wait statement!

2022-12-19 19:55 UTC, Garanas commented on projectiles/AIFFragmentationSensorShell02/AIFFragmentationSensorShell02_script.lua
> +
You can always replace `self:GetBlueprint()` with `self.Blueprint` for projectiles

2022-12-19 19:55 UTC, Garanas commented on projectiles/AIMFlare01/AIMFlare01_script.lua
> -        --self:SetCollisionShape('Sphere', 0, 0, 0, self:GetBlueprint().Physics.FlareRadius)
Same here (a few lines below) - you can factor out the `GetBlueprint`

2022-12-19 21:39 UTC, MrRowey commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> -        --LOG('Projectile impacted with: ' .. TargetType)
Ive searched for VisMarkerOpti and cant seem to see a Example is this somthing that in a upcoming pr ?

2022-12-20 20:44 UTC, Garanas commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> -        --LOG('Projectile impacted with: ' .. TargetType)
Yes, that seems about right 👍

2022-12-21 19:19 UTC, Garanas requested changes
The two conversations left need to be looked at before we can merge this.

2022-12-21 19:19 UTC, Garanas commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> +        self.ForkThread(self.CountdownExplosion)
This is not a safe change on its own - see also:
- https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Projectile.lua#L885-L893

You'll also need to add it to the trash bag

2022-12-21 19:19 UTC, Garanas commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> +            self.OnImpact('Underwater', nil)
There is no need to change this. Note that this change is also not logically equivalent. Please revert all changes of the same type (`:` -> `.`, back to `:`)

2022-12-21 21:45 UTC, MrRowey commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> +        self.ForkThread(self.CountdownExplosion)
I've just revert back to : from . for now 

I'm assuming the change would be something like

```lua
self.Trash:ForkThread(self.CountdownExplosion)
```

2022-12-22 07:22 UTC, Garanas commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> +        self.ForkThread(self.CountdownExplosion)
No, it would be:
-  `self.Trash:Add(ForkThread(self.CountdownExplosion, self))`

when you use `:` what actually happens is that the argument before `:` (which is `self` in this context) is appended as the first argument to whatever you're calling after the `:`

2022-12-23 18:02 UTC, Garanas approved these changes

2022-12-23 18:02 UTC, merged