Introduces function to determine allocated bytes for any value
FAForever/fa pull request #4523
Opened 2022-12-21 19:50 UTC by Garanas

This is useful to understand the impact of tables (or values in general) - a long missing factor in our hunt towards better performance. Looking forward to feedback on this function.

2022-12-24 00:09 UTC, 4z0t requested changes

2022-12-24 00:09 UTC, 4z0t commented on lua/sim/Unit.lua
> +    local seen = seen or { }
It is local already

2022-12-24 00:09 UTC, 4z0t commented on lua/sim/Unit.lua
> +        )
Test code.

2022-12-24 00:09 UTC, 4z0t commented on lua/sim/Unit.lua
> +end
Duplicate

2022-12-24 07:30 UTC, Garanas commented on lua/sim/Unit.lua
> +end
Test code too 😄

2022-12-24 07:30 UTC, Garanas commented on lua/sim/Unit.lua
> +    local seen = seen or { }
Parameters are, I'll adjust it

2022-12-24 10:04 UTC, Garanas commented
Fun fact with the navigational mesh, on the map `Syrtis Major` the entire datastructure takes up about 33 megabytes:

![image](https://user-images.githubusercontent.com/15778155/209430997-b6396285-c58b-4a8e-aed6-919b9dded3d4.png)

On Seton's Clutch this is about 48 megabytes. This means that the compression we do works quite well.

About 30% of the memory that we use originates from these lines:
- https://github.com/FAForever/fa/blob/feature/bytes-function/lua/sim/NavGenerator.lua#L652-L670

If we remove those lookup tables:
- Syrtis Major: 33mb -> 21mb
- Seton's Clutch: 48mb -> 30mb

Oof 😄

2022-12-24 10:40 UTC, merged

2022-12-24 13:38 UTC, KionX commented
This should exec only for tables: https://github.com/FAForever/fa/pull/4523/files#diff-b7cb9a852b1ea5bdbe28863255f535c0924f4446962075087db5bbe9a9b71314R54

2022-12-24 19:08 UTC, Garanas commented
As far as I can see it only executes that for tables a this moment

2022-12-24 19:34 UTC, KionX commented
if type(v) == 'table' then

2022-12-25 11:48 UTC, Garanas commented
I'm all up for an alternative if it is more accurate!

As far as I can tell, the recursion only applies to tables at the moment, unless you're making a distinction between the hash and array sections of a table.