Adds default repeat build option for factories
FAForever/fa pull request #4524
Opened 2022-12-22 19:11 UTC by haifron

Closes #4346

### New logic:
- When you first select a factory, it is toggled to repeat build if the option is enabled.
- This is controlled by `Options > Interface > Building > Factories Default Repeat Build`. It is `false` by default.

This implementation is smoother than the UI-Party implimentation since it doesn't require changing the user's selection to make the change. To achieve that I've made the assumption there's no way to give a queue to a factory before selecting it.

### Extra information / cheaper implementation
This implementation does loop through the entire selection to check for factories, which is already done in `"rallypoint.lua".OnSelectionChanged()` so it would be cheaper if just implemented there, but I didn't want to add it there initially since the functionality is totally irrelevant to `rallypoint.lua` so it feels a tad spaghetti-y. I would like to know what you guys think.

<details><summary>

##### if implemented in `rallypoint.lua` this just adds an `if` in a loop

</summary>

  ```
function OnSelectionChanged(selection)
     if not beatFunctionAdded then
         import("/lua/ui/game/gamemain.lua").AddBeatFunction(OnBeat)
         beatFunctionAdded = true
     end

     ClearAllRallyPoints()

     local factories = EntityCategoryFilterDown(categories.STRUCTURE * categories.FACTORY, selection)
     if factories then
        for _, factory in factories do
            AddRallyPoint(factory)

+         if not factory.HasBeenSelected then
+             factory:ProcessInfo('SetRepeatQueue','true')
+             factory.HasBeenSelected = true
+         end

        end
     end
end

  ```
</details>

### Testing setup
With the option enabled/disabled, build a factory. When you select the factory it should be set to repeat build if the option is enabled, or not if the option is disabled.

2022-12-23 05:31 UTC, Garanas commented
I don't have time to go into details now, but there's a separation between the sim and the UI. Any field (`HasBeenSelected`) you set in the sim is not available in the UI. The reason this works is because this statement:
- https://github.com/FAForever/fa/pull/4524/files#diff-4d24f0ee6330335ec1aa4beab16e827c5930fc86fa6ce5cbf5aaf85471412e32R664

Returns true whether the value is `false` or `nil`, and in this case it is `nil` because you're using the value in the ui layer, which is oblivious of the value in the sim layer.

See also:
- https://github.com/FAForever/fa/blob/deploy/fafdevelop/engine/Sim/Unit.lua
- https://github.com/FAForever/fa/blob/deploy/fafdevelop/engine/User/UserUnit.lua

2022-12-23 10:52 UTC, haifron commented
Ah ok that explains a lot of the confusion I was having 😛 thanks for your explanation. I've therefore removed the changes to `/lua/defaultunits.lua` since they were unnecessary. I'll just believe it was thanks to my genius that it worked anyway.

Do you have an opinion on whether the added `gamemain.lua` code should stay there, or be moved to `rallypoint.lua`?

###### That force-push was an accident and I've undone it 🙃

2022-12-23 18:29 UTC, Garanas commented on lua/ui/game/gamemain.lua
> +        if options.repeatbuild then
Best to do this like this:
- `Prefs.GetFromCurrentProfile('options.cursor_splash_damage') == 'on'`

But then with the correct values of course. That way if a player changes the preferences they don't need to restart the game.

2022-12-23 18:33 UTC, Garanas requested changes

2022-12-23 18:33 UTC, Garanas commented on lua/ui/game/gamemain.lua
> +            if not table.empty(factories) then
There's no need to check for this - if it empty then the for loop will simply not iterate.

2022-12-23 18:33 UTC, Garanas commented on lua/ui/game/gamemain.lua
> +            local factories = EntityCategoryFilterDown(categories.STRUCTURE * categories.FACTORY, added) -- find all newly selected factories
Is there a reason why you use the `added` parameter and not the `newSelection` parameter?

2022-12-23 19:01 UTC, haifron commented on lua/ui/game/gamemain.lua
> +        if options.repeatbuild then
Oh perfect, I was wondering how to get that behaviour.

2022-12-23 19:15 UTC, haifron commented on lua/ui/game/gamemain.lua
> +            local factories = EntityCategoryFilterDown(categories.STRUCTURE * categories.FACTORY, added) -- find all newly selected factories
Yes, `added` = `newSelection` - `oldSelection` essentially. Since we only need to check for factories that have *never* been selected before, looking at anything that was in `oldSelection` is totally redundant - we literally just selected them.

This at worst saves no time (nothing was reselected, i.e `newSelection` == `added`), and at best saves a lot of time (a lot of units were reselected, i.e `newSelection` ≫ `added`).

2022-12-23 20:48 UTC, Garanas commented on lua/ui/game/gamemain.lua
> +            local factories = EntityCategoryFilterDown(categories.STRUCTURE * categories.FACTORY, added) -- find all newly selected factories
I agree - good call

2022-12-23 20:49 UTC, Garanas commented on lua/ui/game/gamemain.lua
> +        if Prefs.GetFromCurrentProfile('repeatbuild') then
needs to be `options.repeatbuild`

2022-12-23 20:51 UTC, Garanas commented
We need to look into how we want to manage code that works on a selection change in general. This solution is fine for now, but we may put it somewhere else in the (near) future. I just don't know where to put it yet.

There's a lot of functionality that works with the current selection in some fashion.

2022-12-23 20:58 UTC, haifron commented on lua/ui/game/gamemain.lua
> +        if Prefs.GetFromCurrentProfile('repeatbuild') then
B) fixed, cheers

2022-12-23 21:09 UTC, Garanas commented on lua/options/options.lua
> +                title = "<LOC OPTIONS_0287>Factories Default Repeat Build",
I'd argue that this is a gameplay feature and not an interface feature, as it immediately impacts gameplay. Perhaps put it below the `Commands` header?

2022-12-23 21:10 UTC, Garanas approved these changes

2022-12-24 14:30 UTC, haifron commented on lua/options/options.lua
> +                title = "<LOC OPTIONS_0287>Factories Default Repeat Build",
Sure 👍

2022-12-25 08:51 UTC, merged

2023-01-20 20:41 UTC, Garanas commented
Played a few games and I can't play without this anymore - great work @haifron