Projectile refactor 1
FAForever/fa pull request #4528
Opened 2022-12-23 19:45 UTC by MrRowey

Batch one of Projectiles refactoring

2022-12-23 20:35 UTC, Garanas commented on lua/aeonprojectiles.lua
> +    CountdownLength = 101,
What does this do?

2022-12-23 20:36 UTC, Garanas commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> +        self:SetMaxSpeed(20)
Feels to me this should also call the base function

2022-12-23 20:36 UTC, Garanas commented on projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
> +        self.HasImpacted = true
If this value is not used then there is no need to define it

2022-12-23 20:38 UTC, Garanas commented on projectiles/AANTorpedoCluster01/AANTorpedoCluster01_script.lua
>              proj:PassDamageData(self.DamageData)
in this case you can also write: `proj.DamageData = self.DamageData`

2022-12-23 20:38 UTC, Garanas commented on lua/aeonprojectiles.lua
> +    CountdownLength = 101,
I get it now, that is the count down timer. Is that function available at this scope?

2022-12-23 20:39 UTC, Garanas commented on projectiles/AIFFragmentationSensorShell01/AIFFragmentationSensorShell01_script.lua
> +            proj:PassDamageData(self.DamageData)
You can also use `proj.DamageData = self.DamageData`, as you pass the damage data unchanged

2022-12-23 20:39 UTC, Garanas commented on projectiles/AIFGuidedMissile02/AIFGuidedMissile02_Script.lua
> +		WaitTicks(6)
should be `WaitTicks(7)`, if I am not mistaken.

2022-12-23 20:39 UTC, Garanas commented on projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
> +        WaitTicks(3)
Should be `WaitTicks(4)`

2022-12-23 20:40 UTC, Garanas commented on projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
> +            WaitTicks(3)
Should be `WaitTicks(4)`

2022-12-23 20:40 UTC, Garanas commented on projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
> +						WaitTicks(12)
This should be `WaitTicks(16)`

2022-12-23 20:40 UTC, Garanas requested changes
Good start - let's tidy it up and get this merged!

2022-12-23 20:54 UTC, MrRowey commented on lua/aeonprojectiles.lua
> +    CountdownLength = 101,
Didn't mean to add this here :) removed

2022-12-24 07:51 UTC, Garanas commented on projectiles/AANDepthCharge03/AANDepthCharge03_script.lua
>      OnEnterWater = function(self)
Needs to call the base class I think

2022-12-24 07:57 UTC, Garanas requested changes
Almost there, great job 👍

2022-12-24 14:22 UTC, MrRowey commented on projectiles/AANDepthCharge03/AANDepthCharge03_script.lua
>      OnEnterWater = function(self)
@Garanas this didn't call the base function to begin with so and their no 
```
ADepthChargeProjectile.CountdownExplosion(self)
```
to use

2022-12-29 13:56 UTC, Garanas commented on projectiles/AANDepthCharge03/AANDepthCharge03_script.lua
>      OnEnterWater = function(self)
We're talking here about `OnEnterWater` however

2022-12-29 14:01 UTC, MrRowey commented on projectiles/AANDepthCharge03/AANDepthCharge03_script.lua
>      OnEnterWater = function(self)
xD Oohhhhhhh yah i can fix that :)

2022-12-29 18:48 UTC, Garanas approved these changes

2022-12-29 18:48 UTC, merged