Projectile Refactoring 2
FAForever/fa pull request #4529
Opened 2022-12-23 19:54 UTC by MrRowey

Batch 2 of Projectile refactoring

2022-12-23 20:41 UTC, Garanas commented on projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
> +        self.WaitTime = 1
Should be `2`, see also the definition of `WaitSeconds` in `simInit.lua`

2022-12-23 20:41 UTC, Garanas commented on projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
> +						WaitTicks(12)
Should be `16` instead of `12`

2022-12-23 20:41 UTC, Garanas commented on projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
> +            WaitTicks(3)
Should be `4`

2022-12-23 20:42 UTC, Garanas commented on projectiles/AIFQuantumWarhead02/AIFQuantumWarhead02_script.lua
> +        self.Trash:Add(ForkThread(self.ShakeAndBurnMe, self.Army,self))
should be: `self.Trash:Add(ForkThread(self.ShakeAndBurnMe, self, self.Army))` as `self:ForkThread` inserts the `self` parameter into the first argument of the function we're forking

2022-12-23 20:43 UTC, Garanas commented on projectiles/AIMFlare01/AIMFlare01_script.lua
>          self.MyShield = Flare {
Funny how it is called a shield 😄

2022-12-23 20:43 UTC, Garanas commented on projectiles/CAAMissileNanite01/CAAMissileNanite01_script.lua
> +        WaitTicks(2)
Should be `16`, unless this was an intentional change?

2022-12-23 20:43 UTC, Garanas commented on projectiles/CAAMissileNanite02/CAAMissileNanite02_script.lua
> +        self.Trash:Add(ForkThread(self.UpdateThread))
need to include the `self` argument too, see previous conversations

2022-12-23 20:44 UTC, Garanas commented on projectiles/CAAMissileNanite03/CAAMissileNanite03_script.lua
> +        self.Trash:Add(ForkThread(self.UpdateThread))
Same here, see last conversation

2022-12-23 20:44 UTC, Garanas commented on projectiles/CAANanoDart02/CAANanoDart02_script.lua
> +            CreateEmitterOnEntity(self,self.Army,v )
Is `FxTrails` populated with anything at this point? I thought we determined that it was not the case

2022-12-23 20:45 UTC, Garanas commented on projectiles/caananodartex/CAANanoDartEx_script.lua
> +        self.Trash:ADD(ForkThread(self.UpdateThread))
YES, ADD IT PLEASE

2022-12-23 20:46 UTC, Garanas requested changes
Looking good - carefully review the `self:ForkThread(...)` replacements to make sure that the `self` argument is there, and that it is the first argument after the function. Also carefully evaluate the `WaitTicks` replacements, as they're not all equivalent. If that is intentionally, then please add a comment (in Github) that it is intentional

2022-12-23 22:08 UTC, MrRowey commented on projectiles/CAAMissileNanite01/CAAMissileNanite01_script.lua
> +        WaitTicks(2)
yh my brain just rounded it up xD i started to realise this after i was making changes to batch 4 that they were way out of what they should be :)

2022-12-29 14:15 UTC, Garanas commented on projectiles/CAANanoDart02/CAANanoDart02_script.lua
> +            CreateEmitterOnEntity(self,self.Army,v )
Did you look into this?

2022-12-29 14:15 UTC, Garanas commented on projectiles/CAANanoDart03/CAANanoDart03_script.lua
> +        WaitTicks(3)
Should be 4

2022-12-29 14:17 UTC, Garanas requested changes
Minor changes required!

2022-12-29 16:59 UTC, MrRowey commented on projectiles/CAANanoDart02/CAANanoDart02_script.lua
> +            CreateEmitterOnEntity(self,self.Army,v )
FxTrails is Empty in the hierarchy

2022-12-29 18:51 UTC, Garanas approved these changes

2022-12-29 18:51 UTC, merged