Projectile refactoring 3
FAForever/fa pull request #4530
Opened 2022-12-23 20:07 UTC by MrRowey

Batch 3 of projectile Refactoring

2022-12-23 20:47 UTC, Garanas requested changes
As with the other two pull requests - looking good. But carefully evaluate the `self:ForkThread` and `WaitSeconds` replacements

2022-12-24 08:39 UTC, Garanas commented on projectiles/CDFTracker01/CDFTracker01_script.lua
> +            local tracker = CreateUnit('URB5206', self.Data.Parent.Army, x, y, z, 0, 0, 0, 0)
What is this 'Parent' value? Is that a unit?

2022-12-24 08:39 UTC, Garanas commented on projectiles/CIFBrackmanHackPegs01/CIFBrackmanHackPegs01_script.lua
> +        local vx, _, vz = self:GetVelocity()
I'm not sure if this is logically equivalent, but this unit isn't being used regardless 😄

2022-12-24 08:41 UTC, Garanas commented on projectiles/CIFBrackmanHackPegs02/CIFBrackmanHackPegs02_script.lua
> +            WaitTime= ( 0.4+RandomFloat(-0.2,0.2)*10+1 )  ------Get how long to wait before launching the next one.
This change isn't equivalent, I think it should be: `3 + ((Random() * 3) ^0)`, where `^0` is a cheap way to floor a positive number using bit operators 😄

2022-12-24 08:43 UTC, Garanas commented on projectiles/CIFEMPFluxWarhead03/CIFEMPFluxWarhead03_script.lua
> -    FxImpactUnit = {},
These may have use: they can override effects provided in the hierarchy. Are you sure this is a safe change?

2022-12-24 08:43 UTC, Garanas commented on projectiles/CIFEMPFluxWarhead04/CIFEMPFluxWarhead04_script.lua
> -    FxTrails = {},
Same here, see last conversation

2022-12-24 08:43 UTC, Garanas commented on projectiles/CIFMissileTactical01/CIFMissileTactical01_Script.lua
> +        if not self.Split and (amount >= self.Health) then
self.Health is not populated, best to use the C function

2022-12-24 08:44 UTC, Garanas commented on projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
> +        if not self.Split and (amount >= self.Health) then
Same here, not populated

2022-12-24 08:44 UTC, Garanas commented on projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua
> +        if not self.Split and (amount >= self.Health) then
Same here, not poulated

2022-12-24 08:45 UTC, Garanas requested changes
Make sure to evaluate the hierarchy for certain changes. Removing empty tables that represent effects may have side effects.

Also: `self.Health` is not a field, unless it is defined somewhere and I'm not aware of it 😄

2022-12-24 14:45 UTC, MrRowey commented on projectiles/CDFTracker01/CDFTracker01_script.lua
> +            local tracker = CreateUnit('URB5206', self.Data.Parent.Army, x, y, z, 0, 0, 0, 0)
not sure :)

2022-12-24 15:42 UTC, MrRowey commented on projectiles/CIFEMPFluxWarhead03/CIFEMPFluxWarhead03_script.lua
> -    FxImpactUnit = {},
how to do i find if it has a uses as in the hierarchy FxImpactUnit is not populated

2022-12-24 15:46 UTC, MrRowey commented on projectiles/CIFEMPFluxWarhead04/CIFEMPFluxWarhead04_script.lua
> -    FxTrails = {},
Same as Last comment

2022-12-29 18:53 UTC, Garanas commented on projectiles/CIFEMPFluxWarhead03/CIFEMPFluxWarhead03_script.lua
> -    FxImpactUnit = {},
You're correct, they're all empty

2022-12-29 18:54 UTC, Garanas commented on projectiles/CIFEMPFluxWarhead04/CIFEMPFluxWarhead04_script.lua
> -    FxTrails = {},
```lua
---@class CEMPFluxWarheadProjectile : NukeProjectile
CEMPFluxWarheadProjectile = Class(NukeProjectile, SingleBeamProjectile) {
    BeamName = '/effects/emitters/missile_exhaust_fire_beam_01_emit.bp',
    FxInitialAtEntityEmitter = {},
    FxUnderWaterTrail = {'/effects/emitters/missile_cruise_munition_underwater_trail_01_emit.bp',},
    FxOnEntityEmitter = {},
    FxExitWaterEmitter = EffectTemplate.DefaultProjectileWaterImpact,
    FxSplashScale = 0.65,
    ExitWaterTicks = 9,
    FxTrailOffset = -0.5,

    -- LAUNCH TRAILS
    FxLaunchTrails = {},

    -- TRAILS
    FxTrails = {'/effects/emitters/missile_cruise_munition_trail_01_emit.bp',},

    -- Hit Effects
    FxImpactUnit = {},
    FxImpactLand = {},
    FxImpactUnderWater = {},
}
```

The class it inherits from has fx trails set, so if we'd not set them to an empty table then we'd end up having trails

2022-12-29 18:57 UTC, Garanas approved these changes

2022-12-29 18:57 UTC, Garanas commented on projectiles/CDFTracker01/CDFTracker01_script.lua
> +            local tracker = CreateUnit('URB5206', self.Data.Parent.Army, x, y, z, 0, 0, 0, 0)
this is a weird script, as a projectile ends up creating a unit 🤔 ?

2022-12-29 18:58 UTC, merged