Weapons
FAForever/fa pull request #4552
Opened 2023-01-04 11:28 UTC by MrRowey

2023-01-04 12:58 UTC, Garanas commented on lua/aeonweapons.lua
> -            proj:PassDamageData(damageTable)
This substitution is not logically equivalent! It would be:
`proj:PassDamageData(damageTable)` `->` ` proj.PassDamageData(proj, damageTable)`

But we've learned that it is not faster to do that - as this is an internal Lua functionality, unlike the class implementations of Forkthread. Best to revert these changes.

2023-01-04 13:00 UTC, Garanas commented on lua/cybranweapons.lua
>          local data = {
Could you investigate what this data is used for?

2023-01-04 13:10 UTC, Garanas requested changes
Bring back the `:` for those projectile function calls and I think we're good. I'll look at it again this evening.

2023-01-04 13:21 UTC, MrRowey commented on lua/cybranweapons.lua
>          local data = {
Will Lookin to via Seperat PR

2023-01-04 14:40 UTC, Garanas commented on lua/aeonweapons.lua
> +            proj.PassDamageData(damageTable)
missed these

2023-01-04 14:42 UTC, Garanas commented on lua/terranweapons.lua
> -    FxMuzzleFlash = {},
Removing `FxMuzzleFlash` will change the behavior, and give the weapon the default muzzle as defined by the `DefaultProjectileWeapon` class

2023-01-04 14:43 UTC, Garanas requested changes
You've removed some empty tables, but not all of them guarantee the same behavior. Some are empty to override the base effects, usually of the `DefaultProjectileWeapon` class.

2023-01-11 18:03 UTC, Garanas approved these changes

2023-01-11 18:05 UTC, merged