SCU rebalance
FAForever/fa pull request #4621
Opened 2023-01-22 20:37 UTC by TurinturambarFAF

Nerfs the raw SCU HP and dps to the level of a vanilla ACU and also nerfs the raw SCU bp from 56 to 40 and compensates these changes by buffs of the respective upgrades.

2023-01-23 06:24 UTC, Garanas commented
What are the ink files 🤔 ?

2023-01-23 08:43 UTC, Tagada14 commented
Please fix some of the formatting issues and the ink files. Also, shouldn't the Cybran have 10k hp if we are going with the same hp as the ACU theme?

2023-01-23 16:36 UTC, Tagada14 commented
Please resolve the conflict so that I can merge the PR

2023-01-25 00:49 UTC, ComradeStryker commented
Won't this affect how much HP these units gain when they vet?

These changes will affect the 2 factions with shieldable SACUs more than the other two.
In the long run, they're losing more HP, as for example, the Seraphim's SACU's shield doesn't vet with the unit.

---

~ Stryker

2023-01-26 10:23 UTC, Tagada14 commented
It will have slight effects on the units but it really doesn't matter. The difference will be negligible.

2023-01-26 11:12 UTC, Tagada14 requested changes

2023-01-26 11:12 UTC, Tagada14 commented on units/UAL0301/UAL0301_unit.bp
> +            NewDamageMod = 200,
Actually you could change this:
`wep:AddDamageMod(-self:GetBlueprint().Enhancements['RightReactonCannon'].NewDamageMod)`
to:
`wep:AddDamageMod(-self:GetBlueprint().Enhancements['StabilitySuppressant'].NewDamageMod)`

2023-01-26 11:12 UTC, Tagada14 commented on units/UEL0301/UEL0301_script.lua
> +            wep:AddDamageMod(-bp.UpgradeDamageMod)
` wep:AddDamageMod(-self:GetBlueprint().Enhancements['AdvancedCoolingUpgrade'].UpgradeDamageMod)`

2023-01-26 11:12 UTC, Tagada14 commented on units/XSL0301/XSL0301_unit.bp
> +            UpgradeDamageMod = 300,
This should be NewDamageMod

2023-01-26 11:12 UTC, Tagada14 commented on units/XSL0301/XSL0301_script.lua
> +            wep:AddDamageMod(-bp.NewDamageMod or 0)
`wep:AddDamageMod(-wep:AddDamageMod(-self:GetBlueprint().Enhancements['EnhancedSensors'].NewDamageMod))`

2023-01-26 11:14 UTC, Tagada14 commented
@Garanas 
Is this fine or bad practice?
`wep:AddDamageMod(-wep:AddDamageMod(-self:GetBlueprint().Enhancements['EnhancedSensors'].NewDamageMod))`
I would like to avoid having to add values like HP, Damage etc. in both the enchancement and it's removal but I would like to know if this method if fine or not. Also perhaps there is a better way?

2023-01-26 11:16 UTC, Tagada14 commented
@TurinturambarFAF Can you allow me to push to your Repo so that I can update this branch with the changes fixing all those things I mentioned in the review?
Also, next time please at least test the changes, half of the damage upgrades were broken XD

2023-01-26 13:17 UTC, Garanas commented
> @Garanas Is this fine or bad practice? `wep:AddDamageMod(-wep:AddDamageMod(-self:GetBlueprint().Enhancements['EnhancedSensors'].NewDamageMod))` I would like to avoid having to add values like HP, Damage, etc. in both the enhancement and its removal but I would like to know if this method is fine or not. Also perhaps there is a better way?


I'm not too familiar with how enhancements work, but it seems to me it is best to do the same thing that the gun upgrade of ACUs do in terms of coding style.

2023-01-27 20:53 UTC, closed without merging