Improve memory management of treads
FAForever/fa pull request #4640
Opened 2023-01-26 21:07 UTC by Garanas

2023-01-26 23:01 UTC, Garanas commented
Note that the system doesn't actually work properly: try moving 200 tanks at once and you'll see what I mean. There appears to he a maximum to the number of splats being rendered, and that maximum is relatively low in comparison to the number of splats generated.

2023-01-27 00:07 UTC, BlackYps commented
I think that's the same reason why building tarmacs etc. disappear sometimes when tilting the camera. The render limit kicks in. I guess they implemented it to not stress the hardware too much, but today it shouldn't be an issue anymore. Probably needs an engine patch to increase it though.

Do I see this correctly that different tread textures per terrain type are possible?

2023-01-27 00:35 UTC, Hdt80bro commented
Yes, *any* effect for any terrain type can be changed, see https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/TerrainTypes.lua

2023-01-27 07:13 UTC, Garanas commented
> I think that's the same reason why building tarmacs etc. disappear sometimes when tilting the camera. The render limit kicks in. I guess they implemented it to not stress the hardware too much, but today it shouldn't be an issue anymore. Probably needs an engine patch to increase it though.

Tarmacs are decals, they work different. I'm not entirely sure what the exact difference is.

2023-01-27 07:42 UTC, Garanas commented
> Do I see this correctly that different tread textures per terrain type are possible?

Yes, but it didn't quite work like that. At the moment terrain would only disable treads (no need for treads on rocks or metal, for example). As a result the majority of generated maps have no treads. I'm wondering whether that is why generated maps always felt faster than regular maps. With this pull request we change that - treads always work, even when the terrain type tells you not to.

2023-01-27 17:59 UTC, Hdt80bro requested changes
It doesn't look like this will work. Adding back the missing function is trivial, but letting treads underwater, on snow, and on tarmacs looks very unnatural. Since threads are very lightweight, I'm interested in the performance gains. You might be able to get more by consolidating all treads for the unit into one thread, instead of one for each. The Fatboy treads also looks very noisy since it always overlaps both full treads, so I'm not sure that's better.

2023-01-27 17:59 UTC, Hdt80bro commented on lua/sim/Unit.lua
> -    GetTTTreadType = function(self, pos)
We can't remove this method, it's still used elsewhere causing errors (and probably by mods as well)

2023-01-27 17:59 UTC, Hdt80bro commented on lua/defaultcomponents.lua
> +            WaitTicks(interval)
This delays tread creation by one interval any time the unit moves again

2023-01-27 19:14 UTC, Garanas commented on lua/sim/Unit.lua
> -    GetTTTreadType = function(self, pos)
I'll add that back in

2023-01-27 19:14 UTC, Garanas commented on lua/defaultcomponents.lua
> +            WaitTicks(interval)
Visually that is fine - during the first interval the unit barely moves.

2023-01-27 19:20 UTC, Garanas commented
@Hdt80bro I don't understand.

> Adding back the missing function is trivial, but letting treads underwater, on snow, and on tarmacs looks very unnatural

I agree with the water, but treads have always shown on tarmacs. See also: 

![image](https://user-images.githubusercontent.com/15778155/215176312-9207ef0f-f3f7-48b0-9b4a-04daa0c9f182.png)

Testing on `Arctic Refuge` and you're correct: the treads do not show on snow. Odd - in my personal perception they should be visible on snow too, but maybe a different type of tread. I'll add in the terrain type check again.

> You might be able to get more by consolidating all treads for the unit into one thread, instead of one for each. 

I like the idea, but that would be something for a second iteration. This first iteration is already a good improvement memory wise on the current implementation.

2023-01-27 19:56 UTC, Hdt80bro commented on lua/defaultcomponents.lua
> +            WaitTicks(interval)
I can notice it--it's logically an error, just remove it

2023-01-27 20:27 UTC, Hdt80bro commented
Ah, my bad, [these](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/TerrainTypes.lua#L1568-L1609) are left over from vanilla
![image](https://user-images.githubusercontent.com/37224614/215190203-bedcb20c-f228-42b9-98ee-6992df69c0ff.png)
Still, not making tread marks on regular concrete, underwater, on snow makes sense (treads look like the dirt being kicked up, something ice and snow doesn't have--some snow types looks like they're only a thin layer and we could change them, but the tread would probably still look different than normal)

2023-01-27 21:00 UTC, Garanas commented
We could look into adjusting the terrain type:

![image](https://user-images.githubusercontent.com/15778155/215196502-fca1ea25-7658-4b50-99ea-2fd6715d53ac.png)

But how do we change them back, after the tarmac is gone 🤔

2023-01-27 21:08 UTC, Garanas commented on lua/defaultcomponents.lua
> +            WaitTicks(interval)
adjusted it to waiting just a single tick

2023-01-27 21:15 UTC, Hdt80bro commented on lua/defaultcomponents.lua
> +            WaitTicks(interval)
Why do you think you need it?

2023-01-27 21:16 UTC, Garanas commented
To me the fatboy doesn't look that bad

![image](https://user-images.githubusercontent.com/15778155/215202265-db7ad561-4054-4a86-928f-d393c773ba2f.png)

2023-01-28 12:57 UTC, BlackYps commented
> But how do we change them back, after the tarmac is gone

Maybe on destruction of the building, when the tarmac is set for removal with a waiting time period. It's not perfect, as treads would show up as soon as the building is destroyed, but while the building is still alive it would work.

2023-01-29 12:36 UTC, Garanas commented on lua/defaultcomponents.lua
> +            WaitTicks(interval)
Having an infinite loop with no wait statement is asking for trouble.

2023-01-29 12:37 UTC, Garanas commented
@BlackYps it wasn't so much about when to change it, more about what to change it (back) to?

2023-01-29 12:39 UTC, Garanas commented
I'll be merging these changes in as they are a good improvement over the old implementation, without changing the old behavior.

2023-01-29 12:44 UTC, merged