completed units
FAForever/fa pull request #4641
Opened 2023-01-26 22:40 UTC by MrRowey

In progress

2023-03-18 18:11 UTC, MrRowey commented
@Garanas this on is now ready for review

2023-03-27 21:30 UTC, MrRowey commented
@Garanas This Is Tested and Ready for Review 🤠

2023-06-21 19:37 UTC, Hdt80bro requested changes

2023-06-21 19:37 UTC, Hdt80bro commented on lua/seraphimweapons.lua
> +---------------------------------------------------------------------------------------------------------
I'm not a fan of this new header - I think the old one was fine

2023-06-21 19:37 UTC, Hdt80bro commented on units/DAL0310/DAL0310_Script.lua
> +                    proj:PassMetaDamage(self, data)
This is not the same

2023-06-21 19:37 UTC, Hdt80bro commented on units/DEA0202/DEA0202_Script.lua
> +                local unit = self.unit
`unit` is only used once; it might be more readable to leave it as-is

2023-06-21 19:37 UTC, Hdt80bro commented on units/DEA0202/DEA0202_Script.lua
> +            RWingRotator = CreateRotator(self, 'Right_Wing', 'y')
These don't set the instance field anymore. We prefer non-upvalue variables to be lowercase as well.

2023-06-21 19:37 UTC, Hdt80bro commented on units/DEL0204/DEL0204_Script.lua
> +                    spinManip = CreateRotator(unit, 'Left_Arm_Barrel', 'z', nil, 270, 180, 60)
This doesn't set the instance field anymore

2023-06-21 19:37 UTC, Hdt80bro commented on units/DELK002/DELK002_script.lua
> +                    spin2 = CreateRotator(unit, 'Left_Barrel', 'z', nil, 360, 180, 60)
This doesn't set the instance field anymore

2023-06-21 19:37 UTC, Hdt80bro commented on units/DRA0202/DRA0202_Script.lua
>      RotateWings = function(self, target)
Same problems as the other `RotateWings` script

2023-06-21 19:37 UTC, Hdt80bro commented on units/DRLK005/DRLK005_script.lua
> +DRLK005 = ClassUnit(import("/lua/cybranunits.lua").CConstructionEggUnit) {}
This was fine before

2023-06-21 19:37 UTC, Hdt80bro commented on units/DSLK004/DSLK004_script.lua
> +local CollisionBeam = import("/lua/seraphimweapons.lua").PhasonCollisionBeam2
You need to keep the name the same for compatibility reasons

2023-06-21 20:13 UTC, MrRowey commented on lua/seraphimweapons.lua
> +---------------------------------------------------------------------------------------------------------
I've done this to every fine soo?

2023-06-21 21:17 UTC, Hdt80bro commented on lua/seraphimweapons.lua
> +---------------------------------------------------------------------------------------------------------
It would be a lot of your PR's to change - why'd you change it in the first place though?

2023-06-23 09:53 UTC, MrRowey commented on units/DAL0310/DAL0310_Script.lua
> +                    proj:PassMetaDamage(self, data)
Whats the Alternative to doing this then ?

2023-07-13 09:03 UTC, speed2CZ commented on units/DEA0202/DEA0202_Script.lua
> +        lWingRotator = CreateRotator(self, 'Left_Wing', 'y')
So now you're creating rotators each time RotateWings is called, instead of only once?

2023-07-13 09:04 UTC, speed2CZ commented on units/DEA0202/DEA0202_Script.lua
> +        if not lWingRotator then
What the reason for this condition?
It can be never false, since you're assigning this few lines above

2023-07-13 09:07 UTC, speed2CZ commented on units/DELK002/DELK002_script.lua
> +                if spin1 then
if you've just created the rotators few lines above, what would be the case where they would not exist?

2023-07-13 09:09 UTC, speed2CZ commented on units/DRA0202/DRA0202_Script.lua
> +            lWingRotator:SetGoal(fighterAngle)
shouldnt this be -fighterAngle

2023-07-13 09:09 UTC, speed2CZ commented on units/DRA0202/DRA0202_Script.lua
> +            lWingRotator:SetGoal(bomberAngle)
shouldnt this be -bomberAngle

2023-07-18 10:10 UTC, closed without merging