Unit Script files Tidy up Part 4
FAForever/fa pull request #4650
Opened 2023-01-28 22:30 UTC by MrRowey

2023-04-13 17:39 UTC, Garanas commented on units/UEL0001/UEL0001_script.lua
> +                    self.RebuildThread = self.Trash:Add(ForkThread(self.RebuildPod, 1,self))
Not a valid replacement, the `Add` function doesn't return the thread

2023-04-13 17:40 UTC, Garanas commented on units/UEL0301/UEL0301_script.lua
> +                self.RebuildThread = self.Trash:Add(ForkThread(self.RebuildPod,self))
Not a valid replacement

2023-04-13 17:40 UTC, Garanas commented on units/UEL0307/UEL0307_script.lua
> +        self.DestroyManipulatorsThread = self.Trash:Add(ForkThread(self.DestroyManipulators, self))
Not a valid replacement

2023-04-13 17:40 UTC, Garanas commented on units/UEL0307/UEL0307_script.lua
> +        self.PointerRestartThread = self.Trash:Add(ForkThread(self.PointerRestart, self))
Not a valid replacement

2023-06-21 20:42 UTC, Hdt80bro requested changes

2023-06-21 20:42 UTC, Hdt80bro commented on units/UEL0001/UEL0001_script.lua
> +            end,self))
It doesn't use this parameter, but in general, adding the `self` parameter to the functions to remove an upvalue would be good.

2023-06-21 20:42 UTC, Hdt80bro commented on units/UEL0301/UEL0301_script.lua
> -        -- Block Jammer until Enhancement is built
Don't remove non-trivial comments

2023-06-21 20:42 UTC, Hdt80bro commented on units/UEL0301/UEL0301_script.lua
> +            end,self))
Same, for the parameter

2023-06-21 20:42 UTC, Hdt80bro commented on units/UEL0307/UEL0307_script.lua
> +            WaitTicks(11)
It's good to leave the `WaitSeconds` for readability and intent - this isn't performance critical

2023-06-21 20:42 UTC, Hdt80bro commented on units/UEL0307/UEL0307_script.lua
> -                self.TargetPointer:SetFireTargetLayerCaps(self.TargetLayerCaps[self.Layer]) --this resets the stop feature - note that its reset on layer change!
Please leave in helpful comments

2023-06-21 20:42 UTC, Hdt80bro commented on units/UES0305/UES0305_script.lua
> +        self.TimedSonarEffectsThread = self.Trash:Add(ForkThread(self.TimedIdleSonarEffects,self))
This isn't the same

2023-06-21 20:42 UTC, Hdt80bro commented on units/UES0305/UES0305_script.lua
> +            self.OnBeingBuiltEffectsBag:Add(self.Trash:Add(ForkThread(CreateBuildCubeThread, builder, self.OnBeingBuiltEffectsBag, self)))
This isn't the same

2023-06-21 20:42 UTC, Hdt80bro commented on units/UES0401/UES0401_script.lua
> +                SetRate(-1)
When doing this, put the colon on the same line

2023-06-21 20:42 UTC, Hdt80bro commented on units/UES0401/UES0401_script.lua
> +            self.OnBeingBuiltEffectsBag:Add(self.Trash:Add(ForkThread(CreateBuildCubeThread, builder, self.OnBeingBuiltEffectsBag,self)))
This isn't the same

2023-06-21 20:42 UTC, Hdt80bro commented on units/UES0401/UES0401_script.lua
> -
Leave all of this please

2023-06-21 20:42 UTC, Hdt80bro commented on units/URA0001/URA0001_script.lua
> +                local bpos = self.spawnedBy.Blueprint
This isn't the same

2023-06-21 20:42 UTC, Hdt80bro commented on units/URA0001/URA0001_script.lua
> +                WaitTicks(delay)
This isn't the same

2023-06-21 20:42 UTC, Hdt80bro commented on units/URA0104/URA0104_script.lua
> +    AirDestructionEffectBones = { 'Left_Exhaust', 'RighF_Exhaust', 'Char04', 'Char03', 'Char02', 'Char01',
Is the bone really misspelled?

2023-06-21 20:42 UTC, Hdt80bro commented on units/URA0104/URA0104_script.lua
> +            WaitTicks(util.GetRandomFloat(2, 9))
This isn't quite the same

2023-06-21 20:42 UTC, Hdt80bro commented on units/URA0401/URA0401_script.lua
> +            self.ThrustExhaustTT1 = self.Trash:Add(ForkThread(self.MovementAmbientExhaustThread,self))
This isn't the same

2023-06-23 10:16 UTC, closed without merging