Refactoring LazyVars
FAForever/fa pull request #4810
Opened 2023-03-14 20:49 UTC by Garanas

Initial setup to refactor LazyVars so that they re-use memory instead of allocating new memory all the time.

2023-03-14 21:11 UTC, Hdt80bro commented
Looks like this is mostly just moving the functions into the table. If you're going to remove the annotation hack I did, [these lines](https://github.com/FAForever/fa/pull/4810/files#diff-400e5297b564eef68495418887792b9916dd8d86033ff35cb08c069416aaa4e6R23-R24) describing it should go as well. If we're not worried about stack size and want to remove the `do ... end` blocks for readability like you did [here](https://github.com/FAForever/fa/pull/4810/files#diff-400e5297b564eef68495418887792b9916dd8d86033ff35cb08c069416aaa4e6L235-L239), there's a lot of other places we can do that in this file as well.

2023-03-15 05:43 UTC, Garanas commented
This is a mere setup, I couldn't think properly in the old setup. Next steps is casually applying the changes we described. I'll look into your suggestions

2023-03-16 05:35 UTC, Hdt80bro commented
`OnDirty` is actually just an event listener and doesn't do much anyway - the `used_by` list is the one that's set automatically from context when used in the computation of another lazyvar and the table that's getting replaced here.

2023-03-16 05:42 UTC, Hdt80bro commented
Oh you're right, it dirties the lazyvars from `used_by` directly and only adds stuff to the list if it has an `OnDirty` callback. I wonder if integrating one of those tables instead would be better memory-wise and instead we reuse the same dirtied table for all lazyvars to track `OnDirty` callbacks.

2023-03-16 05:50 UTC, 4z0t commented on lua/ui/game/worldview.lua
>      if viewRight then
Didn't know that this gross exists...

2023-03-16 05:53 UTC, Hdt80bro commented on lua/ui/game/worldview.lua
>      if viewRight then
I'd recommend encapsulating the old `compute` field into an understandable getter method, just something as simple as
```lua
function LazyVarMetaTable:GetComputeFunction()
    return self[4]
end
```
so the magic numbers don't bleed over

2023-03-16 05:54 UTC, Garanas commented on lua/ui/game/worldview.lua
>      if viewRight then
@Hdt80bro that is smart 👍 , I'll do that

2023-03-16 05:56 UTC, Garanas commented
> Oh you're right, it dirties the lazyvars from `used_by` directly and only adds stuff to the list if it has an `OnDirty` callback. I wonder if integrating one of those tables instead would be better memory-wise and instead we reuse the same dirtied table for all lazyvars to track `OnDirty` callbacks.

I'm not sure how well that would work with the idea of the keys being weak

2023-03-16 05:57 UTC, Hdt80bro commented
If we empty the table anyway, it doesn't matter

2023-03-16 05:58 UTC, Garanas commented
I was more thinkng of the `OnDirty` key being weak too, and since there is usually no other reference to the function it may ditch the function

2023-03-16 06:03 UTC, 4z0t requested changes

2023-03-16 06:03 UTC, 4z0t commented on lua/lazyvar.lua
>          end
Use `assert`

2023-03-16 06:03 UTC, 4z0t commented on lua/lazyvar.lua
> +                LOG("OnDirty")
Logging

2023-03-16 06:06 UTC, Hdt80bro commented
The `OnDirty` key? I'm not sure I entirely understand, but it sounds like you're talking about `used_by` and `uses` having weak keys (not values), which isn't something I had considered. However, as long only the keys are weak, then the other lazyvar indices in them can be collected just fine if move to the lazyvar while `OnDirty` is kept (because the string is used too much to be collected).

2023-03-16 06:10 UTC, Hdt80bro commented on lua/lazyvar.lua
>          end
It is expected to be an unlikely branch, so using the cheaper `if` statement should be faster.

2023-03-16 06:19 UTC, 4z0t commented on lua/lazyvar.lua
>          end
I would say that assert us better here from readable perspective and performance as well.

2023-03-16 08:27 UTC, Garanas commented on lua/lazyvar.lua
>          end
Is assert an engine call?

2023-03-16 08:31 UTC, Hdt80bro commented
I actually don't think strings get collected at all, so if the values are strong, then it should be fine.

2023-03-16 09:27 UTC, Hdt80bro commented on lua/lazyvar.lua
>          end
I agree that it'd be more readable, but unfortunately the file is being hyperoptimized due to how much it gets used so that's not a priority. By theory, I don't agree that all of the extra setup required for a global call, function call setup on the Lua end, the C <-> Lua interop, and cleanup would be more performant than a simple `if` statement that bakes the comparison into the jump. If it actually is noticeable in practice though, I think those would be good benchmarks to have.

The other interesting thing to consider is that we don't use `assert` at all in our game code, so it seems that it'd go against the implicit conventions we have.

2023-03-16 09:28 UTC, Garanas commented on lua/ui/game/worldview.lua
> -        origLeft = viewLeft.Left.compute
Can someone help explain to me what is happening here, why does this code exist?

2023-03-16 09:55 UTC, Hdt80bro commented on lua/ui/game/worldview.lua
> -        origLeft = viewLeft.Left.compute
It makes sure that the left and right views are setup to the frame for the correct number of views visible. It does this by retaining the original layout functions applied to the views (which appear to be just the stock `return parent.Left()` functions) when the UI is show and applying the layouts on the views (half the root frame for dual view, full otherwise). It then reverts when the UI is hidden, hiding the world views. I'm actually not sure when `GetFrame(parentForFrame:GetRootFrame():GetTargetHead())` wouldn't just be `parentForFrame:GetRootFrame()` so it appears like a logically sound but redundant precaution.

2023-03-19 11:41 UTC, Garanas commented
@Hdt80bro / @4z0t I'll be merging this later today. The code is a lot more difficult to understand, but I don't feel like it requires any future changes. Especially after the changes of 4z0t where it now also supports the value `false`

2023-03-20 10:23 UTC, merged