Refactor Shield-Structure/Units to use ShieldEffectsComponent #4628
FAForever/fa pull request #4831
Opened 2023-03-24 17:17 UTC by scarress

#4628 

Refactored following units to use the new  ShieldEffectsComponent:
UEB4301, URB4202, URB4204, URB4205, URB4206, URB4207, XES205, XSB4202, XSB4301

Added bone name as to the cybran shield-gens and UEF-shield boat, so OnShieldEnabled function knows which bone to attach the emitters to. 

![image](https://user-images.githubusercontent.com/23396667/227595065-5678b6b1-4f76-4385-be45-083e6cf83225.png)

![Screenshot from 2023-03-23 17-28-49](https://user-images.githubusercontent.com/23396667/227592692-870cecd6-773a-446b-b1f4-5b9c1d7335c8.png)

2023-03-24 22:50 UTC, Garanas requested changes
Good start - a few more tweaks and you're there.

Could you also include the Seraphim mobile shield?

2023-03-24 22:50 UTC, Garanas commented on units/URB4206/URB4206_script.lua
>  URB4206 = ClassUnit(CShieldStructureUnit) {
Forgot to inherit the component here

2023-03-24 22:50 UTC, Garanas commented on units/URB4202/URB4202_script.lua
> +        -- LOG(self.ShieldEffectsBone)
You can remove this comment

2023-03-24 22:50 UTC, Garanas commented on units/XSB4202/XSB4202_script.lua
> +XSB4202 = ClassUnit(SShieldStructureUnit, ShieldEffectsComponent) {
Needs the `ShieldEffectsScale` field set to 0.75 in the class

2023-03-24 22:50 UTC, Garanas commented on units/XSB4202/XSB4202_script.lua
> -            table.insert(self.ShieldEffectsBag, CreateAttachedEmitter(self, 0, self.Army, v):ScaleEmitter(0.75))
(continues from previous comment)

See the scale here, which is set to `0.75`

2023-03-24 22:50 UTC, Garanas commented on units/XSB4202/XSB4202_script.lua
> +        if self.ShieldEffectsBag then
Maybe better to call `ShieldEffectsComponent.OnShieldDisabled(self)` here? Not sure if it is equivalent

2023-03-24 22:50 UTC, Garanas commented on units/XSB4301/XSB4301_script.lua
> -        if self.ShieldEffctsBag then
Interesting typo, this if statement code would never pass this if statement

2023-03-25 01:03 UTC, scarress commented on units/XSB4202/XSB4202_script.lua
> +XSB4202 = ClassUnit(SShieldStructureUnit, ShieldEffectsComponent) {
Ahh i missed that one, added now :)

2023-03-25 01:03 UTC, scarress commented on units/XSB4202/XSB4202_script.lua
> +        if self.ShieldEffectsBag then
True, should do the same thing, as long as it is null checked first.

2023-03-25 01:03 UTC, scarress commented on units/XSB4301/XSB4301_script.lua
> -        if self.ShieldEffctsBag then
Yea, and it were two places :S

2023-03-25 01:06 UTC, scarress commented
Ahh missed the Seraphim mobile shield :D should be covered now aswell :)

2023-03-25 07:15 UTC, Garanas approved these changes

2023-03-25 07:15 UTC, merged