Add new event when ACU enters transporter.
FAForever/fa pull request #4857
Opened 2023-04-02 20:27 UTC by rigomate

As seen in the discord suggestion channel, this could be a handy event for casters.
Whenever an ACU is put into a transport, there is likely some action going to take place.
So getting notified about this when casting could put the caster in the middle of the action.

The event is only created for replays, as it needs to be hidden from the enemy team.

2023-04-02 22:24 UTC, 4z0t requested changes
You'd also have to put some changes in `UserSync.lua`

2023-04-02 22:24 UTC, 4z0t commented on lua/defaultunits.lua
> +        if SessionIsReplay()  and (unit.UnitId == 'url0001' or unit.UnitId == 'ual0001' or unit.UnitId == 'xsl0001' or unit.UnitId == 'uel0001') then
Use category matching.

2023-04-02 22:24 UTC, 4z0t commented on lua/defaultunits.lua
> +            local AcuEntersTransporter = events.ACUEntersTransporter or { }
no need for this shinanigans.

2023-04-03 06:42 UTC, Garanas commented on lua/defaultunits.lua
> +            local AcuEntersTransporter = events.ACUEntersTransporter or { }
What do you mean, no need? 😄 

This pattern prevents several table operations

2023-04-03 10:15 UTC, 4z0t commented on lua/defaultunits.lua
> +            local AcuEntersTransporter = events.ACUEntersTransporter or { }
How often do you put your acu in a transport? 🙃

2023-04-03 10:41 UTC, Garanas commented on lua/defaultunits.lua
> +            local AcuEntersTransporter = events.ACUEntersTransporter or { }
Not that often, but it is good practice. Ideally at some point we'd create an interface that does it for you but today is not that day yet

2023-04-03 20:20 UTC, rigomate commented on lua/defaultunits.lua
> +        if SessionIsReplay()  and (unit.UnitId == 'url0001' or unit.UnitId == 'ual0001' or unit.UnitId == 'xsl0001' or unit.UnitId == 'uel0001') then
Thanks for the pointer, I was sure there would be something better to this.

2023-04-03 21:38 UTC, rigomate commented
> You'd also have to put some changes in `UserSync.lua`

Can you elaborate why that would be necessary?
I could just hook into this with a mod to get access to the information.
Like here:
https://github.com/rigomate/SupremeScoreBoard/blob/17055f312a8c652eda145946ddeca90482dd9f8e/hook/lua/UserSync.lua#L39

Thanks!

2023-04-04 18:40 UTC, rigomate commented
> 



> Observer is better than hooking, and we want to move towards using observers.

Ok, I will look into that, and modify the pull request.
Is there maybe a pointer for me for an existing pattern?

2024-06-12 11:28 UTC, MrRowey commented
Closing this PR for now as it has gone over a year with out any progress can be re-opened if needed

2024-06-12 11:28 UTC, closed without merging