Update mod information for FAF
FAForever/fa pull request #4960
Opened 2023-05-22 19:00 UTC by Hdt80bro

Updates the documentation found in `MODS.LUA`, including old unimplemented features / bad documentation, new features FAF added, and touches on some of the interoperability with the FAF client.

2023-05-22 21:28 UTC, Garanas commented
@The-Balthazar would you have the time to review this pull request?

2023-05-23 16:40 UTC, The-Balthazar commented on lua/MODS.LUA
>      uid = B019FBEE-E411-11DB-AFAE-13D355D89593
The uid value should be in quotation marks.

2023-05-23 16:42 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- mod during development. The default is true.
Another use for this value being false is for defining dummy mods that contain other mods, since the game supports nested mods even if the client doesn't.

2023-05-23 16:47 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- be active. The default is false. Note that this precludes the use of `conflicts`.
This is somewhat an aside, but I've never seen a good reason to have this `true`.

2023-05-23 16:53 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- Note that this is unrelated to the `mod_icons.lua` file explained below.
Unless it's changed since I last checked, a dds wont load in the client, and it's relative to root, not to the mods folder.

2023-05-23 16:56 UTC, The-Balthazar commented on lua/MODS.LUA
> +If an active mod has any .bp files defining units, they will be automatically included during
active *sim* mod

2023-05-23 17:03 UTC, The-Balthazar commented on lua/MODS.LUA
> +Second, a mod can hook the `/lua/system/Blueprints.lua` file and override the `ModBlueprints` to
It's a bit structurally weird to explain a thing that can be done with a hook before explaining how to actually hook a file.

2023-05-23 17:08 UTC, The-Balthazar commented on lua/MODS.LUA
> +units. This is one of the few times a UI mod is allowed to modify things in the simulation
It's probably more accurate to say that the sim loads them from the UI mod, rather than the UI actually having any power in the situation.

2023-05-23 17:12 UTC, The-Balthazar commented
I probably should have marked all that as a review. I wasn't actually planning to go through the whole of it right now.

2023-05-24 02:55 UTC, Hdt80bro commented
Oh that's quite alright. It's good to have any sort of feedback - some of what you commented was old stuff I wasn't sure what to do with, but now I have an idea of what to change. Thanks!

2023-05-24 03:07 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- Note that this is unrelated to the `mod_icons.lua` file explained below.
Good catch - it actually defaults to `/textures/ui/common/dialogs/mod-manager/generic-icon_bmp.dds` not a file in the mod folder as well. Not that the FAF client cares, of course.

2023-05-24 03:10 UTC, Hdt80bro commented on lua/MODS.LUA
> +   by a lua file, this only really affects shaders, which are accessed by the game engine directly)
Mmh, but that stems from how blueprints are loaded, not because the files are overwritten

2023-05-24 03:22 UTC, Hdt80bro commented on lua/MODS.LUA
> +   after the game launches).
That's what I thought, but when I checked the code, it only looked like it would work for maps.

2023-05-24 03:24 UTC, Hdt80bro commented on lua/MODS.LUA
> +   after the game launches).
Oh we *do* [import](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/ui/lobby/lobby.lua#L89) all lobby options of *all* mods in the user's mod folder (regardless of if they're used). That is good document.

2023-05-24 03:33 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- If true, one player can have it active independently of the other players.
That's fair - though it doesn't even prevent access to sim files, the UI simply doesn't use them.

2023-05-24 03:35 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- mod during development. The default is true.
Wouldn't making them unselectable be better?

2023-05-24 07:34 UTC, Hdt80bro commented on lua/MODS.LUA
> +units. This is one of the few times a UI mod is allowed to modify things in the simulation
I can change the wording to be passive, but the UI mod does have that power - probably too much. I've already found a way for a UI mod to exploit this.

2023-05-24 12:25 UTC, Garanas commented on lua/MODS.LUA
> +    -- Note that this is unrelated to the `mod_icons.lua` file explained below.
It can be a `png` or other 'normal' file formats, the game can read those

2023-05-24 12:26 UTC, Garanas commented on lua/MODS.LUA
> +units. This is one of the few times a UI mod is allowed to modify things in the simulation
I'd like to know more about that exploit 😄

2023-05-25 04:16 UTC, The-Balthazar commented on lua/MODS.LUA
> +   by a lua file, this only really affects shaders, which are accessed by the game engine directly)
If the point of the statement is avoiding conflicts, then that's not an important destinction.

2023-05-25 04:20 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- mod during development. The default is true.
Setting them to unselectable would allow things outside of the game, such as the client, to enable them, which would defeat the whole point and also load all blueprints from all contained mods, since they are technically also within the container mod.

2023-05-25 04:25 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- Note that this is unrelated to the `mod_icons.lua` file explained below.
`png` or `jpg` are what I'd recommend for being readable by both the client and the game.

2023-05-25 04:26 UTC, The-Balthazar commented on lua/MODS.LUA
> +units. This is one of the few times a UI mod is allowed to modify things in the simulation
Did we not do a good enough job sandboxing?

2023-05-26 20:23 UTC, Hdt80bro commented on lua/MODS.LUA
> +   by a lua file, this only really affects shaders, which are accessed by the game engine directly)
Filename conflicts and replacement, not logical conflicts in general. I'll add the distinction.

2023-05-27 16:34 UTC, The-Balthazar commented on lua/MODS.LUA
> +If an active sim mod has any .bp files defining units, they will be automatically included during
You could change this to
> If an active sim mod has any .bp files,

And it'll still be true and technically more accurate, since it'll load non-unit bps too.

2023-05-27 16:34 UTC, The-Balthazar commented on lua/MODS.LUA
> +override some fields while leaving others intact (possibly also changed by other mods).
This would be better split into two clauses, with the `BlueprintId` part being on the end of
> The blueprint id will be determined from the source file name if not specified.

stating how the ID's specified outside of sourcing it from the filename, and the second part being that it'll merge or replace if the ID, however it evaluated it, matches an existing blueprints ID, since this currently implies that you can only merge or replace if you define `BlueprintId`.
It might also be a good place to mention that you can have multiple blueprints in a single `.bp` file if they specify `BlueprintId`. (Technically I think one/the first can get away without, but that's asking for trouble.)

2023-05-27 18:50 UTC, Hdt80bro commented on lua/MODS.LUA
> +If an active sim mod has any .bp files defining units, they will be automatically included during
Hmm, it's in the section on units, but that's fine I guess

2023-05-27 18:57 UTC, Hdt80bro commented on lua/MODS.LUA
> +override some fields while leaving others intact (possibly also changed by other mods).
That's a good call.

I'd ideally prefer to completely include all information that describes how things work, but I suspect the bit about having multiple blueprints per file might be something better left out.

2023-05-28 16:30 UTC, The-Balthazar commented on lua/MODS.LUA
> +override some fields while leaving others intact (possibly also changed by other mods).
Having multiple blueprints in a single file is very useful for doing a lot of small similar changes to several units that isn't worth setting up a `blueprints.lua` for, like for example:
```lua
UnitBlueprint {
    Merge = true,
    BlueprintId="uab5101",	--Aeon--
    BuildIconSortPriority = 150,
}
UnitBlueprint {
    Merge = true,
    BlueprintId="xsb5101",	--Seraphim--
    BuildIconSortPriority = 150,
}
UnitBlueprint {
    Merge = true,
    BlueprintId="ueb5101",	--UEF--
    BuildIconSortPriority = 150,
}
UnitBlueprint {
    Merge = true,
    BlueprintId="urb5101",	--Cybran--
    BuildIconSortPriority = 150,
}
```
The part that's not worth mentioning is that you can functionally get away with not defining `BlueprintId` on one of them and have that one evaluate from the filename.

2023-05-28 16:36 UTC, The-Balthazar commented on lua/MODS.LUA
> +If an active sim mod has any .bp files defining units, they will be automatically included during
Saying "bp files defining units" implies that other blueprints function differently. It's like saying "I used to drink." and following up with "I still do, but I used to as well." Technically not wrong, but has implications that are wrong.

2023-05-29 20:02 UTC, Hdt80bro commented on lua/MODS.LUA
> +If an active sim mod has any .bp files defining units, they will be automatically included during
It sounds like you'd rather have this be a section on blueprints in general instead of units. That's fine.

2023-05-29 20:07 UTC, Hdt80bro commented on lua/MODS.LUA
> +override some fields while leaving others intact (possibly also changed by other mods).
I can see that, I'll update it

2023-05-31 08:31 UTC, The-Balthazar commented on lua/MODS.LUA
> +      file, this only really affects shaders, which are accessed by the game engine directly and
Aren't sounds in a similar situation to shaders?

2023-05-31 08:31 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
Is this accurate? How does it determine which is the most recent uid if not by version number?

2023-05-31 08:31 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- Optional copyright info. If absent, the mod author is presumed to maintain full ownership of
Except as defined in the FAF vault license.

2023-05-31 08:31 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- truncated in-game if over 20 characters. Make sure this reflects who is uploading the mod to
Do we really want to be encouraging the uploader to put their name in the author field if they aren't the author?

2023-05-31 08:31 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- use the requires mechanism instead however). The default is true.
Using the requires mechanism isn't necessarily an appropriate alternative to mod packs if you're using packs to avoid uploading like 40 separate mods, which is what I use it for.

2023-05-31 08:32 UTC, The-Balthazar commented on lua/MODS.LUA
> +suffix (e.g. `"_unit.bp"`). For multiple blueprints in a file, be sure to specify each
Since this is now generic to bp files rather than units, this should specify that units default to lowercase filename sans `_unit.bp`, while all other blueprints default to lowercase filepath including `_proj.bp` ect..

2023-06-02 00:37 UTC, Hdt80bro commented on lua/MODS.LUA
> +      file, this only really affects shaders, which are accessed by the game engine directly and
No, the sound banks are still referenced in Lua like textures.

2023-06-02 00:38 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
The vault uses upload time

2023-06-02 00:39 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- truncated in-game if over 20 characters. Make sure this reflects who is uploading the mod to
Don't they become responsible for the uploaded mod at that point?

2023-06-02 00:40 UTC, Hdt80bro commented on lua/MODS.LUA
> +	-- to keep mods differentiated. I'd recommend using a GUID or Guaranteed Unique ID.
Yup, another leftover

2023-06-02 00:42 UTC, Hdt80bro commented on lua/MODS.LUA
> +suffix (e.g. `"_unit.bp"`). For multiple blueprints in a file, be sure to specify each
The reality is that it doesn't care what the ending is, it truncates everything from `_` to `.bp`

2023-06-02 00:49 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- Optional copyright info. If absent, the mod author is presumed to maintain full ownership of
Would a good way to say that be it must be compatible with https://content.faforever.com/tos/vault-license.html and defaults to that if absent?

2023-06-02 00:53 UTC, Hdt80bro commented on lua/MODS.LUA
> +suffix (e.g. `"_unit.bp"`). For multiple blueprints in a file, be sure to specify each
Oh, it does only call `SetShortId` for `UnitBlueprint` and `SetBackwardsCompatId` for everything else. That's a good catch.

2023-06-02 00:54 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- use the requires mechanism instead however). The default is true.
Mmh, that's an interesting perspective. I'll remove that bit.

2023-06-03 13:18 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
Compared to what though for things not in the vault? Does the vault just assume it's more up to date than local files?

2023-06-03 13:27 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- truncated in-game if over 20 characters. Make sure this reflects who is uploading the mod to
It's an 'author' field, not a 'who is responsible' or a 'care of' field. The vault tracks the uploader separately, and if the uploader hasn't actually contributed to the content then they aren't an author, regardles of if they have permission to upload or not.
I delegated uploading my main mods to someone else. They were not an author of the content and I would not have been happy if they put their name in the author field or if they were encouraged to do so.

2023-06-03 13:34 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- Optional copyright info. If absent, the mod author is presumed to maintain full ownership of
"If absent, mod author is presumed to reserve all rights except as required by ~~"
This is just documentation after all, not an actual part of any license or rights agreement, so we can't assume or state that it's anything more than would be required.

2023-06-03 13:39 UTC, The-Balthazar commented on lua/MODS.LUA
> +      file, this only really affects shaders, which are accessed by the game engine directly and
They aren't mounted inside the mod dir though, they're mounted to `/sounds/`

2023-06-03 17:58 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
My understanding is that it takes the UID of the local mod and looks up the uploaded time of that UID to compare - I'm not sure what happens when there's a conflict between a local unuploaded mod and when hosting with a mod of the same name that's in the vault. Sounds like a weird edge case, though I suspect it just leaves the unuploaded one alone and would update the in the vault. Perhaps @Sheikah45 can offer some insight or tell me if I'm totally off base.

2023-06-03 17:59 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- Optional copyright info. If absent, the mod author is presumed to maintain full ownership of
I'll remove it then.

2023-06-03 18:00 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- truncated in-game if over 20 characters. Make sure this reflects who is uploading the mod to
I'll remove that bit then

2023-06-03 18:18 UTC, Hdt80bro commented on lua/MODS.LUA
> +      file, this only really affects shaders, which are accessed by the game engine directly and
Ah, sound mountpoints. So those wouldn't be untouchable like shaders and could produce conflicts then (when they do end up working correctly) - I'll add that. I didn't realize only maps could mount movies, that's good to know.

2023-06-03 20:09 UTC, Sheikah45 commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
It doesn't use uploaded time. FAF track versions of the mods separately. Each new upload increments the version by one of the mod. We use UID to find the mod and look up its most recent uploaded version and install that. It will overwrite any non matching local mods.

2023-06-04 05:28 UTC, Hdt80bro commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
So it's something like this @Sheikah45 ?
* A mod author uploads a mod named "Mod Name" to the vault with a particular UID and FAF attaches an internal version number to it - the version in the mod info is cosmetic.
* A player downloads the mod.
* Later, the mod author updates the mod by uploading a mod with the same "Mod Name" name but with a different UID. FAF recognizes the mod as being a newer version of the same mod because it has the same name with a different UID and the internal version number is incremented - hopefully the mod author thought to change the mod info version.
* The player then hosts with the "Mod Name" mod.
* FAF then looks up the most recent UID of the mod named "Mod Name" based on the internal version, finds that this new mod is more recent than the one in local storage, and auto-updates the old mod.

2023-06-04 08:32 UTC, Sheikah45 commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
Correct

2023-06-05 21:06 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
If the `mod_info` `version` is entirely cosmetic, why is it restricted to integers?

2023-06-05 23:51 UTC, Sheikah45 commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
Ah nevermind just double checked and we do use the version as defined in the lua. But the uid is still used to query the mods so trumps anything else.

2023-06-10 14:48 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
Why is this marked as resolved when it still says the version number doesn't matter after it was established that it does? @Sheikah45 could you clarify specifically how it is used?

2023-06-10 14:48 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- Required name(s) of author(s). Shows up as `"UNKNOWN"` if left blank. Will be begin to be
Typo "Will be begin to be" should probably be "Will be"

2023-06-10 14:48 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- `"/textures/ui/common/dialogs/mod-manager/generic-icon_bmp.dds"`. The FAF client does cannot
Typo "does cannot"

2023-06-10 14:48 UTC, The-Balthazar commented on lua/MODS.LUA
> +    }
Is `requires` required if `requiresNames` is defined with the same -and more- data? Seems redundant.

2023-06-10 14:48 UTC, The-Balthazar commented on lua/MODS.LUA
> +units. This is one of the few times a UI mod will be able to have an affect things in the simulation
Typo; "to have an affect things", should be either "to affect things" or "to have an effect on things"

2023-06-10 14:57 UTC, Sheikah45 commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
It is used with an existence check if that version of the mod exists in the vault already and to name the zip folder

2023-06-10 15:46 UTC, The-Balthazar commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
Does that mean it's used to indicate which is newer rather than a timestamp?

2023-06-10 16:20 UTC, Sheikah45 commented on lua/MODS.LUA
> +    -- mods (based on the most recent `uid` - the version number does not matter and is only used
Yes

2023-06-13 03:12 UTC, Hdt80bro commented on lua/MODS.LUA
> +    }
Currently, yes. The intention is that `requires` is the array, and `requiresNames` is the look up for the name of the UID. The same could be done with `before`, `after`, and `conflicts`. However, combining required data with optional data is a little weird, particularly because `requiresNames` can be partial. I don't think we can change this at this point though.

2023-06-16 07:40 UTC, The-Balthazar requested changes

2023-06-16 07:40 UTC, The-Balthazar commented on lua/MODS.LUA
> +   https://wiki.faforever.com/en/Vault-Rules
Dead link. It's currently `https://wiki.faforever.com/en/Development/Vault/Vault-Rules`, although I don't like the redundancy of `Vault/Vault`, so I'm going to see about getting it changed to `https://wiki.faforever.com/en/Development/Vault/Rules` and also inquire about redirects, 'cause this is a change that has broken a lot of links.

Should also mention that they need to follow the FAF rules as well as the vault rules, `https://faforever.com/rules`, which prohibit reclaim macros and autoclickers.

2023-06-16 07:50 UTC, The-Balthazar commented on lua/MODS.LUA
> +   https://wiki.faforever.com/en/Vault-Rules
It's now `https://wiki.faforever.com/en/Development/Vault/Rules`

2023-06-16 07:54 UTC, The-Balthazar approved these changes

2023-06-16 08:00 UTC, merged