Adjust engineer filter key
FAForever/fa pull request #5249
Opened 2023-07-20 22:31 UTC by ChessBerry

This PR adds two changes to the reintroduced SelectHighestEngineerAndAssist hotkey.

1. It treats T3 engies and SACUs the same for the purpose of selecting the highest tech level constructors. This is preferable as the tech level a unit can produce is more important than what the unit actually is, so with the new behavior where we select not one but all equivalent engies, we want to also treat t3 engies and sacus the same.

2. If you have multiple different factions in your selection, it now selects the faction's engies of which you have the most of for the highest tech level. For example, if you have 4 t3 uef engies and 2 t3 aeon engies, it will select the 4 t3 uef engies and have the 2 aeon engies assist those.
This mostly matters in fullshare team games when you get the base of an ally but in those situations such a hotkey can be a lifesaver.

2023-07-20 22:39 UTC, ChessBerry commented
Note that I'm guessing that there is a much smarter way to count the number of units of each faction than using the utility function CalcTableLength I have written above, but a quick google search just told me that lua tables by default seemingly don't have a length parameter.
Still, I'm guessing there already is a better function in the FA repo that does this that I'm not aware about

2023-07-21 05:17 UTC, Garanas commented
Is this written with ChatGPT?

2023-07-21 07:53 UTC, ChessBerry commented
> Is this written with ChatGPT?

What? xd

Tbf I have been using ChatGPT quite a bit over the last months so maybe it has rubbed off on me. 

But what if if this too is written by ChatGPT and I just didn't notice? What if everything I write is actually ChatGPT?? WHAT IF I AM JUST SIMULATED BY CHATGPT??? AM I REAL?!?

2023-07-21 07:57 UTC, Garanas commented
And that is how I accidentally triggered an existential crisis 😄 

I'll rewrite it

2023-07-26 13:56 UTC, HUSSAR-mtrela requested changes

2023-07-26 13:56 UTC, HUSSAR-mtrela commented on lua/keymap/misckeyactions.lua
> +        nr_of_units_for_that_faction = CalcTableLength(u)
replace CalcTableLength with global function called: table.getsize

2023-07-26 13:56 UTC, HUSSAR-mtrela commented on lua/keymap/misckeyactions.lua
> +function CalcTableLength(tbl)
remove CalcTableLength function since it is the same as table.getsize function

2023-07-26 13:56 UTC, HUSSAR-mtrela commented on lua/keymap/misckeyactions.lua
> +        local tech3_and_sACUs = EntityCategoryFilterDown((categories.SUBCOMMANDER + categories.TECH3) - categories.COMMAND, selection)
remove "_" in name of variable and use camelCase for variable

2023-07-26 13:56 UTC, HUSSAR-mtrela commented on lua/keymap/misckeyactions.lua
> +        local highest_tech_engies_and_sacus_of_majority_faction = nil
remove "_" in name of variable and use camelCase for variable

2023-07-26 13:56 UTC, HUSSAR-mtrela commented on lua/keymap/misckeyactions.lua
> +    local faction_categories = {categories.UEF, categories.CYBRAN, categories.AEON, categories.SERAPHIM}
remove "_" in name of variable and use camelCase for variable

2023-07-26 13:56 UTC, HUSSAR-mtrela commented on lua/keymap/misckeyactions.lua
> +    local units_factions = {}
remove "_" in name of variable and use camelCase for variable

2024-06-08 20:10 UTC, ChessBerry commented
Apologies, I completely forgot this PR existed..

I merged it with the current develop branch, implemented the suggestions by @HUSSAR-mtrela and fixed a bug where engies accidentally assisted army units sometimes.

I think it works as intended now and will try my hardest to not forget the existence of this PR again for a year :P

2024-06-08 21:19 UTC, ChessBerry commented
Should maybe ping @Garanas here too

2024-06-10 23:13 UTC, lL1l1 requested changes

2024-06-10 23:13 UTC, lL1l1 commented on lua/ui/game/hotkeys/filter-engineers.lua
>              -- do nothing
```suggestion
```

2024-06-10 23:13 UTC, lL1l1 commented on lua/ui/game/hotkeys/filter-engineers.lua
> +        local tech1Engineers = EntityCategoryFilterDown(categories.ENGINEER * categories.TECH1 - categories.COMMAND, selection)
[Suggested change] Cache the category calculation in a local variable at the top of the file. Like here:
https://github.com/FAForever/fa/blob/4eed87d6df67e9691b259eefb7326c7b4227c944/lua/shield.lua#L98-L99

2024-06-12 13:41 UTC, ChessBerry commented on lua/ui/game/hotkeys/filter-engineers.lua
> +    local factionCategories = {categories.UEF, categories.CYBRAN, categories.AEON, categories.SERAPHIM}
Implemented

2024-06-12 13:41 UTC, ChessBerry commented on lua/ui/game/hotkeys/filter-engineers.lua
> +    return factionsOfUnits[factionNr]
Implemented

2024-06-12 13:41 UTC, ChessBerry commented on lua/ui/game/hotkeys/filter-engineers.lua
> +        local tech1Engineers = EntityCategoryFilterDown(categories.ENGINEER * categories.TECH1 - categories.COMMAND, selection)
Implemented

2024-06-12 13:45 UTC, ChessBerry commented on lua/ui/game/hotkeys/filter-engineers.lua
>  --- Filters your selection to the highest tech of engineers. All other engineers assist one of those engineers.
I have updated the hotkey description in `keydescriptions.lua` but I haven't touched `keydescriptions.lua` because seemingly none of the advanced order hotkeys have an entry there yet.

2024-06-12 13:46 UTC, ChessBerry commented on lua/ui/game/hotkeys/filter-engineers.lua
> +        local tech1Engineers = EntityCategoryFilterDown(categories.ENGINEER * categories.TECH1 - categories.COMMAND, selection)
Implemented the sparky filtering with a priority between t1 and t2 engies.

I'll leave the fully general buildable category filtering for a future PR.

2024-06-17 12:53 UTC, ChessBerry commented on lua/ui/game/hotkeys/filter-engineers.lua
> +        if highestTechEngiesAndSacusOfMajorityFaction and table.getn(selection) ~= table.getn(highestTechEngiesAndSacusOfMajorityFaction) then
I think it's preferable to keep the callback when units found equals selection as the callback cancels queued orders and this behavior should imo be consistent whenever you use the hotkey.

2024-06-17 12:54 UTC, Garanas approved these changes

2024-06-17 12:56 UTC, merged