Multiple pod orders
FAForever/fa pull request #5370
Opened 2023-08-29 15:29 UTC by clyfordv

Can select multiple pods/pod platforms when multiples of their counterpart is selected. Stock behavior remains unchanged.

2023-09-05 17:03 UTC, Garanas commented on lua/ui/game/orders.lua
> +        if next(assistingUnits) then
Please use `table.empty` instead of `next` to check if a table is empty

2023-09-05 17:04 UTC, Garanas reviewed
It appears to be all good. Looked into some of the more common UI mods and none of them touch this aspect of the code. Perhaps @Hdt80bro or @4z0t could also give it a view, to be certain?

Also tested it with BlackOps. The mod pack has various drone carriers. This also works fine there.

2023-09-05 19:51 UTC, 4z0t requested changes

2023-09-05 19:51 UTC, 4z0t commented on lua/ui/game/orders.lua
> +        if self._mixedIcon then
why is it here?

2023-09-05 19:51 UTC, 4z0t commented on lua/ui/game/orders.lua
> +    if not table.empty(units) and (next(EntityCategoryFilterDown(categories.PODSTAGINGPLATFORM, units)) or next(EntityCategoryFilterDown(categories.POD, units))) then
use separate named variables for readability

2023-09-05 19:51 UTC, 4z0t commented on lua/ui/game/orders.lua
> +        self._mixedIcon = Bitmap(self, UIUtil.UIFile('/game/orders-panel/question-mark_bmp.dds'))
create icon and hide if not needed. no need for create/destroy

2023-09-05 22:29 UTC, clyfordv commented on lua/ui/game/orders.lua
> +        if self._mixedIcon then
This is taken straight from ScriptButtonOrderBehavior. If the unit states are mixed (and displaying a question mark) when the state is changed, destroy the question mark (because all the pods will have the same state now).

2023-09-05 22:33 UTC, clyfordv commented on lua/ui/game/orders.lua
> +        self._mixedIcon = Bitmap(self, UIUtil.UIFile('/game/orders-panel/question-mark_bmp.dds'))
Also taken from from ScriptBitInitFunction--question mark will only be created once (when the other alt orders are) and will only be hidden/destroyed once (because the unit states can't be "unmixed" once selected). Didn't see a reason to break consistency with ScriptBit.

2023-09-06 10:30 UTC, 4z0t commented on lua/ui/game/orders.lua
> +        self._mixedIcon = Bitmap(self, UIUtil.UIFile('/game/orders-panel/question-mark_bmp.dds'))
I don't like copy-pasting and I'd suggest to make it as separate class to utilize. I'll approve, but would be much better to have no code dupolication.

2023-09-06 10:35 UTC, 4z0t requested changes

2023-09-06 10:35 UTC, 4z0t commented on lua/ui/game/orders.lua
> +    local PodStagingPlatforms = EntityCategoryFilterDown(categories.PODSTAGINGPLATFORM, units)
camelCase for variables.

2023-09-07 15:05 UTC, Garanas commented on lua/ui/game/orders.lua
> +        self._mixedIcon = Bitmap(self, UIUtil.UIFile('/game/orders-panel/question-mark_bmp.dds'))
For the purpose of this change I think it is fine. If we'd introduce new files then the standard would be higher, like @clyfordv already did with #5378

2023-09-17 17:13 UTC, merged