add semitransparent background for unit counter
FAForever/fa pull request #5413
Opened 2023-09-10 01:47 UTC by HUSSAR-mtrela

Adds semitransparent background for unit counter to improve visibility of displaying text which fixes  issue #2854

The new SetColorShadow() works better than SetDropShadow() for displaying text, e.g. white unit count over bright blue background of air units

Units counter with new semitransparent background:
![image](https://github.com/FAForever/fa/assets/11665978/e37354cf-1da4-4b07-9d74-e92444c7457e)

this work similar to existing semitransparent background used in displaying keybinding in construction menu:
![image](https://github.com/FAForever/fa/assets/11665978/84d1b482-527f-4405-a17b-7fb2202cf3e6)

Note above screenshots where taken with a mod that increase size of strategic icons so this is why they appear to overlap with unit counter. @Garanas should we add an option to configure placement of strategic icons on left/right side of the unit icon?

2023-09-10 06:31 UTC, Garanas commented
> @Garanas should we add an option to configure placement of strategic icons on left/right side of the unit icon? Also, I could add options to configure color of unit counter and background if you want?

I don't see the need to customize it further, the overlap is minimal. It'd be better I think if we draw the strategic icon on top of the background

2023-09-13 14:02 UTC, HUSSAR-mtrela commented
@Garanas I checked implementation of construction.lua and there are a lot of duplicated code and low performance code so I will make a few other improvements in this PR. Please do not merge it for now.

2023-09-18 06:03 UTC, Garanas commented
@HUSSAR-mtrela could you elaborate as to what you'd like to improve, and how you'd want to do that?

2023-09-22 19:14 UTC, HUSSAR-mtrela commented
@Garanas I'm working on this kind of improvements:
- move logic for getting icons and basic info about units to utility functions for reuse by other UI
- improved performance by caching common data that is generated for each unit and build option
- use classes to encapsulate some UI elements of construction.lua so we can re-use in avatar.lua
- add a few options to configure appearance of units in construction menu

above improvements should help us later do overhaul of the whole construction like you are planning with the lobby.

2023-10-01 08:24 UTC, Garanas commented
@HUSSAR-mtrela  Your work may have a conflict with https://github.com/FAForever/fa/pull/5484

2023-10-20 23:27 UTC, 4z0t requested changes
Don't stick to old style.

2023-10-20 23:27 UTC, 4z0t commented on lua/maui/text.lua
> +    SetColorShadow = function(self, color, left, top, right, bottom, targetDepth, shadowDepth)
It doesn't make sense to present here.
Create an inherited class with background behind the text.

2023-10-20 23:27 UTC, 4z0t commented on lua/ui/uiutil.lua
> +function CreateBackground(target, color, left, top, right, bottom, targetDepth, bitmapDepth)
Create a class. Use Layouter.

2024-06-12 11:38 UTC, MrRowey commented
Closing PR as it is not currly necessary and change isn't flowing new style as well as not being active for almost 10 months

2024-06-12 11:38 UTC, closed without merging