Draft: Improve ACU upgrade descriptions
FAForever/fa pull request #5566
Opened 2023-10-20 18:24 UTC by Basilisk3

**This PR aims to:**

- Add information, that was previously missing
- Fix outdated information
- Fix wording/spelling issues

The reason for doing this are simple. The exact stat changes of a lot of the upgrades are not shown in the UI. For a game that has an option to show the exact stats of every unit before building it, it is a bit odd, that even some of the most basic stat changes are not shown for upgrades.

2023-10-20 21:13 UTC, lL1l1 requested changes
Added/corrected some details.

2023-10-20 22:05 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0112="Doubles the main cannon's Rate-Of-Fire, and increases the range of all the ACU's weaponry.\n\n+1 Rate of fire\n+8 Main Weapon range"
I was thinking about this too. I ended up using "+1 Rate of fire" because I did not see percentages used anywhere else. This does seem better though, I will use percentages for these.

2023-10-20 22:12 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0011="Creates a protective Bubble Shield around the ACU, which protects friendly units inside it. Requires energy to run."
I am unsure about this one. The ACU is resistant to overcharge damage in general, so I would not add it here. Commenting on overspill is a good idea though. I suggest: "Shields transfer a portion of the damage received to intersecting bubbles."

2023-10-23 05:09 UTC, lL1l1 requested changes

2023-10-23 11:35 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0430="Enhances the Repair Field to grant faster restoration in a larger area, as well as providing a larger boost to the maximum HP of those units.\n\n+1500 Health (ACU only)\n+20 Re
I think I will remove the regen-floor stat, it is not useful. Describing the range of the possible regen-buff is marginally better, but something between 20 and 240 is not very insightful.

2023-10-23 11:42 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0430="Enhances the Repair Field to grant faster restoration in a larger area, as well as providing a larger boost to the maximum HP of those units.\n\n+1500 Health (ACU only)\n+20 Re
My System for now is:
- If a stat is added, the change in numbers will be mentioned first.
- Definite statements like x = y will have their number mentioned last, in order to keep them apart.

I will keep evaluating this further, I did not take a look at the wording of some of the descriptions yet.

2023-10-23 12:17 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0160="Replaces the Tech 2 engineering Suite. Grants Tech 3 and Experimental schematic access and further increases the ACU's build speed and maximum health.\n\n+58 Buildpower\n+3000
For Aeon and UEF it is only +1000. I think your way of formatting (adding on top of the T2 upgrade) is better though, I will keep it and correct the stats.

2023-10-23 12:31 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0159="Grants the ACU a long range omni Sensor and increased optical range.\n\n+54 Vision Radius\n+54 Omni Radius"
The ACU has 26 vision in its stats, which is then increased by 15% after the fact. Apparently this 15% vision buff is not applied to the Upgrade (is this intentional? Because this was technically a nerf to the upgrade). I thought the vision buff would also apply to the upgrade. Maybe this is something to investigate further in the future.

2023-10-23 12:38 UTC, Basilisk3 commented
Thanks for your help and suggestions. I will go over every single upgrade, and add further changes today/tomorrow, my changes from yesterday, were actually not finished yet. So in case you have further feedback, it is probably best to wait until I have added those changes.

2023-10-23 13:42 UTC, Garanas commented
I think these are great improvements 😃 !

2023-10-23 16:10 UTC, KionX commented
It would be better to do this through blueprint value refs.

2023-10-24 19:57 UTC, Basilisk3 commented
I think this is ready for another round of feedback.

2023-10-25 02:47 UTC, lL1l1 requested changes
In addition to the suggestions, Teleport upgrades could be changed to:
`"Adds Teleportation capability. Requires considerable energy to activate.\n\nTeleportation - Range: Infinite, Duration: 25"`

2023-10-25 02:47 UTC, lL1l1 commented on loc/US/strings_db.lua
> +Unit_Description_0165="Greatly increases Personal Shield's HP. Requires energy to run.\n\nShield regen rate = 32 HP/s\nShield recharge time = 160 seconds"
Possessive s isn't needed without a "the" before.
```suggestion
Unit_Description_0164="Creates a protective Personal Shield around the ACU. Requires energy to run.\n\nPersonal Shield - Regen Rate: 30, Recharge Time: 75"
Unit_Description_0165="Greatly increases Personal Shield HP. Requires energy to run.\n\n+17000 Personal Shield HP\n+2 Personal Shield Regen Rate\n+45 Personal Shield Recharge Time"
```
It does feel a bit silly to write +2 regen and +45 recharge time. Maybe alternatively it could be:
```suggestion
Unit_Description_0164="Creates a rapidly-recharging protective Personal Shield around the ACU. Requires energy to run.\n\nPersonal Shield - Regen Rate: 30, Recharge Time: 75"
Unit_Description_0165="Replaces the Personal Shield with a higher HP Heavy Personal Shield. Requires energy to run.\n\nPersonal Shield - Regen Rate: 32, Recharge Time: 160"
```
Rapidly-recharging seems to make sense considering that it is 106hp/sec at a rather early stage in the game, where losing 8000 HP isn't a near-future death for your ACU. I didn't add slower recharge to the heavy shield because that would conflict with describing the SACU's heavy shield which upgrades HP, regen rate, and recharge.

2023-10-25 02:47 UTC, lL1l1 commented on loc/US/strings_db.lua
> +Unit_Description_0430="Enhances the Repair Field to grant faster restoration in a larger area, as well as providing a larger boost to the maximum HP of those units.\n\n+1000 Health (ACU only)\n+10 Re
This formats it into a nice-looking table, and includes all the information someone would want to know.
```suggestion
Unit_Description_0429=Emits a field which repairs nearby allied units, as well as providing a boost to the maximum HP of those units.\n\n+500 Health (ACU only)\n+10 Regen (ACU only)\nRegen Aura - Radius: 30, HP Buff: 10%,\n%HP Regen: 2.0%, Maximum Regen:\nT1: 10, T2: 15, T3: 25, SACU: 30, T4: 40
Unit_Description_0430="Enhances the Repair Field to grant faster restoration in a larger area, as well as providing a larger boost to the maximum HP of those units.\n\n+1000 Health (ACU only)\n+10 Regen (ACU only)\nRegen Aura - Radius: 35, HP Buff: 20%,\n%HP Regen: 3.5%, Maximum Regen:\nT1: 20, T2: 50, T3: 120, SACU: 140, T4: 240"
```
![image](https://github.com/FAForever/fa/assets/82986251/74013fb6-9f62-4320-ac15-883511969127)

2023-10-25 09:34 UTC, Garanas commented
@Basilisk3 do you think it is possible to finalize this for the release next weekend (28th of October)? It doesn't need to be perfect - just needs to be an improvement 😃 . Additional details can be processed in a separate pull request

2023-10-25 10:44 UTC, Basilisk3 commented
> @Basilisk3 do you think it is possible to finalize this for the release next weekend (28th of October)? It doesn't need to be perfect - just needs to be an improvement 😃 . Additional details can be processed in a separate pull request

Sure, I will try to finalize it today.

2023-10-25 11:59 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0009="Tactical Cruise Missiles replaced by much more expensive, powerful Tactical Nuclear Missiles.\n\nInner ring damage = 12000\nOuter ring damage = 250"
If you will add those stats anyway, there is little use in having them here. I will remove them.

2023-10-25 12:07 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0011="Creates a Bubble Shield around the ACU, which protects friendly units inside its radius. If present, the shield will transfer a portion of the damage received to intersecting s
Residual is wrong here, because it is not just residual damage that is applied to the other shields. The first shield takes the full amount of damage, and then a portion of this damage is also applied to other shields. The spillover is not leftover damage, as "residual" would imply, it is additional damage, derived from the damage, the first shield sustained.

2023-10-25 12:11 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0013="Creates a protective Personal Shield around the ACU. Requires energy to run.\n\nShield regen rate = 30 HP/s\nShield recharge time = 140 seconds"
I have used the equals sign in all my other changes, for the sake of consistency, I will keep it like this for now. But this is somethign we can revisit in the future. Removing the unit of measurement is not ideal though.

2023-10-25 12:16 UTC, Basilisk3 commented on loc/US/strings_db.lua
>  Unit_Description_0015="Adds a second Engineering Drone."
This is not ideal, because this is already shown somewhere else in the UI, but I guess there is little harm in adding this either.

2023-10-25 12:25 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0112="Doubles the main cannon's Rate-Of-Fire, and increases the range of all the ACU's weaponry.\n\n+100% Rate of fire\n+8 Main Weapon range"
"Weaponry" implies all of the ACU's weapons see an increase in range, which is not the case. I have seen some players claim, that the gun upgrade also increases the range of its torpedoes. This is false.

2023-10-25 13:10 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0159="Grants the ACU a long range omni Sensor and increased optical range.\n\n+50 Vision Radius\n+54 Omni Radius"
The increase in vision radius is vastly more important for this upgrade, and the primary reason why it is used.

2023-10-25 13:43 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0165="Greatly increases Personal Shield's HP. Requires energy to run.\n\nShield regen rate = 32 HP/s\nShield recharge time = 160 seconds"
I will revisit the formatting at a later date, I think adding "rapidly-recharging" is a very good idea though. That is one of the selling points of this upgrade.

2023-10-25 13:55 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0430="Enhances the Repair Field to grant faster restoration in a larger area, as well as providing a larger boost to the maximum HP of those units.\n\n+1000 Health (ACU only)\n+10 Re
I will add the %HP Regen metric, but won't add the Regen caps for now. I think it is the least important metric of the ones displayed, and I also don't want this description to become too convoluted. There is a lot going on with this upgrade already.

2023-10-25 14:22 UTC, Basilisk3 commented
@lL1l1 Thanks for your feedback. I applied your changes where I agreed and updated the descriptions. For the next patch, I will look at improving the formatting further.

@Garanas It is not perfect, but I think, this is ready to be included in the patch now. For the next patch, I will investigate referencing the blueprint values, so the descriptions are updated automatically when a value is changed.

2023-10-25 19:45 UTC, lL1l1 commented on loc/US/strings_db.lua
> +Unit_Description_0430="Enhances the Repair Field to grant faster restoration in a larger area, as well as providing a larger boost to the maximum HP of those units.\n\n+1000 Health (ACU only)\n+10 Re
The Regen caps are very easily reached by everything except T1 and support units, so they're one of the most important stats. A complex upgrade requires a complex description so that people can fully understand it, and I don't want to see complaints like "The ilshie has 2500 HP, why am I not getting 50 regen at level 1 aura?", or 2345 regen on the Ythotha, or 164 regen on the othuum.

2023-10-25 22:58 UTC, Basilisk3 commented
> @Garanas I will investigate referencing the blueprint values, so the descriptions are updated automatically when a value is changed.

I tried to do this with string.format in this file, but it didn't work out. Can you point me into the right direction? If it is more complicated, it would probably better left to someone with more experience on this repo.

2023-10-25 23:16 UTC, Basilisk3 commented on loc/US/strings_db.lua
> +Unit_Description_0430="Enhances the Repair Field to grant faster restoration in a larger area, as well as providing a larger boost to the maximum HP of those units.\n\n+1000 Health (ACU only)\n+10 Re
I don't necessarily agree, but I have added it in for now. One problem will be the formatting, I am not happy with either of our solutions.

2023-10-25 23:42 UTC, MrRowey commented
https://www.lua.org/pil/20.html

This may help?

2023-10-26 00:22 UTC, lL1l1 commented
The data is stored this way: 
text in strings_db.lua -> alias given in unitdescription.lua (this file contains unlocalized descriptions)

It is accessed this way:
enhancement blueprint's "icon" field -> used to recreate alias in unitViewDetail:140 -> recreated alias used to retrieve unlocalized description from unitdescription.lua on unitViewDetail:419 -> the description is localized on the same line.

In the WrapAndPlaceText function there, you have access to the enhancement's blueprint so it should be pretty to check for enhancement specific fields and then add those fields into a string.format() in between :420 and :421.
There is an example of stats from blueprints being put into text on unitViewDetail:558. Since these are unit descriptions and not tooltips, make sure the %d flags are present in the strings_db file(s) (localized case) and the unitdescription.lua (unlocalized case).

2023-10-26 00:36 UTC, Basilisk3 commented
Thanks, I will have a look.

2023-10-26 06:19 UTC, merged

2023-10-26 06:20 UTC, Garanas commented
Great work @lL1l1 and @Basilisk3 , this is a great first step. The suggestions of @KionX and @lL1l1 would make it more future proof, that would be great to have 😃