Allow Hotbuild to redirect orders to exfac units like the buttons do
FAForever/fa pull request #5656
Opened 2023-11-10 15:27 UTC by gordenwunderlich

https://github.com/FAForever/fa/assets/7266458/38e0c0c2-219e-415b-ba32-ba24ee881ef9

should work for both normal and alternate hotbuild (templates not yet)

Needs more testing since I just quickly copied the code from @clyfordv but I wanted to at least put this out there.

2023-12-19 17:32 UTC, Garanas commented
@4z0t can you take the time to review this? I generally do not use hotkeys

2023-12-22 20:03 UTC, 4z0t requested changes
Follow [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

2023-12-22 20:03 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +                    if exFacUnits then
Copy pasted fragments of the code

2023-12-22 20:03 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +    local exFacs = EntityCategoryFilterDown(categories.EXTERNALFACTORY, selection)
move to separate function

2023-12-22 20:07 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +        local exFacUnits = EntityCategoryFilterOut(categories.EXTERNALFACTORY, selection)
redefinition of the local variable

2023-12-22 20:10 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +    if not table.empty(exFacs) then
EntityCategoryFilterDown returns nil if no units were found, excess check here

2023-12-22 20:15 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +        local exFacUnits = EntityCategoryFilterOut(categories.EXTERNALFACTORY, selection)
redefined local variable `exFacUnits`

2024-01-07 21:38 UTC, gordenwunderlich commented
@4z0t
I moved the filter code to a different function, that also fixes the issue of declaring the local twice.
Should I put the part with `if exFacUnits then` into a separate function as well? It feels kinda weird to hide the simple if behind another function call.

2024-01-08 12:55 UTC, 4z0t requested changes

2024-01-08 12:55 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +function translateExFacUnits(selection)
Pascal case function name.

2024-01-08 12:55 UTC, 4z0t commented on lua/keymap/hotbuild.lua
> +                        IssueBlueprintCommandToUnits(exFacUnits, "UNITCOMMAND_BuildFactory", units, count)
Still the same code 4 times pasted.

2024-01-08 13:53 UTC, gordenwunderlich commented on lua/keymap/hotbuild.lua
> +function translateExFacUnits(selection)
Oh, I just copied the style of the other function names in that file.
should I update them all for correct casing?
Or should we keep them as is in case someone referenced them in a mod?

2024-01-08 13:54 UTC, Garanas commented
There's no need to write a separate function for that if statement. If you can apply the Pascal convention to the name of the function today then we can include it with the hotfix

2024-01-08 14:02 UTC, gordenwunderlich commented on lua/keymap/hotbuild.lua
> +                        IssueBlueprintCommandToUnits(exFacUnits, "UNITCOMMAND_BuildFactory", units, count)
That's what I meant.
To me it feels more weird to have those effectively 2 lines of code (that also just call another function) behind another function call.

2024-01-08 14:06 UTC, gordenwunderlich commented
I changed the name of the new function, though all other functions in that file are still lowerCamelCase

2024-03-19 18:29 UTC, Basilisk3 commented
Tested and works. The only thing that does appear to be missing, is that the automatic enabling of repeat build does not work. 

To remedy this, you can add `categories.EXTERNALFACTORY` and/or `categories.EXTERNALFACTORYUNIT` to line 684 in gamemain.lua. Though this will not solve this problem either, because the code requires you to _select_ the factory for it to change it to repeat build. So if you never select the external factory, it will not have repeat build enabled automatically.

2024-06-12 11:42 UTC, MrRowey commented
@gordenwunderlich can you look at fixing what Basalisk mentions?

2024-06-18 14:42 UTC, Garanas approved these changes

2024-06-18 14:43 UTC, Garanas commented
@MrRowey that can be fixed separately from this pull request.

2024-06-18 14:49 UTC, merged