Code Formatting Units V1
FAForever/fa pull request #5759
Opened 2023-12-19 10:29 UTC by MrRowey

2023-12-19 13:25 UTC, speed2CZ commented on units/UAB3101/UAB3101_script.lua
> +            rotator= CreateRotator(self, 'B01', 'y')
This logic is broken, the rotator will never get saved on the unit. This applies to all similar changes you did in this PR

2024-04-10 09:05 UTC, lL1l1 requested changes
See https://github.com/MrRowey/fa/pull/2 for the suggested changes. It fixes some critical typos, fixes the broken upvalues, fixes some animation bugs, adds new upvalues, and fixes some whitespace.

2024-04-10 21:29 UTC, lL1l1 approved these changes

2024-04-11 08:38 UTC, MrRowey commented
@Garanas this is ready for review

2024-05-14 08:30 UTC, lL1l1 commented
Testing done:
Diff the branch with fafdevelop, then spawn in all the units that appeared in the diff:
<details> <summary> Spawn command: </summary>

```lua
CreateUnitAtMouse('daa0206', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('dal0310', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('dea0202', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('delk002', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('dra0202', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('drlk001', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('dslk004', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uaa0104', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uaa0203', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uaa0304', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uaa0310', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab0303', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab0304', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab1102', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab1103', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab1104', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab1106', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab1201', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab1301', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab1302', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab1303', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab2109', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab2204', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab2205', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab3101', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab3104', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab3201', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab4201', 1,    0.00,    0.00, -0.71822)
CreateUnitAtMouse('uab4202', 1,    0.00,    0.00, -0.71822)
```
</details>

2024-05-30 08:17 UTC, merged