Add new track target ground logic
FAForever/fa pull request #5812
Opened 2024-01-07 11:53 UTC by Garanas

Logic changes are cherry-picked from #5788, all credits to @lL1l1

2024-01-07 11:54 UTC, Garanas commented on lua/sim/Projectile.lua
> +            end
I noticed the subtle preference here to target the lower end of a unit, is that there to fix a bug or to increase the accuracy of missiles @lL1l1 😃

2024-01-07 23:54 UTC, lL1l1 commented on lua/sim/Projectile.lua
> +            end
It's not meant to bias the offset in any direction, only change the targeting volume to the above-surface part of the hitbox.
I think I made a mistake with the parentheses. It should be `sy = sy - 0.5 * sy + 2 * cy`
![image](https://github.com/FAForever/fa/assets/82986251/e9342347-b156-4166-826b-81681c6d32c1)
Also there's a mistake in `cy = sy / 2` where it should be `cy = sy / 4`

2024-01-08 00:11 UTC, lL1l1 requested changes

2024-01-08 00:11 UTC, lL1l1 commented on lua/sim/Projectile.lua
> +            local fuzziness = 0
```suggestion
            local fuzziness = physics.TrackTargetGroundFuzziness or 0.8
```

2024-01-08 00:11 UTC, lL1l1 commented on lua/sim/Projectile.lua
> +            dz = dw * ty + dz * tw + dx * tz - dy * tx
These changes would break the code because variables are assigned new values in the middle of the computation. That is why the original code only used 1 assignment to change all the values.
```suggestion
            -- compute the product in a single assignment to not have to use temporary variables.
            dw, dx, dy, dz = 
            -tx * dx - tz * dy - ty * dz,
             tw * dx + tz * dz - ty * dy,
             tw * dy + ty * dx - tx * dz,
             tw * dz + tx * dy - tz * dx

            tx, tz, ty = -tx, -tz, -ty
            
            -- compute the product in a single assignment to not have to use temporary variables.
            dx, dy, dz = 
            dw * tx + dx * tw + dy * ty - dz * tz,
            dw * tz + dy * tw + dz * tx - dx * ty,
            dw * ty + dz * tw + dx * tz - dy * tx
```

2024-01-08 00:11 UTC, lL1l1 commented on lua/sim/Projectile.lua
> +            DrawCircle(pos, 1, 'ffffff')
Don't forget to remove the DrawCircle debug.

2024-01-08 00:11 UTC, lL1l1 commented on lua/sim/Projectile.lua
> +            local dw
I placed `dw` in the rotation computation section because it is a temporary variable needed for the actual rotation and nothing else. Frankly you could replace `dw` with `(-tx * dx - tz * dy - ty * dz)` in the second multiplication and explain it with a comment, then you wouldn't need the variable at all.

2024-01-08 00:51 UTC, lL1l1 commented on lua/sim/Projectile.lua
> +            end
> It's not meant to bias the offset in any direction, only change the targeting volume to the above-surface part of the hitbox. The comments in the original code explained this.

I don't know how I made the mistake of thinking the offset is 2x or acted so weirdly.
```suggestion
            -- don't target the part of the hitbox below the surface
            if cy < 0 then
                sy = sy + cy
                cy = 0
            end
```

2024-01-08 01:12 UTC, lL1l1 commented on lua/sim/Projectile.lua
> +            end
Unexpectedly megalith changes its collision box when it finishes building to values different from its blueprint. That's what I was compensating for in my testing process when writing the code.

2024-01-08 01:57 UTC, lL1l1 commented
I fixed the megalith hitbox issue and put all the correct changes together into [2d1296e](https://github.com/lL1l1/fa/commit/2d1296e166a1d979b75205796eeb95eb2af58e6e).

2024-01-08 05:25 UTC, Garanas commented on lua/sim/Projectile.lua
> +            dz = dw * ty + dz * tw + dx * tz - dy * tx
Ah, my mistake. That is a bit confusing, haha

2024-01-08 15:53 UTC, merged