Game version 3801
FAForever/fa pull request #5912
Opened 2024-02-18 13:25 UTC by Garanas

2024-03-15 14:17 UTC, The-Balthazar commented on changelog/3801.md
> +- (#5873) Reduce the lifetime of scorchmarks created by forest fires
This should mention the new times, xor not mention the old times.

2024-03-15 16:28 UTC, Basilisk3 commented on changelog/3801.md
> +- (#5873) Reduce the lifetime of scorchmarks created by forest fires
Those were the ones which took 25 in-game hours to disappear.

2024-03-15 18:30 UTC, Basilisk3 requested changes

2024-03-15 18:30 UTC, Basilisk3 commented on changelog/3801.md
> +
```suggestion

(#5939) Improve the naming scheme of all UEF drones and update their descriptions and Tech levels.

```

2024-03-15 18:30 UTC, Basilisk3 commented on changelog/3801.md
> +- (#5870, #5858, #5881) Improve the descriptions of a wide range of units
```suggestion
- (#5870, #5858, #5881) Improve the descriptions of a wide range of units.
```

2024-03-15 18:30 UTC, Basilisk3 commented on changelog/3801.md
> +- (#5958, #5979) Fix projectiles of the Fatboy and SACUs running out of lifetime before impact
```suggestion
- (#5958, #5979) Fix projectiles of the Fatboy and SACUs with their respective range upgrades running out of lifetime before impact.
```

2024-03-16 01:49 UTC, 4z0t commented on changelog/3801.md
> +    The Novac Satalite System can be restricted separately.
Typo `Novax`.

2024-03-16 07:24 UTC, merged