UnitviewDetail: Do not display unneeded stats for the 'Teleport in' weapon of units with the teleport upgrade
FAForever/fa pull request #6018
Opened 2024-03-25 19:46 UTC by Basilisk3

## Description of the proposed changes

The `Range` and `Reload` stats should not be displayed for 'Teleport in' weapons in, as they do not make sense here.

**The old output for 'Teleport in' weapons:**

```
Teleport in (Teleport) (Manual Fire)
Damage: 100, Splash: 4, Range: 0 - 1, Reload: 1.$
```

**The new output for 'Teleport in' weapons:**

```
Teleport in (Teleport) (Manual Fire)
Damage: 100, Splash: 4
```

## Checklist

- [ ] Changes are documented in the changelog for the next game version

2024-03-31 08:06 UTC, lL1l1 requested changes
I have written a pr to your branch with the suggested changes.

2024-03-31 12:26 UTC, Basilisk3 commented on lua/ui/game/unitviewDetail.lua
> +                            if row < 0 then
This is a difficult one, because if there is only one armor type present, which I assume holds true for the majority of units, my solution looks better. To me, it makes more sense that if there is only one armor type, it is displayed under (% of damage taken) instead of `Armor Type`. When there is more than one armor type, your solution looks better. I will revert this for now, but this is something that could be looked into in the future.

2024-04-01 03:16 UTC, lL1l1 approved these changes

2024-04-01 06:24 UTC, lL1l1 commented
@Basilisk3 The branch needs to be rebased on the latest version because of the telebilly force push rewriting the commit history. After that I can move the changelog notes to 3807 and merge it.

2024-04-01 11:45 UTC, Garanas commented
Yeah, my mistake - sorry about that 😞

2024-04-01 14:24 UTC, closed without merging