Simplify and robustify transport cargo killing and veterancy
FAForever/fa pull request #6091
Opened 2024-04-16 21:37 UTC by clyfordv

1. When killing cargo, the instigator unit is provided. The engine then counts kills for score and unitview purposes.
2. Similarly, the mass of all cargo is distributed to the killer(s) (via lua) with `VeterancyComponent.VeterancyDispersal`.
3. For transports with external storage, cargo is cached so impact effects can be delayed/applied properly when the transport hits the ground.
4. Lastly, the new function explicitly kills all units (previously relied on the engine to do it), which (hopefully) addresses a bug where units who were supposed to die escaped their fate.

And hopefully all in a much more straightforward way than before!

2024-04-17 03:49 UTC, lL1l1 requested changes
I tested the changes with continentals of SACU or harbingers, a T1 transport with SACU/harbingers, a carrier full of strategic bombers, and a CZAR. The veterancy distribution works.
In the suggestions, I fixed two bugs I found:
- units don't detach from air transports nor spawn wrecks on transport death. They also play death effects when the transport dies.
- Units in carriers (transport internal storage) play death effects/weapons (but aircraft don't have death weapons so its less noticeable). They shouldn't do this because it looks bad.

There is another bug that I'm unsure of the best way to fix:
- transports/carriers can't be ctrl-k'd. 
This bug is caused because `Entity:Kill()` is separate from `Entity:Kill(instigator, damageType, excessDamageRatio)`, and the latter is called if any 3 arguments are passed to :Kill, even if they are nil, and the arguments must be valid (`instigator is Unit | nil, damageType is string, excessDamageRatio is number`).
Solutions: Add `(nil, '', 0)` to selfdestruct.lua:45, add `if not instigator then damageType = '' excessDamageRatio = 0 end` to the AirTransportUnit and AircraftCarrierUnit `Kill` functions, or use BaseUnitKill(self) when instigator == nil inside the unit classes and inside killcargo. 


The best fix would just be whatever is most easily documented I guess.

Future? possible improvements:
- wrecks from transports' internal storages
- can an internal storage + external clamps transport exist? If so, would it break the logic?

Don't forget the changelog by the way.

2024-04-17 03:49 UTC, lL1l1 commented on lua/sim/units/components/TransportUnitComponent.lua
> +            end
```suggestion
            if not EntityCategoryContains(categories.COMMAND, unit) then
                unit.killedInTransport = true
            end
            if cacheCargo then
                table.insert(self.cargoCache, unit)
            end
```
The two flags have independent purposes (triggering death effects from `Unit:Kill()` right now (on line 119) vs dealing with the units in a future time), so they should be treated separately.

2024-04-17 04:00 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +                unit:OnKilled(self.killInstigator, self.killDamageType, self.killExcessDamageRatio)
Those values aren't passed to/aren't available to OnImpact, so cannot be passed ImpactCargo, and need to be cached from Kill/OnKilled.

2024-04-17 04:02 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +        local cacheCargo = (self:GetBlueprint().Transport.StorageSlots and false) and true
Sounds good to me, hadn't looked at the blueprint viewer.

2024-04-17 04:13 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +                unit:OnKilled(self.killInstigator, self.killDamageType, self.killExcessDamageRatio)
As to overkill, would it not also be odd to see the wreck of the transport disappear but not the units?

2024-04-17 04:18 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +            end
yep they gotta be separate

2024-04-17 04:23 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +            unit:Kill(instigator, damageType, excessDamageRatio)
Your fix above addresses this ye? (And then uncached cargo gets killed, but never fires OnKilled. Will that prevent anything important?)

2024-04-17 04:26 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> -            unit:DetachFrom()
I'd asked the same question, couldn't think of a good reason why it had to be in there, and figured I'd experiment with taking it out.

2024-04-17 04:46 UTC, clyfordv commented
Fixed ctrl-k, probably had something to do with removing the part with comments to the effect of "do not remove this part or it won't work".

2024-04-17 05:11 UTC, lL1l1 commented on lua/sim/units/components/TransportUnitComponent.lua
> -            unit:DetachFrom()
It works fine and I can't find anything through git blame, so I guess it's okay.

2024-04-17 05:15 UTC, lL1l1 commented on lua/sim/units/components/TransportUnitComponent.lua
> +                unit:OnKilled(self.killInstigator, self.killDamageType, self.killExcessDamageRatio)
By "passed in before" I meant why didn't the old devs cache it. I think it's just because that was the easiest solution at the time, because I can't find any old transport logic that would explain not caching as a workaround for something. Consider that question resolved.

For overkill, units have way more HP than transports, so aesthetically they can survive the complete destruction of the transport. After that, what kills them is the crash damage, which doesn't seem like it would obliterate the unit. In addition to all that, any low HP units that could be overkilled by AA would have already died while the transport was being shot at.

2024-04-17 05:27 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +                unit:OnKilled(self.killInstigator, self.killDamageType, self.killExcessDamageRatio)
Ah, I see I see. Yeah who knows, sometimes an obvious solution conceals itself.

And I can get with that reasoning. How would you feel about the overkill-surviving units being thrown away from the explosion?

2024-04-17 06:22 UTC, lL1l1 commented on lua/sim/units/components/TransportUnitComponent.lua
> +            unit:Kill(instigator, damageType, excessDamageRatio)
Not firing OnKilled is a problem, it does tons of things from visual effects to callbacks to statistics to AI informing.
Bug: It also disperses veterancy, so if the unit was ever damaged before, it gives vet to the transport killer (through the transport component) and to whatever damaged it before (double vet). This is a common situation since most ground AA has AoE.
I think the better way to handle dispersing unit veterancy of transported units is to concatenate the transport's veterancy fields (`VeterancyComponent.VetDamage, .VetInstigators, and .VetDamageTaken` onto the cargo's vet fields. Fixes double vet dispersal, but still gives double vet damage for splash AA, it could be accounted for by not adding the damage if that entity already has damage on the unit.
OnKilled needs a way to not trigger death visual effects. Maybe by using a 'TransportDeath' damage type (passes to AI brain), just adding a new optional parameter to the function, or by using a unit field similar to `Unit.DeathWeaponEnabled`. Btw air units have their own OnKilled behavior that happens when they're in the air layer (inside the carrier, even underwater atlantis, they are still in the air layer).

2024-04-17 06:27 UTC, lL1l1 commented on lua/sim/units/components/TransportUnitComponent.lua
> +                unit:OnKilled(self.killInstigator, self.killDamageType, self.killExcessDamageRatio)
I think it's best for the reclaim to fly in the same direction as the transport, so that the actions of the players is reflected in where the reclaim goes. The reclaim being next to the transport also helps remember what was in the transport for replay watchers/casters/in-game players.

2024-04-17 06:30 UTC, lL1l1 commented on lua/sim/units/components/TransportUnitComponent.lua
> +            end
They're actually dependent on each other. killedInTransport means "don't trigger OnKilled effects right now because we will deal with them later" and cacheCargo means "these are the units we are dealing with later". So they should be under the same if statement.
> triggering death effects from Unit:Kill() right now
That should be a third option as I described before, specific for carriers to "kill units now, but without effects".

2024-04-17 08:46 UTC, MrRowey commented
Please Request a review from me once PR is Complete :)

2024-04-17 13:42 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +            unit:Kill(instigator, damageType, excessDamageRatio)
I like the 'TransportDeath' damage type, it's a tight solution.

For the double veterancy issue, we can replace:

`cargoMass = cargoMass + unit:GetTotalMassCost()`
with
`cargoMass = cargoMass + unit:GetTotalMassCost() * (unit:GetHealth() / unit:GetMaxHealth())`

... which will mean that only any remaining health will be credited to the transport instigator, but it will still be divided properly among the transport killers.

2024-04-17 13:42 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +            unit:Kill(instigator, damageType, excessDamageRatio)
Working through an example:
1. `Tank` has 100 hp.
2. It gets in a scuffle, takes 25 hp of damage from `kbot`.
3. It loads in `transport` that has 50 hp.
4. Transport gets whacked by `flak`, `tank` takes 25 damage, `transport` takes 25 damage.
5. `Interceptor` shoots down transport.

Transport veterancy dispersal:
- 50% to `flak`
- 50% to `interceptor`

Tank veterancy dispersal:
- 25% to `kbot`
- 25% to `flak`
- 50% remaining when killed on transport

The leftover 50% of `tank:MassCost()` gets collected by `cargoMass` and dispersed 50:50 to `flak` and `interceptor` in `KillCargo()`

2024-04-17 13:46 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +            end
I knew there was a reason I put them together ;D

But yes you're definitely right about the third option, I'll assemble it.

2024-04-17 19:21 UTC, clyfordv commented
Alright we should be solid (tested it this time!) 

Improvements:
- Added `TransportInternal` and `TransportExternal` as damage types (currently only `TransportInternal` is relevant, so we could trim it down to just `Transport` if people like the simplicity).
- Reworked the logic so KillCargo only runs once on transports-in-transports. 
- OnKilled for mobile units and aircraft runs a check for the `TransportInternal` damage type and will not play any effects, death threads, shield bounce projectiles, etc. when the internal storage they're in dies.

Possible issues:
- The divide between score/AI and visual/audio/etc. in `OnKilled` is not super strong, or at least not formalized. (For example, do death threads do anything that should still happen if killed inside a transport?)

Minor issues:
- Discovered that external factory dummy units are counted as losses to the player at the end of the game (2, actually--1 structure, 1 layer). This happens in `deploy/fafdevelop` as well.

Future ideas:
- Tangentially related, but when a transport enters a transport it could detach its unit, store it in the carrier on another bone, then retrieve it when it exits. This would require a little rework of the above, but would solve the ghost selection issue when a stinger with cargo is in a carrier.

2024-04-17 20:32 UTC, MrRowey commented
@relent0r will any of the changes here affect ai ?

2024-04-18 08:17 UTC, lL1l1 requested changes
I tested it and found no errors.

2024-04-18 13:25 UTC, clyfordv commented on lua/sim/Unit.lua
> +        end
"TransportDamage" is for internal storage (external storage just gets "Normal"), so no death threads, wreckage, etc. "Any errors" == any lingering references (like from `OnImpact`, though that's applicable for aircraft only) that might throw warnings. Adding the `self:Destroy()` here (to mobile units) is just a precaution for something unforseen, because I haven't found anything that would be an issue but felt it wise to get a rid of a unit that would otherwise be hanging around with half its normal death declarations.

2024-04-18 13:28 UTC, clyfordv commented on lua/sim/units/MobileUnit.lua
> +            self.SkipOnKilled = false
I'll flip it back.

2024-04-18 13:30 UTC, clyfordv commented on lua/sim/units/AirTransportUnit.lua
> +        damageType = damageType or "Normal"
If it works it works, I was just going with what was defined in the original.

2024-04-18 13:41 UTC, clyfordv commented on lua/sim/units/components/TransportUnitComponent.lua
> +            self:VeterancyDispersal(cargoMass)
It would not be difficult to do, but I think 1 level at a time is a good rate limiter. The extreme case of distributing it in chunks results in "kill a fully loaded carrier" -> "immediately promoted to top rank", which feels odder to me, given that the actual action of shooting down the transport is the same as the empty one.

E.g. In real life(!), a dive bomber pilot that gets a lucky hit on a loaded carrier or AA crew that shoots down an airship would probably get a bonus/promotion/three day pass, but would likely not be promoted to admiral/general.

2024-04-18 13:47 UTC, clyfordv commented on lua/armordefinition.lua
> +---| "TransportDamage"
I think we're alright (conceptually there's a good number of damage types that are used for various kinds of bookkeeping, not just damage) but it also prevents us from having to declare 150 new table fields for a single instant when a fully loaded CZAR gets killed.

2024-04-19 20:09 UTC, relent0r commented
> @relent0r will any of the changes here affect ai ?

I don't see anything that would impact the default AI. The changing from OnKilled to Kill might impact other AI's that are tracking deaths of units. But it looks like we are trying to make it consistent between files so makes sense.

2024-04-19 21:07 UTC, MrRowey approved these changes

2024-04-20 07:24 UTC, lL1l1 commented on lua/sim/units/MobileUnit.lua
> +            self.SkipOnKilled = false
I think it should be changed back because otherwise any old mod that creates a similar OnKilled function will have to 
be unnecessarily updated to handle the new transport flag name.

2024-04-21 14:16 UTC, MrRowey commented
@lL1l1 you happy with the changes so far? if so can you approve the PR so I know

2024-04-22 00:19 UTC, clyfordv commented
killedInTransport flagging variable is renamed back, so we should be squared away

2024-04-22 03:13 UTC, lL1l1 approved these changes

2024-04-22 08:15 UTC, merged