Othuum Responsiveness and Range Buff
FAForever/fa pull request #6103
Opened 2024-04-21 11:42 UTC by lL1l1

## Description of the proposed changes

Goal: make it not get outranged as much and better to micro so that it is more viable in T3 raids/rushes.

- Increase Othuum's Bolters' range from 20 -> 22
- Increase Othuum turn rate 75 -> 130
- Increase Othuum max brake 2.85 -> 3.55. This slightly helps it turn from a standstill

https://github.com/FAForever/fa/assets/82986251/b7d2a285-d24b-459e-acf8-3789ca4afd6f

https://github.com/FAForever/fa/assets/82986251/e7ff4b66-1b5c-46cb-867b-1699dcfea531

## Additional context
Made by Balance Team request.

## Checklist

- [ ] Changes are documented in the changelog for the next game version

2024-04-21 14:17 UTC, MrRowey approved these changes

2024-04-21 16:15 UTC, Garanas requested changes
It is a big sturdy unit on tracks - with this turn rate it feels weightless. I'd rather we explore different directions before making the Othuum feel weightless.

2024-04-22 00:35 UTC, lL1l1 commented
https://github.com/FAForever/fa/assets/82986251/be456668-55ad-4a99-adce-e3cb64a8cdda

2024-04-22 08:04 UTC, MrRowey approved these changes

2024-05-14 11:18 UTC, MrRowey commented
Please can you change the `TurnRate` to `90`

2024-05-14 11:24 UTC, MrRowey approved these changes

2024-05-14 11:41 UTC, merged