Add feature to preview adjacent units when building
FAForever/fa pull request #6283
Opened 2024-06-21 15:41 UTC by Garanas

## Description of the proposed changes

It's always been difficult to properly understand what units are considered adjacent when you are building. With this new feature we try to alleviate this problem!

With thanks to `OnDetectAdjacencyBonus` in [gamemain.lua](/lua/ui/game/gamemain.lua) we've always had the ability to detect adjacency while constructing. But up until now we did not quite do anything with that ability. Now, we render the unit icon on top of all units that are adjacent. 

https://github.com/FAForever/fa/assets/15778155/e9111af6-f338-41e9-8be2-c67731bc0ba0

## Testing done on the proposed changes

Spawn in structures and then create all sorts of build previews. 

## Additional context

The feature is enabled by default. It can be disabled in the game options at `Interface -> HUD -> `Show adjacent units when building`.

There is no reliable solution for more advanced checks and/or drawings. This includes, but is not limited to:

- Check whether there are actual adjacency benefits before drawing
- Drawing of lines, or other features that rely on the position of the location of the build preview

The reason for this is because we only know what unit we're adjacent to but we do not know what in the build preview is adjacent to that unit. When there's only one build target this is trivial, but when we drag build and/or use a template it because much, much less trivial to understand. Therefore I opted for the simple solution to just always show the icon.

## Checklist

- [x] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

2024-06-21 15:44 UTC, Garanas commented
I'm open to suggestions on the name of the feature in the game options 😃 !

2024-06-21 16:02 UTC, Garanas commented
Example of dynamic scaling: 

https://github.com/FAForever/fa/assets/15778155/48d6bfe1-6730-4d3a-b6ff-c18d0138109c

2024-06-21 18:47 UTC, lL1l1 commented
> The reason for this is because we only know what unit we're adjacent to but we do not know what unit in the build preview is adjacent to that unit.

`otherBp` in `OnDetectAdjacencyBonus(userUnit, otherBp)` seems to contain the bp of the adjacent build preview, even for templates. This allows checking for adjacency bonuses.

> Drawing of lines, or other features that rely on the position of the location of the build preview

There could be a special case for non-template build mode, in which the build preview is located using mouse worldpos and mimicking however the engine interprets skirts and skirt offsets onto the world grid. 
Thinking this through more, you can apply this analysis to UserUnits' positions and skirt data, selected template data, and mouse position to identify what userunit is touching what part of the build template.

2024-06-21 19:05 UTC, Garanas commented
> `otherBp` in `OnDetectAdjacencyBonus(userUnit, otherBp)` seems to contain the bp of the adjacent build preview, even for templates. This allows checking for adjacency bonuses.

You're right! I just checked again, I must have goofed up there. Would make for an interesting improvements in version 2, where we for example add an energy or mass icon if it impacts production or consumption.

> There could be a special case for non-template build mode, in which the build preview is located using mouse worldpos and mimicking however the engine interprets skirts and skirt offsets onto the world grid.
> Thinking this through more, you can apply this analysis to UserUnits' positions and skirt data, selected template data, and mouse position to identify what userunit is touching what part of the build template.

I don't think the complexity of it is worth it. The feature is quite simple right now. That keeps it maintainable.

2024-06-22 08:37 UTC, Garanas commented
@lL1l1 I've prepared the functions to allow them to be expanded in the (near) future. Could you give the pull request a review as it is right now? Then we can ship that, because I think it already adds sufficient value the way it is now.

2024-06-22 13:03 UTC, lL1l1 requested changes

2024-06-22 13:03 UTC, lL1l1 commented on lua/ui/game/cursor/Adjacency.lua
> +    unitAdjacencyLabel:SetUnitTexture(unit:GetBlueprint())
The entire texture setting function does not need to run every frame for a label that is assigned to a specific EntityId. It can be replaced in the looping part with 
```
unitAdjacencyLabel.FrameCount = 0
unitAdjacencyLabel:Show()
```
the `:Show()` is also not ideal because it's just there to fight OnFrame doing `:Hide()` after 10 frames.

2024-06-22 16:24 UTC, Garanas commented
Processed the skirt size feedback in https://github.com/FAForever/fa/pull/6283/commits/5bd048c25b821d75a9729cbeaf93dec76fbf127d

2024-06-22 16:25 UTC, Garanas commented on lua/ui/game/cursor/Adjacency.lua
> +            :Fill(self)
Processed in https://github.com/FAForever/fa/pull/6283/commits/e1f2606327cfe8cab71b0820dfb0b4d5156105a3

2024-06-22 16:26 UTC, Garanas commented on lua/ui/game/cursor/Adjacency.lua
> +        LayoutHelpers.LayoutFor(self)
Processed in https://github.com/FAForever/fa/pull/6283/commits/6bafa36e32d180179d0d474b04d9b11dfacb6d61

2024-06-22 16:26 UTC, Garanas commented on lua/ui/game/cursor/Adjacency.lua
> +local LayoutHelpers = import("/lua/maui/layouthelpers.lua")
Processed in https://github.com/FAForever/fa/pull/6283/commits/6bafa36e32d180179d0d474b04d9b11dfacb6d61

2024-06-22 16:27 UTC, Garanas commented on lua/ui/game/gamemain.lua
>  function OnDetectAdjacencyBonus(userUnit, otherBp)
Applied 👍

2024-06-22 16:28 UTC, Garanas commented on lua/ui/game/cursor/Adjacency.lua
> +        self.UnitStrategicIcon = Bitmap(self, nil, 'unit-adjacency-label-strategic-icon')
The strategic icon field is not implemented yet. I was thinking of creating an exact replica of what you see in the construction view:

![image](https://github.com/FAForever/fa/assets/15778155/ce6be44e-3606-40a2-aa94-d82745b33f05)

But I'm not sure if that is better at this point as we'll also need the space to show an energy or mass icon when adjacency applies.

2024-06-22 16:29 UTC, Garanas commented on lua/options/options.lua
> +                        { text = "<LOC _On>", key = 1 },
I don't know - I copied another on/off field and adjusted the text. I'm fine with any suggestion

2024-06-22 16:59 UTC, Garanas commented on lua/ui/game/cursor/Adjacency.lua
Processed in https://github.com/FAForever/fa/pull/6283/commits/e6b21c6ae2ad0a5d014cf5139c0e06dd5e1b9ef7

2024-06-22 17:19 UTC, Garanas commented on lua/ui/game/cursor/Adjacency.lua
> +    OnFrame = function(self, delta)
Processed in https://github.com/FAForever/fa/pull/6283/commits/d36d00c43ba01308c2413faf9820eaac79226e34

2024-06-22 17:20 UTC, Garanas commented on lua/ui/game/cursor/Adjacency.lua
> +    unitAdjacencyLabel:SetUnitTexture(unit:GetBlueprint())
Processed in https://github.com/FAForever/fa/pull/6283/commits/0eef598bef8231876c26be45653717133d85c56e

I personally think the location for `Show` now fits decently in `UpdateReferences`

2024-06-22 17:23 UTC, Garanas commented on lua/ui/game/cursor/Adjacency.lua
> +        self.UnitStrategicIcon = Bitmap(self, nil, 'unit-adjacency-label-strategic-icon')
Decided to just remove it for now, processed in: https://github.com/FAForever/fa/pull/6283/commits/bde489ce5251693cc0bd1d49819036cc13ac2617

2024-06-22 17:27 UTC, Garanas commented
Behavior at this moment:

https://github.com/FAForever/fa/assets/15778155/1145b08a-bef2-4ebf-9812-be32efa115bc

2024-06-23 14:02 UTC, BlackYps commented
I think for this feature to be useful it should only show adjacency when there is an actual bonus. And then we probably should show only a mass or energy symbol. The way it is now it literally shows up on every combination of buildings which makes the feature a bit annoying. I can already see that my air factory is next to the land factory. I don't need to see the icon of the building at that moment. They are a bit hard to process anyway, so at the moment I don't see a significant benefit here.

I'd say we should only ship this feature once we have it reduced to buildings where you actually care for adjacency otherwise a lot of players will probably turn it off in the beginning and then not even experience the version 2.

Unrelated to that, this should probably point to dev iteration 3 anyway, right?

2024-06-23 16:22 UTC, lL1l1 commented on lua/ui/game/cursor/Adjacency.lua
> +        self.UnitStrategicIcon = Bitmap(self, nil, 'unit-adjacency-label-strategic-icon')
A good idea would be to re-use the selected strategic icon (`[StrategicIconName]_selected.dds`) to highlight what structures are getting the adjacency bonus. I think it would fit into the HUD very cleanly and be easy to process for the player; an issue BlackYps pointed out.
If it fits on top of the strategic icons perfectly it would be very unobtrusive and be a good default option since I doubt it would get complaints even from conservative players.

2024-06-23 16:27 UTC, lL1l1 commented on lua/options/options.lua
> +                        { text = "<LOC _On>", key = 1 },
I think `true | false` makes sense for on/off options, and then `false | string` for off/multichoice options. It avoids having to compare the key against 0 to see if the option is enabled, and when you have multiple choices the string makes it clear in the code where a certain choice is implemented. Numbers should be for when you are going to use the number directly in some calculation, just like a slider option.

2024-06-23 16:37 UTC, lL1l1 commented on lua/ui/game/cursor/Adjacency.lua
> +    unitAdjacencyLabel:SetUnitTexture(unit:GetBlueprint())
How about moving `Show` into `OnFrame`'s `if alpha > 0 then`? It would keep the parts that hide/show the label together.

2024-06-23 18:04 UTC, lL1l1 reviewed
I left some more comments in this review and added to the discussion in the previous review.
I agree with BlackYps that it should point Dev iteration 3. It's a good proof of concept but it needs more polishing to be beneficial but unobtrusive for players.

2024-06-24 08:18 UTC, Garanas commented on lua/ui/game/cursor/AdjacencyPreview.lua
> +        self.WorldView = worldView
> and possibly a way to easily render something in all worldviews.

A user only looks at one place at a time however. From a performance perspective the function `OnFrame` triggers at least 60 times per second, but it can be much higher if people unlocked the FPS. 

I can see the value in using the world view the mouse is over, but I'm personally not in favor of always rendering the data on all worldviews and/or make that more accessible to developers because of the impact it can have.

2024-06-24 08:18 UTC, Garanas commented on lua/ui/game/cursor/AdjacencyPreview.lua
> +        self.Top:Set(unitScreenPosition[2] - self.Height() / 2)
I do not understand, can you elaborate?

2024-06-25 01:02 UTC, lL1l1 commented on lua/ui/game/cursor/AdjacencyPreview.lua
> +        self.WorldView = worldView
The engine already renders everything on all worldviews, so I think that such a capability should be open for developers so that they can maintain consistency with how the game normally plays. Of course it can come with a hefty warning that it may cost performance and it is unnecessary for one-time tasks where the user is focusing on where the cursor is and not looking at different views simultaneously.

But back to the PR topic, we can just render only in the current view of the mouse, and it would be nice for whoever plays some multiscreen setup, say if they have their base on one view and their front on the other view.

2024-06-25 01:12 UTC, lL1l1 commented on lua/ui/game/cursor/AdjacencyPreview.lua
> +        self.Top:Set(unitScreenPosition[2] - self.Height() / 2)
`CUIWorldView:Project` returns the screen space in local coordinates for the worldview, not absolute screen coordinates. `viewleft` is located at (0, 0) so that works, but `viewright` is located at (ScreenWidth/2, 0) so your labels won't be in the right place. Something like this:
```lua
ReusedLayoutFor(self)
  :AtLeftTopIn(worldView
    , unitScreenPosition[1] - self.Width() / 2
    , unitScreenPosition[2] - self.Height() / 2
  )
  :End()
```

2024-06-25 06:40 UTC, Garanas commented on lua/ui/game/cursor/AdjacencyPreview.lua
> +        self.Top:Set(unitScreenPosition[2] - self.Height() / 2)
We should probably update the description 😃 , even though it is there I did not immediately make that conclusion haha.

2025-02-01 18:47 UTC, BlackYps commented
Are you still planning to continue this? After reading the discussion again I wonder if this feature is not more suited as a UI mod...

2025-04-11 00:03 UTC, Hdt80bro commented
I think this would be a great feature, suitable for the base game and not a UI mod, if it got polished up (e.g. only showed for relevant buildings, T1 PD skirt size was handled properly, it showed up for planned buildings...) and if the way it was communicated was changed. Maybe something more subtle like highlighting the edge that's adjacent?

It also occurs to me that there's a few different ways that adjacency works, so it might be nice to somehow communicate that power generators next to artillery will make that building shoot faster, but next to energy storage will make this building produce more, while next to a factory will make it consume less.

2025-05-27 21:02 UTC, 4z0t commented on engine/Core.lua
>  ---@param entity? Destroyable
Should also change it. This means that the argument is optional, but in reality it is required and *can* be nil.

2025-05-27 21:05 UTC, 4z0t commented on lua/ui/game/cursor/AdjacencyPreview.lua
> +        self.Top:Set(unitScreenPosition[2] - self.Height() / 2)
Also wrong. With UI scale it will be offset wrongly.

2025-06-09 07:55 UTC, Garanas commented
I've looked whether we can include more context to understand what type of buff would be applied. For example, whether there would be an energy consumption reduction.

All of these type of buffs are defined here:

- https://github.com/FAForever/fa/blob/develop/lua/sim/AdjacencyBuffs.lua
- https://github.com/FAForever/fa/blob/develop/lua/sim/BuffDefinitions.lua
- https://github.com/FAForever/fa/blob/develop/lua/sim/CheatBuffs.lua
- https://github.com/FAForever/fa/blob/develop/lua/sim/OpBuffDefinitions.lua

When a unit checks for a buff to apply there's several steps:

- Check if the adjacent unit (that would provide the buff, like a power generator) is able to provide buffs. This is the `Blueprint.Adjacency` field.
- Map the adjacency blueprint field to the actual buff names. This is done with the `AdjacencyBuffs.lua` file. There will be multiple hits, because there are different numbers for different unit sizes.
- For each buff name, find the matching blueprint buff.
- For each blueprint buff that exists, check if the target unit (that would receive the buff, like a mass extractor, factory or artillery) meets the basic category check (as defined by `blueprintBuff.EntityCategory`).

And here is where things get tricky:

- For each blueprint buff that exists, if it has a BuffCheckFunction and if it does, check if the target unit (that would receive the buff) passes that check.

These checks are defined in this file:

- https://github.com/FAForever/fa/blob/develop/lua/sim/AdjacencyBuffFunctions.lua

Which requires a unit reference, the type of unit reference that you only have in the simulation. This is especially relevant for the weapon related buffs, as they go over each weapon instance.

Which is where it breaks down a little bit. At the end of the day, all these functions end up checking one type of blueprint value or another. Even those of weapons are set directly from the blueprint. But I think if we refactor this, and especially the function signature, we'll be in a world of pain with regards to mod compatibility 😃 .

And if I take a step back - I think we already are in a world of pain by just importing the buff files. They reside in the `sim` folder. It wouldn't be strange for a mod author to import other sim related files for very specific buffs, like a buff that adds some entity.

Which ends my investigation. I'm not sure what is the best approach to proceed. Open to ideas on how to polish this further! Maybe @lL1l1  / @The-Balthazar have an idea since they recently worked with buffs quite a bit.

2025-06-10 08:05 UTC, lL1l1 commented
As a first step I would move the `BuffDefinitions.lua` import from global init to sim init. The global import is already creating functions that would error if called, since it imports the adjacency buff checks functions.

For getting buff data to the UI (since its in sim init now), you could have a shared adjacency buff definitions file, but it would lead to desyncs between Sim/UI when sim mods adjust those definitions, so instead I would sync select buffs at the start of the game (with the presumption that all adjacency buffs are initialized by then). The selected buffs would be a cleaned list of the buff tables created in `AdjacencyBuffs.lua` (since this is what [StructureUnit uses](https://github.com/FAForever/fa/blob/21cbd19c15ba8ed34ec001f8309404a5dc848501/lua/sim/units/StructureUnit.lua#L795)). The cleaning step would recursively remove values that are not of type table, number, or string.

After you have the up-to-date buff tables you can add UI buff check functions based on the buff's effects that imitate the sim version but using blueprint fields if UserUnit doesn't expose the necessary info. Then finally you can use the `Adjacency` blueprint field of the adjacent units being previewed to find the correct buffs, check if they apply, and display their effects if they do.

2025-06-10 15:26 UTC, Garanas commented
> so instead I would sync select buffs at the start of the game (with the presumption that all adjacency buffs are initialized by then).

Buff definitions rely on functions. You can not sync those function definitions I think.

I'm not sure about removing global state, especially if it's been there from the start. There are some mods that heavily rely on buffs, and maybe they'll error out because of that.

2025-06-11 20:14 UTC, lL1l1 commented
> You can not sync those function definitions I think.

Yes, that's why I included the process of selecting specific buffs and cleaning the buff tables before syncing.

> I'm not sure about removing global state, especially if it's been there from the start. There are some mods that heavily rely on buffs, and maybe they'll error out because of that.

By moving it to simInit it is moved from UI+Sim global state to Sim global state. I don't expect any mods to use the UI global state.

2025-06-12 10:45 UTC, speed2CZ commented on lua/simInit.lua
> +        GTS = GetGameTimeSeconds()
Aren't you missing locals? here

2025-11-15 14:04 UTC, BlackYps commented
Closing due to inactivity. Feel free to reopen it if you pick it up again.

2025-11-15 14:04 UTC, closed without merging