Implement variable transport speeds
FAForever/fa pull request #6309
Opened 2024-06-26 19:49 UTC by Basilisk3

Implement transports moving at different speeds depending on how many and which types of units they have loaded.

## Description of the proposed changes
- Each Tech 1 unit decreases the transport's MaxAirspeed by `0.15`
- Each Tech 2 unit decreases the transport's MaxAirspeed by `0.3`
- Each Tech 3 unit decreases the transport's MaxAirspeed by `0.6`
- ACUs decrease the transport's MaxAirspeed by `1`

## Stat changes:
**All Tech 1 Air Transports:**
MaxAirspeed: 10 --> 10.75

**All Tech 2 Air Transports:**
MaxAirspeed: 13.5 --> 14.5

**The Continental:**
MaxAirspeed: 15 --> 17.5
**All Tech 1 land units:**
UnitWeight: 1.5

**All Tech 2 land units:**
UnitWeight: 3

**All Tech 3 land units:**
UnitWeight: 6

**All ACUs and SACUs:**
UnitWeight: 10

The `UnitWeight` stat can be tweaked for each unit individually, though I did not do it here for consistency reasons. 

## Additional context
- As Jip already pointed out, the change introduces a new balance knob.
- Enables more teamplay, as getting an empty transport to your teammates is faster.
- The changes would introduce a new choice for the player, allowing him to decide between a swift and less damaging drop or a slower but more damaging one.
- Nerfs arty drops, specifically Seraphim transports fully loaded with Zthuees, in an intuitive way. As Seraphim has the highest capacity transports (and the strongest Tech 1 Artillery), I regard this as a positive.

## Checklist
- [ ] Populate the `UnitWeight` blueprint field of all land units
- [x] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

2024-06-26 19:58 UTC, Basilisk3 commented
@EvildrewFAF This is my own implementation of this idea. You are obviously free to do whatever you want with it. Since your implementation is more detailed, overriding this would be the easiest solution to keep your mod compatible. Alternatively you could build your own implementation on top of this one.

@Garanas @lL1l1 If you have time, please consider giving this a review.

2024-06-27 05:13 UTC, Garanas commented
Are you referring to this blueprint value: https://github.com/FAForever/fa/pull/6279

2024-06-27 08:02 UTC, lL1l1 requested changes

2024-06-27 08:02 UTC, lL1l1 commented on lua/sim/units/AirTransportUnit.lua
> +        for _, unit in ipairs(self:GetCargo()) do
You could also design the feature so that it does not need to use `GetCargo`, and instead uses the `unit` passed into the attach/detach functions.

2024-06-27 08:04 UTC, lL1l1 commented
Also the stat should be added to `blueprints-units.lua`'s post-processing for mod compatibility.

2024-06-27 09:27 UTC, Basilisk3 commented on lua/sim/units/AirTransportUnit.lua
> +        for _, unit in ipairs(self:GetCargo()) do
This is good to know. I oriented myself on other FAF code.

2024-06-27 10:34 UTC, Basilisk3 commented
> Also the stat should be added to `blueprints-units.lua`'s post-processing for mod compatibility.

Done. Thanks for reviewing.

2024-06-28 15:13 UTC, Basilisk3 commented
> Are you referring to this blueprint value: #6279

The UnitWeight stat is now populated via blueprints-units.lua. We could also populate the field in the blueprints themselves to make the stat more visible.

2024-06-28 15:42 UTC, Basilisk3 commented on lua/sim/units/AirTransportUnit.lua
> +        for _, unit in ipairs(self:GetCargo()) do
Unfortunately I could not get this to work.

2024-06-29 09:27 UTC, Garanas commented
> > Are you referring to this blueprint value: #6279
> 
> The UnitWeight stat is now populated via blueprints-units.lua. We could also populate the field in the blueprints themselves to make the stat more visible.

I'll look into it for you 👍

2024-06-30 07:02 UTC, lL1l1 commented on lua/sim/units/AirTransportUnit.lua
> +            totalweight = totalweight + unit.Blueprint.General.UnitWeight
@Basilisk3 sorry maybe I worded it wrong; by `TransportSpeedReduction` I meant the name of the UnitWeight stat:
```suggestion
            totalweight = totalweight + unit.Blueprint.General.TransportSpeedReduction
```
You changed the name of the function which wasn't what I was talking about.

2024-06-30 07:03 UTC, lL1l1 commented on lua/sim/units/AirTransportUnit.lua
> +        for _, unit in ipairs(self:GetCargo()) do
That's fine, it's not essential.

2024-06-30 12:29 UTC, Basilisk3 commented on lua/sim/units/AirTransportUnit.lua
> +            totalweight = totalweight + unit.Blueprint.General.UnitWeight
I changed it.

I also moved the stat from General to Physics, which I am still a bit divided about. The stat only affects the physics of the unit when it is traveling via the transport, but I also do not know where else to put it.

2024-06-30 23:24 UTC, lL1l1 approved these changes

2024-07-01 07:19 UTC, clyfordv commented on lua/system/blueprints-units.lua
> +        end
Might be wise to add a catch all weight for naval units/structures for whatever mod instance where they end up attached to a transport.

2024-07-01 15:01 UTC, Basilisk3 commented on lua/system/blueprints-units.lua
> +        end
I added it for naval units, but did not for structures because I have never seen structures being moved by transports and I would rather not add the logic if it is not necessary.

2024-07-01 15:14 UTC, Basilisk3 commented
This should be ready now, thanks for the reviews.

2024-07-01 20:01 UTC, MrRowey commented
The balance team would like to test this out first so once reviews are happy this can be merged as apart of the next iteration.

2024-07-09 10:03 UTC, MrRowey commented
are you happy with this now @lL1l1

2024-07-10 04:30 UTC, lL1l1 commented
> are you happy with this now @lL1l1

Yes.

2024-07-10 07:52 UTC, merged