Redundancies to avoid lua errors
FAForever/fa pull request #6413
Opened 2024-08-17 07:22 UTC by maudlin27

This fixes two lua errors I received in a desynced replay (was an AI vs AI game I was testing offline hence no replay ID to refer to).

The first was:
WARNING: Error running lua script: ...\gamedata\units.nx2\units\xab3301\xab3301_script.lua(52): attempt to call method `SetRate' (a nil value)
         stack traceback:
         	...\gamedata\units.nx2\units\xab3301\xab3301_script.lua(52): in function `CreateVisibleEntity'
         	...ata\faforever\gamedata\lua.nx2\lua\remoteviewing.lua(57): in function <...ata\faforever\gamedata\lua.nx2\lua\remoteviewing.lua:49>

I've therefore added a check to make sure that the method SetRate isn't called if it doesn't exist (and for completeness have done the same with the following lines calling a separate method SetTargetSpeed)

The second error was:
WARNING: Error running lua script: ...ithub\fa\lua\sim\weapons\defaultprojectileweapon.lua(414): Game object has been destroyed
         stack traceback:
         	[C]: in function `RemoveEconomyEvent'
         	...ithub\fa\lua\sim\weapons\defaultprojectileweapon.lua(414): in function <...ithub\fa\lua\sim\weapons\defaultprojectileweapon.lua:412>

For this, I added a check if the object in question returned true for IsDestroyed() before going on to call RemoveEconomyEvent.

Re-running the changes, neither error appeared.

2024-08-22 08:58 UTC, Garanas commented on lua/sim/weapons/DefaultProjectileWeapon.lua
> +        if not(self:BeenDestroyed()) then
Is this checking for the correct entity to be (not) destroyed?

It checks whether the weapon (`self`) is destroyed, but the economy event is applied to the unit (`self.unit`)

2024-08-22 09:02 UTC, Garanas commented on units/XAB3301/XAB3301_script.lua
> +                if self.Animator.SetRate then self.Animator:SetRate(1) end
I think you're checking for the wrong thing here. Whether the field (function) `SetRate` exists is not the problem - the problem is that `self.Animator` is not yet initialized.

These fields are initialized when the unit is done building. See also the body of `OnStopBeingBuilt`. That means that any logic inside this function can not run until the unit is done building. A better solution would be to check and verify that the unit is done building (there is a flag if I am not mistaken, or an engine function) and just early exit the function as a whole.

This also applies to the other changes at lines 52-55.

2024-08-22 09:02 UTC, Garanas requested changes
See the comments.

2024-08-22 09:03 UTC, Garanas commented on units/XAB3301/XAB3301_script.lua
> +                if self.Animator.SetRate then self.Animator:SetRate(1) end
This may apply to all the vision-related functionality in general, but I have not reviewed the remaining code at this moment.

2024-11-19 20:13 UTC, maudlin27 commented on lua/sim/weapons/DefaultProjectileWeapon.lua
> +        if not(self:BeenDestroyed()) then
Agreed it looks like it should check if self.unit is valid - I've made changes to the code, but my nervousness with this is I couldn't get a log added in the same place to trigger, and I dont have the replay that gave rise to the error anymore

2024-11-19 20:16 UTC, Garanas commented on lua/sim/weapons/DefaultProjectileWeapon.lua
> +        if not(self:BeenDestroyed()) then
You can use the global `IsDestroyed` instead of the table entry `BeenDestroyed` if you're afraid of whether the reference exists or not.

2024-11-19 20:30 UTC, maudlin27 commented on units/XAB3301/XAB3301_script.lua
> +                if self.Animator.SetRate then self.Animator:SetRate(1) end
I've added a check whether the unit itself is constructed (if I've understood your comments correctly) - it runs without error in a sandbox (but then in the sandbox scenario the unit was fully constructed)

2024-11-19 20:31 UTC, maudlin27 commented on lua/sim/weapons/DefaultProjectileWeapon.lua
> +        if not(self:BeenDestroyed()) then
Presumably that would be IsDestroyed(self.unit)?

2024-11-20 09:04 UTC, Garanas commented on units/XAB3301/XAB3301_script.lua
> +        if not(self.GetFractionComplete) or self:GetFractionComplete() < 1 then return nil end
Out of curiosity - why do you check for the existence of the `self.GetFractionComplete` field?

2025-02-01 18:52 UTC, BlackYps commented
What's the status here?

2025-03-07 16:56 UTC, maudlin27 commented on units/XAB3301/XAB3301_script.lua
> +        if not(self.GetFractionComplete) or self:GetFractionComplete() < 1 then return nil end
If it doesn't exist (for whatever reason) then the code would cause an error - e.g. if code elsewhere was to pass an invalid unit reference or a nil value, so I added for completeness

2025-04-11 06:14 UTC, maudlin27 commented
@Garanas See BlackYps query

2025-11-15 14:07 UTC, BlackYps commented
Closing due to inactivity. Feel free to reopen it if you pick it up again.

2025-11-15 14:07 UTC, closed without merging