Pulsar pitch range
FAForever/fa pull request #6423
Opened 2024-08-26 15:15 UTC by Basilisk3

## Description of the proposed changes

**Pulsar: T3 Mobile EMP Missile Launcher (SRL0310):**
  - Categories added:
    - "PRODUCTDL"
    - "SNIPEMODE" 
  - Othismash EMP Missile Barrage:
    - DamageRadius: 0 --> 2 (same as Hoplite)
    - TurretPitchRange: 15 --> 25 (required against nearby units)

## Explanation of the changes

- The `PRODUCTDL` category is added as the Pulsar is content added outside of the main game and the expansion.
- The `SNIPEMODE` category is added as it is instrumental for using the Pulsar against ACU's equipped with personal shields. The Absolver also has this category.
- Its weapon gains the ability to deal damage in an AoE, differentiating it more from the Absolver. Right now, the Pulsar is essentially an Absolver with lower range and no hover ability. The effects of the missiles appear like they deal AoE damage.
- The `TurretPitchRange` is increased so it can hit units close to its model. Right now, this is not the case; its missiles will overshoot closer units. The model does provide enough leeway to make this change.

## Checklist
- [ ] Changes are documented in the changelog for the next game version

2024-08-26 19:16 UTC, lolaenter commented
when we will get pulsar in 3v3?

2024-08-27 17:18 UTC, Basilisk3 commented
> when we will get pulsar in 3v3?

I do not have an ETA currently, but you can try asking in one of the dev-channels on Discord.

2024-09-21 20:04 UTC, BlackYps commented on projectiles/CIFOthismashEMPMissile01/CIFOthismashEMPMissile01_proj.bp
>      Interface = { HelpText = "Othismash EMP Missile" },
This should probably be renamed to Pulsar as well

2024-09-22 09:22 UTC, BlackYps requested changes
Change the missile name and fix the commit issues, then this is good to go

2024-09-22 09:22 UTC, BlackYps commented on lua/version.lua
> -local Commit = 'unknown'    -- The use of `'` instead of `"` is **intentional**
You have the postprocess commit in your commit history because you were starting your branch from deploy/fafdevelop instead of develop

2024-09-22 09:53 UTC, Basilisk3 commented on lua/version.lua
> -local Commit = 'unknown'    -- The use of `'` instead of `"` is **intentional**
Thanks, fixed.

2024-09-23 20:51 UTC, BlackYps approved these changes

2024-09-27 15:51 UTC, merged