Fix error when full share transfers units to a dead player
FAForever/fa pull request #6432
Opened 2024-09-04 22:04 UTC by lL1l1

## Issue
Reported on [Discord](https://discord.com/channels/197033481883222026/1277749416878669925). Replay [23190625](https://replay.faforever.com/23190625).
```
WARNING: Error running lua script: ...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua(498): bad argument #1 to `getn' (table expected, got no value)
         stack traceback:
         	[C]: in function `getn'
         	...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua(498): in function <...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua:479>
         	...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua(526): in function `TransferUnitsToHighestBrain'
         	...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua(608): in function <...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua:440>
```
The game tried to transfer units to a defeated player which causes the `TransferUnitsOwnership` function to return nil, and `TransferUnitsToBrain` didn't handle this case before putting the results into `table.getn`.

## Description of the proposed changes

Add a guard so that it puts an empty table into `getn` if the result is nil.

## Testing done on the proposed changes

Running the replay again with the changes properly transfers the units after the player dies.
To run the replay with changes from your local repo, load the replay from the FAF client to unpack it, and then run the console command: 
```
UI_Lua LaunchReplaySession('C:/ProgramData/FAForever/data/cache/temp.SCFAReplay')
```

## Checklist
- [x] Changes are annotated, including comments where useful
  - The `TransferUnitsOwnership` function has a proper return value of `Unit[]?`
- [ ] Changes are documented in the changelog for the next game version

2024-09-06 14:14 UTC, 4z0t requested changes

2024-09-06 14:14 UTC, 4z0t commented on lua/aibrain.lua
> +                            local givenUnitCount = table.getn(TransferUnitsOwnership(units, brain.index) or {})
Overthinking. Put function result into a variable and check against nil.

2024-09-06 20:24 UTC, lL1l1 commented on lua/aibrain.lua
> +                            local givenUnitCount = table.getn(TransferUnitsOwnership(units, brain.index) or {})
Thanks, also I can use `next()` instead of `table.getn > 0`.

2024-09-07 13:23 UTC, 4z0t commented on lua/aibrain.lua
> +                            local givenUnitCount = table.getn(TransferUnitsOwnership(units, brain.index) or {})
Also bad idea. `table.empty` would be more understandable.

2024-09-07 13:25 UTC, 4z0t requested changes

2024-09-07 13:25 UTC, 4z0t commented on lua/aibrain.lua
> +                            if givenUnits and next(givenUnits) then
Use `table.empty` instead.

2024-09-09 13:45 UTC, 4z0t commented
I doublt `table.empty` accepts `nil`

2024-09-09 14:00 UTC, lL1l1 commented
It does accept nil:
https://github.com/FAForever/fa/blob/2d1e06ad6a435fee7aaad5cccbbdbd03d1352e30/lua/system/utils.lua#L59-L62

2024-09-09 14:35 UTC, lL1l1 commented
Console command:
```lua
SimLua 
LOG('"table.empty":', table.empty, '"table.empty(nil)"', table.empty(nil))
LOG('"table.empty2":', table.empty2, '"table.empty2(nil)"', table.empty2(nil))
```
Output:
```
info: "table.empty":	function: 22180F28	"table.empty(nil)"	true
info: "table.empty2":	cfunction: 1AF80C00	"table.empty2(nil)"	true
```

2024-09-09 14:37 UTC, lL1l1 commented
Also `debug.getinfo` says that `table.empty` in Sim is sourced from `/lua/system/utils.lua`

2024-09-09 14:42 UTC, 4z0t commented
It is seems like a bug. Currently pending.

2024-09-09 14:54 UTC, 4z0t commented
https://github.com/FAForever/fa/pull/6439

2024-09-09 15:00 UTC, 4z0t approved these changes

2024-09-10 02:19 UTC, merged