Create script converting markdown-based changlog to lua-based changelog
FAForever/fa pull request #6444
Opened 2024-09-12 00:23 UTC by Zjonn

Resolves #6237
Please take a look @Garanas 

## Description

Following PR is introducing python script converting Markdown files to Lua. 
Markdown files are formatted before conversion to Lua file using [mdformat](https://github.com/executablebooks/mdformat) (it's python alternative to prettier).

Why I chose python? There are several reasons:
- It comes preinstalled in most Linux distibutions
- Installed packages do not pollute the user environment (when using venv)
- Has better linters than for example bash (shellcheck)

Additionaly I wrote `setup_python_env.sh` script for users not familiar with python, it can create python virtual enviorement for them, install required packages and source it.

## Testing done on the proposed changes
Tested manually in local environment

## Checklist
- [ ] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

2024-09-16 06:15 UTC, Garanas commented
Hi @Zjonn, this looks exciting! I'll make some time next weekend to review it. Would you like me to incorporate it further into the workflow, or would you like to try and do that yourself?

2024-09-16 17:22 UTC, Zjonn commented
Hi @Garanas 
I will add this to the workflow myself (I hope 😄 ).

2024-09-22 10:42 UTC, BlackYps commented
Please set it to ready for review once you are done with your changes

2024-09-22 22:59 UTC, Zjonn commented
I added a workflow that can be run manually or through another workflow. 
This has been tested in my fa fork, the results are as follows https://github.com/Zjonn/fa/actions/runs/10984939551

In short:
- it takes all `*.md` files from changelog directory
- runs `markdown2lua.py` on each of them
- saves results in `lua_changlog` directory, which is later uploaded as an artifact

2024-10-04 11:56 UTC, Garanas requested changes
In general it looks good and the output is as promised! 

A general suggestion:

- (1) Generated files should be marked as generated. Please add a header block of comments stating that the lua changelog files are generated. Preferably with a reference to the source file and the logic responsible for generating it.

And two functional requests: 

- (1) The changelog files will be loaded as regular modules, via either the `import` statement or the `doscript` statement. For this the table inside the file needs to be named. Can you add a `Changelog = {...}` in front of each table?

- (2) It would good if the integrity of the generated lua files are checked automatically. In a separate job you can install Lua, retrieve the artifact and check that all files can be interpret. The step should fail if one (or more) files can not be interpret. Make sure to use the [needs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds) field to tell the interpreter about the dependency between the jobs.

The last job is especially relevant since maintainers come and go. Not everyone may be aware of the details of this workflow file. And by testing the output automatically we can catch 'simple' issues long before it would reach any staging or production area.

For future reference, this was the output the review was made with:

- [lua_changelog.zip](https://github.com/user-attachments/files/17257699/lua_changelog.zip)

It took a bit longer to review this than anticipated, life got in between 😃 .

2024-10-04 11:56 UTC, Garanas commented on scripts/markdown2lua.py
It is best to put these scripts in the following folder:

- https://github.com/FAForever/fa/blob/develop/.github/workflows/scripts

That way all the source files that are related to workflows are close to the source files of the workflows. 

Perhaps the file can be called `changelog-markdown-to-lua.py`, to match the convention of the other files.

2024-10-04 11:56 UTC, Garanas commented on scripts/requirements.txt
I am not _that_ familiar with a Python programming environment. Given the results of Google, I suspect such a file as this is common practice. Just like `scripts/markdown2lua.py`, it is best to move this file to: https://github.com/FAForever/fa/blob/develop/.github/workflows/scripts

But given the generic name, maybe it is better if both this and the python file is in its own subfolder? That way future python scripts with different requirements would not clash. But again - I have little to no experience with Python so do share your thoughts.

2024-10-04 11:56 UTC, Garanas commented on scripts/setup_python_env.sh
Same suggestion as with the other two files in this folder - please move it to:
- https://github.com/FAForever/fa/blob/develop/.github/workflows/scripts

2024-10-04 18:01 UTC, Zjonn commented
Thanks for the review @Garanas.
I'll temporarily mark PR as a draft version to satisfy @BlackYps ;)

I like the idea of adding information that the file was generated automatically and how

>  Can you add a Changelog = {...} in front of each table?

Sure, no problem

> ld fail if one (or more) files can not be interpret. Make sure to use the [needs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds) field to tell the interpreter about the dependency between the jobs.

Thanks for the tip

2024-10-04 21:04 UTC, Zjonn commented on scripts/markdown2lua.py
One of the things I really like about Python is [PEP8](https://peps.python.org/pep-0008/#package-and-module-names), which defines a style guide for the entire language, taking file names into account as well. I wish more languages would do the same 😄. 

Having said that, `-` in file name is no go, but `changelog_markdown_to_lua.py` is, but it seems unnecesarry long to me, how about `changelog_markdown2lua.py`?

2024-10-04 21:11 UTC, Zjonn commented on scripts/requirements.txt
Yes, requirements.txt is the simplest way to go. If you were developing a package, you would probably choose poetry these days and end up with a .toml file, but there is no need to complicate things, simple, well-known requirements should be enough.

Also, I don't know if anyone will want to use this script on Windows, but if they do, it might be a good idea to put a README.md in the scripts directory with the instruction that they need to install requirements.txt first.

I have mixed feelings about simply adding `python` subfolder in the `scripts`. 

```
scripts
|----python
      |---- markdown2lua.py
|----changelog-combine.sh
```

Doesn't look the best to me. I agree that it's a good idea to keep Python-related stuff in separate directories, so I suggest making separate directories for bash scripts as well, that way we end up with
scripts

```
|---- python
      |---- markdown2lua.py
|---- bash
      |---- changelog-combine.sh
```

What do you think?

2024-10-05 06:13 UTC, Garanas commented on scripts/requirements.txt
What if we go with feature-based naming, instead of language-based? For your python script it would be something like `markdown-to-lua` and then the main python script can be called `main.py` (or what the usual convention is). What are your thoughts on that?

2024-10-05 06:16 UTC, Garanas commented on scripts/requirements.txt
I see now your previous comment about pep8 - I'll leave this decision to you. Since you're clearly more aware of the best practices than I am, haha. But everything should reside in the `scripts` folder inside the `workflows` folder.

2024-10-05 06:27 UTC, Garanas commented on scripts/markdown2lua.py
See also my comment here: https://github.com/FAForever/fa/pull/6444#discussion_r1788521168

2024-10-06 17:26 UTC, Zjonn commented on scripts/markdown2lua.py
> +#{f"This file was autogenerated using {SCRIPT_NAME:}":^{MAX_LINE_LENGTH - 2}}#
Thanks, I had completely forgotten to check this, muscle memory worked

2024-10-06 17:31 UTC, Zjonn commented on scripts/requirements.txt
I wanted to revisit your idea of putting Python-related stuff in `scripts/python` (by `scripts` I mean the `scripts` directory in the `workflows` folder.

What do you think of the following directory structure, I will adapt to your decision.
```
scripts
|---- python
      |---- python_related_stuff.py
|---- bash
      |---- currently-existing-scripts.sh
```

2024-10-06 17:39 UTC, Zjonn commented on scripts/markdown2lua.py
> +#{f"This file was autogenerated using {SCRIPT_NAME:}":^{MAX_LINE_LENGTH - 2}}#
Can look like this?
```lua
------------------------------------------------------------------------------------------------------------------------------------------------------
--                                                This file was autogenerated using markdown2lua.py                                                 --
--                                                           Source: fa/changelog/3636.md                                                           --
------------------------------------------------------------------------------------------------------------------------------------------------------
```

2024-10-07 06:48 UTC, Garanas commented on scripts/requirements.txt
That seems fine, but how does one deal with conflicting `requirements.txt` files if we have multiple in the future?

2024-10-07 21:41 UTC, Zjonn commented on scripts/requirements.txt
There should be only one `requirements.txt` file, shared by all scripts. It will be the responsibility of the implementer not to affect other scripts if it decides to change the requirements already defined.

2024-10-07 23:25 UTC, Zjonn commented
I think I have made all the changes we have discussed. You can find newest workflow results [here](https://github.com/Zjonn/fa/actions/runs/11225533050).

Validation job reuses already existing `tests/run-syntax-test.sh`, I made it executable (`chmod +x`). 
I also moved all workflow bash scripts into bash subdirectory.

2024-10-08 12:16 UTC, Garanas approved these changes
Excellent work 👍

2024-10-08 12:18 UTC, merged

2024-10-08 12:29 UTC, Garanas commented
As an extension to your work here: https://github.com/FAForever/fa/issues/6472 , with that we have everything we need to start updating the Lua of the game. We'll save several megabytes of memory all together and we'll have consistent changelogs 😃 !

2024-10-08 19:17 UTC, Garanas commented
@Zjonn I forgot - the contributions have no license at the top of the file. Would it be fine to license the contributions of this pull request with the MIT license?

2024-10-10 13:31 UTC, Zjonn commented
@Garanas for some reason I don't see notifications when you are pinging me. MIT license sounds perfect! 

About #6472, I can't wait to see the end result. Amount of deleted lines in there looks great.