Small bug fixes for shields
FAForever/fa pull request #6445
Opened 2024-09-12 10:53 UTC by lL1l1

## Description of the proposed changes

- Fix overcharge dealing half damage to shields. Reported on [Discord](https://discord.com/channels/197033481883222026/1283134865604218953).
- Prevent tree effect damage from going through shields
- Move anti-shield area damage before the normal area damage so that the normal damage can overkill things under the shield if the anti-shield damage kills the shield.

## Testing done on the proposed changes

Shooting overcharge at a shield in a forest and checking its HP and that the trees on the other side don't get knocked down.

## Checklist
- [x] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

2024-09-22 10:35 UTC, BlackYps requested changes
Other than the slip in the comments it looks good. Also tested it and it works

2024-09-22 10:35 UTC, BlackYps commented on lua/shield.lua
> +        -- In the past it used to be 0.25 absorption for static shields (due to structure armor) and needed a 2x multiplier.
```suggestion
        -- In the past it used to be 0.25 absorption for static shields (due to structure armor) and needed a 2x division.
```

2024-09-23 13:25 UTC, lL1l1 commented on lua/shield.lua
> +        -- In the past it used to be 0.25 absorption for static shields (due to structure armor) and needed a 2x multiplier.
Seems like the explanation is unclear. With 0.25 absorption we had a 0.25 damage and 0.75 damage instance hitting the shield. Both get set to 800 OC structure damage, but then 0.25x armor is applied again (second `OnGetDamageAbsorption` call), reducing it to 2x200 damage, which requires a 2x multiplication to bring it to the expected 800.

The old version of the line:
https://github.com/FAForever/fa/blob/aa17c0cf95570b71e2702db888e681dcdae23efe/lua/shield.lua#L514-L515

2024-09-23 20:47 UTC, BlackYps commented on lua/shield.lua
> +        -- In the past it used to be 0.25 absorption for static shields (due to structure armor) and needed a 2x multiplier.
Yeah, it's indeed a bit confusing. I was looking at the removed / 2 division in line 523 and 525 and thought you meant that.

2024-09-23 20:49 UTC, BlackYps commented on lua/shield.lua
> +        -- In the past it used to be 0.25 absorption for static shields (due to structure armor) and needed a 2x multiplier.
What is the purpose of this comment anyway? I'm not sure what it is supposed to achieve and if I were to read it at some point in the future I'm not sure if I would understand what it is trying to tell me

2024-09-24 07:50 UTC, lL1l1 commented on lua/shield.lua
> +        -- In the past it used to be 0.25 absorption for static shields (due to structure armor) and needed a 2x multiplier.
I'm trying to warn about how setting this damage value is wrong and can lead to issues if not all damage is absorbed, since the unabsorbed remainder also hits the shield and gets set + applied armor against again.

2024-09-24 11:28 UTC, BlackYps commented on lua/shield.lua
> +        -- In the past it used to be 0.25 absorption for static shields (due to structure armor) and needed a 2x multiplier.
I think we should just include your example in the comment and make the wording more clear. My proposal:

If the absorption multiplier is less than 1, then the shield will get hit by two instances of area damage, the absorbed amount and the remainder.
This means that the following code then requires a multiplier to correct the total damage amount since both instances will be overriden.
For example with 0.25 absorption we would have a 0.25 damage and 0.75 damage instance hitting the shield. Both get set to 800 OC structure damage, but then 0.25x armor is applied again (second OnGetDamageAbsorption call), reducing it to 2x200 damage, which requires a 2x multiplication to bring it to the expected 800.
Currently the absorption multiplier is 1, so we don't need a multiplier on the damage to balance it out.

2024-11-19 16:26 UTC, BlackYps approved these changes

2024-11-19 16:42 UTC, merged