Move `RollOfUnit()` to after the "finished building" animation
FAForever/fa pull request #6456
Opened 2024-09-21 22:49 UTC by lL1l1

## Description of the proposed changes

Fixes #5625. UEF and Cybran air factories have an animation that locks the unit's orientation, interfering with the rolloff rotation. The changes move the rolloff rotation to happen after the animation finishes.

## Testing done on the proposed changes

Spawn factories, give a rally point on one side, order an engineer, and then change the rally point to the other side before the engineer finishes building and see that it now gets rotated correctly in the UEF and Cybran factories.
```
   CreateUnitAtMouse('xab1401', 0,    0.14,   -8.65, -0.00000)
   CreateUnitAtMouse('xsb0302', 0,   -4.04,    2.16,  0.00000)
   CreateUnitAtMouse('ueb0302', 0,   11.96,    2.16,  0.00000)
   CreateUnitAtMouse('urb0302', 0,    3.96,    2.16,  0.00000)
   CreateUnitAtMouse('uab0302', 0,  -12.04,    2.16,  0.00000)
```

## Checklist
- [x] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

2024-10-19 18:05 UTC, clyfordv requested changes
This introduces a bug where the a land unit built from a relevant air fac wants to nav back to the roll off point after the rally point. See something similar here where an order is slipped in right at the moment of construction with odd behavior: https://discord.com/channels/197033481883222026/1144605729911738439/1238254471662927943 

Stock:
![image](https://github.com/user-attachments/assets/4f444c6c-f1cc-41ca-8358-9b65ee91a6d6)

With change:
![image](https://github.com/user-attachments/assets/f8fadf0f-07c3-4aae-b1a1-540f59cbe9a5)

My read on why this occurs is that the rally point order chain issuing is extra special somewhere in the engine (apropos nothing it would be nice to expose that to lua a little more, to enable more sophisticated roll off behavior). I think if you want to implement this as-is you'll have to manually re-check the unit's orientation and update if necessary.

2024-10-23 12:27 UTC, lL1l1 commented
This fixes it but the code style may be sloppy, although I think it's the most efficient solution.

2024-11-03 16:30 UTC, Basilisk3 commented
Tested and works as expected, in addition to being an important change for gameplay.

2024-11-21 17:53 UTC, clyfordv approved these changes
Tested, good to go

2024-11-24 13:12 UTC, BlackYps commented
We'll include this one as well because we now have more time for testing with the delayed release

2024-11-24 13:13 UTC, merged