Balance cost and DPS stats of T3 arty
FAForever/fa pull request #6481
Opened 2024-10-19 05:33 UTC by lL1l1

## Issue
[Related Discord thread.](https://discord.com/channels/197033481883222026/1272828981367803967) Currently it's well known that Aeon arty is by far the best T3 arty. It has double the alpha damage of other arties (can one shot shields with only two arties, one shots targets if it hits), has better dps per unit and dps per mass than other arties (compared to Cybran: 19%/mass 24%/unit), and has very good accuracy that boosts the damage output compared to others even further.
To a lesser known extent, UEF arty is 10% better DPS per mass than Cybran arty, and 8% compared to Sera, so in general T3 arties could use some balance altogether. Balancing the arties altogether is a good first step before seeing if Aeon arty needs to be addressed.

## Description of the proposed changes

### Balance of arty DPS by cost:
1. Aeon arty set to 79k mass in proportion to old UEF arty DPS/M.
2. Arty costs spread evenly across 70-79k mass. Arty costs are not reduced below their current costs because that would make them come out earlier.
3. Damage adjusted for more per-artillery variety in shots to kill T3 shields, while also evening out STK vs different faction T3 shields.
4. Reload adjusted so that avg DPS vs T3 shields (this accounts for regen) per mass is equal to Aeon arty.
5. Energy and buildtime adjusted for the new mass costs with some rounding, but practically the same per-mass ratios.

## Testing done on the proposed changes

Shooting at a test target, no artillery seems excessively powerful, due to the inaccuracy massively reducing the DPS of artillery with high splash radius.
<details> <summary> Spawn target command: </summary>

UEF structure/Seraphim shield air grid test target spawned at the edge of the arty range so that the top shield edge is roughly at max range of the artillery:
```
CreateUnitAtMouse('xsb4301', 1,    3.63,   11.13, -0.00017)
CreateUnitAtMouse('ueb0302', 1,  -27.38,  -11.88, -0.00009)
CreateUnitAtMouse('ueb1301', 1,   12.63,  -11.88,  0.00010)
CreateUnitAtMouse('ueb1301', 1,  -11.38,   12.13,  0.00000)
CreateUnitAtMouse('ueb1301', 1,  -19.38,    4.13,  0.00000)
CreateUnitAtMouse('zeb9602', 1,  -11.38,   20.13,  0.00018)
CreateUnitAtMouse('zeb9602', 1,  -11.38,    4.13, -0.00024)
CreateUnitAtMouse('zeb9602', 1,  -19.38,   12.13,  0.00012)
CreateUnitAtMouse('zeb9602', 1,   -3.38,   12.13, -0.00011)
CreateUnitAtMouse('zeb9602', 1,   12.63,   -3.88, -0.00113)
CreateUnitAtMouse('zeb9602', 1,    4.63,  -11.88, -0.00152)
CreateUnitAtMouse('zeb9602', 1,   12.63,   12.13, -0.00060)
CreateUnitAtMouse('ueb1301', 1,   12.63,    4.13, -0.00086)
CreateUnitAtMouse('zeb9602', 1,   20.63,    4.13, -0.00052)
CreateUnitAtMouse('xsb4202', 1,   -0.38,  -18.88, -0.00008)
CreateUnitAtMouse('xsb4301', 1,  -12.38,   -2.88, -0.00043)
CreateUnitAtMouse('xsb4301', 1,    5.63,  -18.88, -0.00032)
CreateUnitAtMouse('xsb4202', 1,  -12.38,  -10.88, -0.00014)
CreateUnitAtMouse('zeb9602', 1,  -27.38,    4.13,  0.00009)
CreateUnitAtMouse('zeb9602', 1,  -19.38,   -3.88,  0.00000)
CreateUnitAtMouse('xsb4202', 1,   25.63,   -4.88,  0.00022)
CreateUnitAtMouse('xsb4202', 1,    3.63,   17.13,  0.00000)
CreateUnitAtMouse('xsb4301', 1,   19.63,   -4.88,  0.00129)
CreateUnitAtMouse('zeb9602', 1,   20.63,  -11.88,  0.01918)
CreateUnitAtMouse('zeb9602', 1,   12.63,  -19.88,  0.07159)
CreateUnitAtMouse('zeb9602', 1,   -3.38,   -3.88, -0.00042)
CreateUnitAtMouse('ueb1301', 1,   -3.38,    4.13, -0.00019)
CreateUnitAtMouse('zeb9602', 1,    4.63,    4.13, -0.00056)
CreateUnitAtMouse('ueb1301', 1,    4.63,   -3.88, -0.00121)
CreateUnitAtMouse('xsb4301', 1,  -20.38,  -10.88,  0.00018)
CreateUnitAtMouse('ueb1301', 1,  -27.38,   -3.88,  0.00006)
```
</details>

## Additional context

A separate PR will address the accuracy balance, as it is a much more difficult question with the randomness and splash damage involved.

## Checklist
~~- [ ] Changes are annotated, including comments where useful~~
- [ ] Changes are documented in the changelog for the next game version

2024-10-19 16:49 UTC, clyfordv requested changes, later dismissed
Tested, changes are good, only issue is the mass cost for the Emissary is reversed in the changelog.

2024-10-22 17:07 UTC, MrRowey commented
Do you have BT Approval due to the Cost Chanage?

2024-10-22 19:22 UTC, lL1l1 commented
There hasn't been a vote yet, but there is a thread (with discussion) for it in the balance team chat and the outlook for getting approval is positive imo. Just might be delayed a bit due to team lead switching.

For example the DPS being adjusted along with cost increases is the result of the discussion with balance team after initially proposing a simple cost reduction for weaker artilleries.

2025-05-07 12:05 UTC, Rhaelya approved these changes
Everything looks in order

2025-05-07 12:12 UTC, merged

2025-05-07 12:12 UTC, Rhaelya approved these changes