Update UEF SACU Enhancement Script
FAForever/fa pull request #6515
Opened 2024-11-07 16:01 UTC by MrRowey

Following on the changes of https://github.com/FAForever/fa/pull/6498

## Checklist
- [x] Changes are annotated, including comments where useful
- [x] Changes are documented in the changelog for the next game version

2024-11-10 06:20 UTC, Garanas requested changes

2024-11-10 06:20 UTC, Garanas commented on units/UEL0301/UEL0301_script.lua
> +        if self.ProcessEnhancementRadarJammer and self:IsIntelEnabled('Jammer') then
This is an unintentional change - it would always be true. See also the `RadarJammerEnh` field that is set to `true`/`false` depending on whether the enhancement exists.

2024-11-10 06:20 UTC, Garanas commented on units/UEL0301/UEL0301_script.lua
> +    ProcessEnhancementPod = function(self, bp)
Please add the basic annotations, which would boil down to the following in my opinion:

```
---@param self UEL0001
---@param enhancementBlueprint table
```

2024-11-11 13:29 UTC, MrRowey commented on units/UEL0301/UEL0301_script.lua
> +    ProcessEnhancementPod = function(self, bp)
yes, theses were meant to be marked as draft as I had not got around to doing the annotation.

2024-11-11 20:40 UTC, MrRowey commented on units/UEL0301/UEL0301_script.lua
> +        if self.ProcessEnhancementRadarJammer and self:IsIntelEnabled('Jammer') then
After looking at this can't this just be a part of the 2 Functions for the enhancements now?

2024-11-11 20:42 UTC, MrRowey commented on units/UEL0301/UEL0301_script.lua
> +        if self.ProcessEnhancementRadarJammer and self:IsIntelEnabled('Jammer') then
So something like

```lua
    ---@param self UEL0301
    ---@param bp UnitBlueprintEnhancement
    ProcessEnhancementRadarJammer = function(self, bp)
        self.RadarJammerEnh = true
        self:SetIntelRadius('Jammer', bp.NewJammerRadius or 26)
        self:EnableUnitIntel('Enhancement', 'Jammer')
        self:AddToggleCap('RULEUTC_JammingToggle')

        if self.RadarJammerEnh == true then
            if self.IntelEffects then
                self.IntelEffectsBag = {}
                self:CreateTerrainTypeEffects(self.IntelEffects, 'FXIdle',  self.Layer, nil, self.IntelEffectsBag)
            end
            self:SetEnergyMaintenanceConsumptionOverride(bp.MaintenanceConsumptionPerSecondEnergy or 0)
            self:SetMaintenanceConsumptionActive()
        end

    end,
    ```

2024-11-11 20:43 UTC, MrRowey commented on units/UEL0301/UEL0301_script.lua
> +        if self.ProcessEnhancementRadarJammer and self:IsIntelEnabled('Jammer') then
but then do you even need the `self.RadarJammerEnh = true` if the part its setting ti for can now be apart of the same function as it wasn't before ?

2024-11-11 20:53 UTC, lL1l1 commented on units/UEL0301/UEL0301_script.lua
> +        if self.ProcessEnhancementRadarJammer and self:IsIntelEnabled('Jammer') then
You can't inline `OnIntelEnabled` because that function is called when the jamming toggle is pressed (or whenever else the jammer is enabled), while the enhancement function is called only once when the enhancement is built. Same for `OnIntelDisabled`.

If you did inline it, then the jammer's FX and and energy consumption would remain permanently on until the enhancement is removed.

2024-11-17 15:49 UTC, Garanas approved these changes

2024-11-18 17:02 UTC, merged