fix GetAngleInBetween parameter references
FAForever/fa pull request #6525
Opened 2024-11-10 06:39 UTC by relent0r

## Description of the proposed changes
Fixes a small bug in the refactor of GetAngleInBetween. It was references indexes but the function that calls it is using named keys.

closes #6524

## Testing done on the proposed changes
Tested to make sure the scathis does not error and shoots things.

## Checklist
- [ ] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

2024-11-10 07:56 UTC, lL1l1 requested changes
Good find for my refactor messing up the mathematics, it should indeed be `z1 * z1` and `z2 * z2`.

I tested the changed math with my fixed Scathis and they make the fake barrels align with the aim barrel more accurately (when you view the wireframe skeletons).

2024-11-10 07:56 UTC, lL1l1 commented on lua/utilities.lua
>      local z2Sq = z2 * z2
```suggestion
```

2024-11-10 07:56 UTC, lL1l1 commented on lua/utilities.lua
> +    local len2 = MathSqrt((x1 * x1 + y1 * y1 + z1Sq) * (x2 * x2 + y2 * y2 + z2Sq))
```suggestion
    local dot = x1 * x2 + y1 * y2 + z1 * z2
    local len2 = MathSqrt((x1 * x1 + y1 * y1 + z1 * z1) * (x2 * x2 + y2 * y2 + z2 * z2))
```

2024-11-10 07:56 UTC, lL1l1 commented on lua/utilities.lua
> +    local x2, y2, z2 = v2.x, v2.y, v2.z
I think it's better to fix Scathis to use Vectors (https://github.com/FAForever/fa/commit/00c835fa6894dea25690e2aa36a897d7a0e9c7bd) instead of diverging from how the rest of vector processing code works.
Array access for Vectors is also better than hash access, since it avoids the metamethod that redirects `x` `y` `z` keys to `1` `2` `3` indices.

2024-11-10 08:34 UTC, lL1l1 commented
Note: caused by #6438 
You can also simply add this PR's number to the snippet `other.6438.md` for the changelog requirement, since it is essentially part of the same patch.

2024-11-10 19:18 UTC, relent0r commented
> Good find for my refactor messing up the mathematics, it should indeed be `z1 * z1` and `z2 * z2`.
> 
> I tested the changed math with my fixed Scathis and they make the fake barrels align with the aim barrel more accurately (when you view the wireframe skeletons).

Thanks, I can see your making the updates in 6528 for function call, once you merge that in I'll update this to match.

2024-11-11 04:18 UTC, relent0r commented on lua/utilities.lua
> +    local x2, y2, z2 = v2.x, v2.y, v2.z
Have reverted to using indexes in prep for the other PR.

2024-11-11 13:58 UTC, lL1l1 commented on changelog/snippets/other.6438.md
> +- (#5061, #6438, #(6525)) Add metamethods and utility functions for Vectors and Quaternions to simplify and clean up the code involving operations with them.
```suggestion
- (#5061, #6438, #6525) Add metamethods and utility functions for Vectors and Quaternions to simplify and clean up the code involving operations with them.
```
Should remove the extra paranthesis and this can be merged in

2024-11-12 20:00 UTC, merged