annotate orders.lua
FAForever/fa pull request #6558
Opened 2024-11-26 03:14 UTC by clyfordv

## Description of the proposed changes
Annotates functions and squashes errors in orders.lua w/ small changes to related files.

Branched from: https://github.com/FAForever/fa/pull/6557

2024-11-27 16:17 UTC, Garanas commented
It appears that https://github.com/FAForever/fa/pull/6557 was merged in with an invalid snippet format. It states `feature` instead of `features`, my mistake for approving.

2024-11-27 17:12 UTC, clyfordv commented
Yoink. Not totally clean, but I'll fix it in this PR instead of making a new one?

2024-12-09 02:56 UTC, lL1l1 commented
@clyfordv Is it okay with you if I rebase and force push this branch? It will make reviewing it easier for me.

2025-03-05 01:13 UTC, lL1l1 requested changes
@clyfordv I went through the PR and wrote suggestions for the PR in https://github.com/clyfordv/fa/pull/2 since they covered quite some details. If you could review the suggestions over there and merge it in then I can approve this one.

2025-03-05 01:14 UTC, lL1l1 commented on engine/User/UserUnit.lua
> +---@field Dead boolean
Fixed in the PR with the suggestions*

2025-03-05 01:14 UTC, lL1l1 commented on lua/ui/game/orders.lua
>  local function IsToggleMode(unitList, variable, value)
Fixed in the PR with the suggestions*

2026-03-22 19:16 UTC, BlackYps commented
Whats the status here?

2026-09-09 11:17 UTC, BlackYps commented
Closing due to inactivity.
In an effort to bring the number of open pull requests under control, I'm closing old ones that seem to have stalled. You are free to open them again, if you are still interested in getting them merged. Please familiarize yourself with our updated [contribution guidelines](https://github.com/FAForever/fa/blob/develop/CONTRIBUTING.md) that explain the new process of how to get a pull request merged. I also encourage you to use the status labels to signal to other contributors the state of the pull request.

2026-09-09 11:17 UTC, closed without merging

2026-11-10 19:51 UTC, lL1l1 commented
Superseded by #7395, which carries this work and the review suggestions from clyfordv/fa#2, updated to current develop.