Expose player ratings and divisions to the session
FAForever/fa pull request #6569
Opened 2024-11-30 16:22 UTC by Garanas

## Description of the proposed changes

Extends https://github.com/FAForever/fa/pull/6479 by implementing the details of https://github.com/FAForever/fa/pull/6160. I'm not sure how I forgot about this - the rating and divisions are also not part of the checklist. 

## Testing done on the proposed changes

Extended the launch script made by @lL1l1 to include (sub)divisions. Launch the game via the script. Observe the divisions in the scoreboard.

## Additional context

Discussion on [Discord](https://discord.com/channels/197033481883222026/1312271501776388146) whether we should show this data by default to players.

## Checklist

- [x] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

2024-12-02 07:29 UTC, lL1l1 reviewed
- Technically divisions aren't needed in the Sim, `GetFrontEndData` and `SetFrontEndData` would be the correct choice, if we ignore being consistent with ratings and clan tags.
- The `/clan` arg also needs to be passed to the UI of other players for clan tags to work. It goes into the `gameInfo.GameOptions.ClanTags` field https://github.com/FAForever/fa/blob/6208f257759778bf9509455d64dc8d68d52d3053/lua/ui/lobby/lobby.lua#L2238
Unfortunately we can't use front end data due to backwards compatibility unless you add a meta table to `SessionGetScenarioInfo().Options.ClanTags` with 
```lua
__index = function(i) 
  return GetFrontEndData("ClanTags")[i] 
end
```
or simply duplicate the code, if it's not being used often anyway (we will only ever have 2 lobbies).
- The lobby does some safeguards for args in case the arg is an empty string and causes the next arg to be grabbed instead of the value (since an empty string is not a valid token for the arg getter).
https://github.com/FAForever/fa/blob/6208f257759778bf9509455d64dc8d68d52d3053/lua/ui/lobby/lobby.lua#L159-L181
This safeguarding is similar to what I did for `GetCommandLineArgTable` more recently:
https://github.com/FAForever/fa/blob/b872a718f8c026690b6b95e475c06b356137f4e4/lua/system/utils.lua#L744-L769

2024-12-02 17:30 UTC, Garanas commented
> * Technically divisions aren't needed in the Sim, `GetFrontEndData` and `SetFrontEndData` would be the correct choice, if we ignore being consistent with ratings and clan tags.

I wonder if these show up in the replay somewhere.

2024-12-05 04:54 UTC, lL1l1 commented
Mentioning replays, it's best to put it in the sim so that replays have a copy of clan tags/divisions/rating through the scenario info table.

2024-12-05 16:25 UTC, BlackYps commented
They should be handled in the same way as ratings and clans. They should all not be lost when watching the replay.

2024-12-05 21:03 UTC, Garanas commented
@lL1l1 is https://github.com/FAForever/fa/pull/6569/commits/1c6384b80043bd4ad474886f2dda7f647c6f1880 roughly the right direction for proper command line parsing?

2024-12-06 15:59 UTC, Garanas commented
@BlackYps it now also supports clan tags.

2024-12-09 00:48 UTC, lL1l1 requested changes
I think all that is necessary is some "get arg or default" function:
```lua
GetCommandLineArgOrDefault = function(option, default)
  local arg = GetCommandLineArg(option, 1)[1]
  if not arg or string.sub(arg, 0, 1) == "/" then
    return default
  else
    return arg
  end
end
```
This guards against the empty string (fromt client) arg case with the least complexity.

2024-12-09 00:48 UTC, lL1l1 commented on lua/ui/lobby/autolobby/components/AutolobbyArguments.lua
> +        if arguments and (not option[ arg[1] ]) then
Why not check `string.sub(arg[1], 0, 1) == "/"`? 
- It's much simpler than keeping a list of all valid command line arguments (which get preceded and effectively overwritten by the client's own cmdline args anyway).

2024-12-09 00:48 UTC, lL1l1 commented on lua/ui/lobby/autolobby/components/AutolobbyArguments.lua
> +    GetCommandLineArgumentNumber = function(self, option, default)
Not sure if verifying as thoroughly as checking types is necessary, it just adds to the load of thinking which function is best to use without improving the solution to the original issue: The guards in `lobby.lua` were implemented to prevent the case of the client giving a command line argument `/arg X /arg2 ...` where `X` is an empty string, and `GetCommandLineArg(option, 1)` would end up returning `{"/arg2"}` because an empty string is not a token.

2024-12-09 00:48 UTC, lL1l1 commented on lua/ui/lobby/autolobby/components/AutolobbyArguments.lua
> +        end
the utils function will return an empty table for a non-existent key, so if we don't want to verify if a requested command line key is valid, then this function is not necessary as the default empty table return value is already implemented.

2024-12-09 00:48 UTC, lL1l1 commented on lua/ui/lobby/autolobby/AutolobbyController.lua
> +                    -- this way they are available in both the sim and the UI
```suggestion
                    -- tuck them into the game options. By all means a hack, but
                    -- this way they are available in both the sim (for replays) and the UI
```

2024-12-09 02:35 UTC, lL1l1 approved these changes
Tested on test server with accounts [TEC] clan `KAZAKHNYA` and `Straiken` and the fix works: clans, ratings, and divisions appear in the game options for both the live game and in the replay file. Although the style could be better, this PR is due for a hotfix and it is functional, so I'm approving it.
```
UI_Lua print(repr(SessionGetScenarioInfo().Options))
```

2024-12-10 00:33 UTC, merged