Include the projectile in the OnMissileIntercepted callback
FAForever/fa pull request #6601
Opened 2024-12-26 20:43 UTC by maudlin27

As certain information may be included on the projectile that is of interest to AI when the missile is intercepted

## Description of the proposed changes
Adds the projectile to the onmissileintercepted callback, for if the projectile contains information of use to the AI.

## Testing done on the proposed changes
Did a destructive hook of the code change to check it provided the desired functionality.

## Additional context
The target position provided from the callback is unreliable; this way when a projectile is created I can record against the projectile the intended unit target, and then access this when the intercepted callback is triggered.

2024-12-26 20:48 UTC, maudlin27 commented
If any issues with this or want to discuss please ping me on discord; I've already covered the scenario with a destructive hook for M28 but figured it'd be worth adding to core functionality to be of benefit more generally

2024-12-27 10:07 UTC, Garanas commented
@relent0r I think we spoke of this a few days ago, what are your thoughts about this?

2024-12-27 10:08 UTC, Garanas commented on lua/sim/Projectile.lua
Please also update the definition in the unit class to include the additional parameter.

2024-12-28 02:39 UTC, relent0r commented
> @relent0r I think we spoke of this a few days ago, what are your thoughts about this?

If its what I think it is its a little different. Maudlin found that when the Aeon TMD intercepted missiles the position being returned by the callback was the TMD rather than the target position. I believe this was a way that Maudlin could track what happened to the missile.

2025-02-14 08:18 UTC, maudlin27 commented on lua/sim/Projectile.lua
I've updated Unit.lua's OnMissileIntercepted, is that what you meant by this?

2025-04-04 09:59 UTC, 4z0t requested changes

2025-04-04 09:59 UTC, 4z0t commented on lua/sim/Unit.lua
> +    OnMissileIntercepted = function(self, target, defense, position, self)
second `self` replaces the first one. Shouldn't it be `missle`?

2025-04-10 21:07 UTC, maudlin27 commented on lua/sim/Unit.lua
> +    OnMissileIntercepted = function(self, target, defense, position, self)
yes thanks, I've updated

2025-04-10 21:38 UTC, 4z0t approved these changes

2025-04-10 23:15 UTC, merged